### ISSUE TITLE
Profile Cover

### ISSUE THREAD

**Issue by KingAsta** [gwillem/freeflarum.com#100]
It would be great if you add the ProfileCover extension:

https://discuss.flarum.org/d/23437-profile-cover

Thanks!

**Comment by CWKevo** [comment]
First of all, we have a template for extension requests, which you didn't use. Please, do that next time you will request an extension, as it is easier for us to review and approve the requests.

And secondarily, FreeFlarum does not currently support any extensions that allow direct file upload to FreeFlarum, mainly for security reasons. We're sorry. 

But with some HTML & CSS knowledge, it could be actually possible to replicate this extension, however everything would have to be manual (done by admins, as they would have to put the CSS for every member individually, and images would have to be hosted at external server, outside of FreeFlarum).
