### ISSUE TITLE
Flarum Moderation Warnings by askvortsov

### ISSUE THREAD

**Issue by Bluejeanx** [gwillem/freeflarum.com#103]
__Packagist URL for extension:__
[https://packagist.org/packages/askvortsov/flarum-moderator-warnings](https://packagist.org/packages/askvortsov/flarum-moderator-warnings)

__Why we should install this extension?__
You should install extension since this provides a solid way to warn users for misbehavior on a community's forum. This would benefit multiple communities that have rules that don't warrant a suspension but instead a warning. 

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__ [Discuss Forum Extensions](https://discuss.flarum.org/d/22190-extensions-of-discuss )

This extension is being actively used the official Discuss forum and the discuss forum is always on the latest BETA release meaning it is still compatible with BETA 13. 

![image](https://user-images.githubusercontent.com/29443411/83933316-7722c100-a775-11ea-8eb5-ed23a1c4bbbd.png)

**Comment by CWKevo** [comment]
Thank you for your extension request, that's really nice first-issue you have there.
For me personally, this seems like a nice and useful extension for forums that are seeking for a warning system. +1 from me :)

**Comment by Anonymyous678** [comment]
⬆️ (upvote) for me!
Please add it.

**Comment by ririko5834** [comment]
I like this extension!

**Comment by CWKevo** [comment]
Installed!
