### ISSUE TITLE
Pipetables

### ISSUE THREAD

**Issue by luatdolphin** [gwillem/freeflarum.com#106]
__Packagist URL for extension:__

https://packagist.org/packages/kvothe/pipetables
composer require kvothe/pipetables

__Why we should install this extension?__

We can active pipeline for flarum

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

![image](https://user-images.githubusercontent.com/2277080/84615447-3eac8100-aef3-11ea-9ac8-4b87090421b3.png)
![image](https://user-images.githubusercontent.com/2277080/84615580-977c1980-aef3-11ea-9856-95adb7e9cfaf.png)
Thanks!!!

**Comment by CWKevo** [comment]
Additionaly you can see #23. I saw a statement that this was supported by the formatting extension, however it seems that it is not the case.

Thank you for your request, please keep in mind that it requires 5 upvotes to be honored :)
