### ISSUE TITLE
User list

### ISSUE THREAD

**Issue by dorienh** [gwillem/freeflarum.com#107]
A few users tried to register before my email was setup. The result is that their email address is 'taken' but they cannot activate their account. Normally I'd check the database so I can retrieve their username and delete the profile at u/username. Now I don't know their usernames... 

Could we have a user list extension activated so we can address this? 

__Packagist URL for extension:__

https://packagist.org/packages/fof/user-directory

__Why we should install this extension?__

[//]: # "In short, tell us why we should install this extension and how it would be beneficial towards the community."

So we can delete spam users and fix registrations that have gone wrong. 

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

This module came recommended on discuss.flarum.org instead of other user lists. It has no incompatibility flags. https://discuss.flarum.org/d/5682-user-directory-by-friendsofflarum/19

Not listed as incompatible, in fact it was recommended on the forum.

**Comment by CWKevo** [comment]
This extension already exists in FreeFlarum (FoF User Directory).
