### ISSUE TITLE
Tags Extension

### ISSUE THREAD

**Issue by nprh** [gwillem/freeflarum.com#109]
Hi there,

I’m having problems with the Tags extension. Most of the extension and it’s headings/buttons have “flarum-tags.forum.index.tags_link” or similar prefixing most functions. Also, when creating a second primary tag it’s creating it as a secondary tag to the first primary tag I created.

Thanks in advance.

Nick

**Comment by CWKevo** [comment]
Hello,
the buttons have improperly translated strings. This can occur when you have disabled the English extension and use other extension that didn't translate the buttons, or (more likely) when some other extension causes incompatibility. Did you disable English extension?

As for primary and secondary tags, they can be re-ordered and moved by dragging them up or down. I assume the extension automatically creates a primary tag and nests it under another primary tag, just drag the tag out and you should be good to go.

**Comment by nprh** [comment]
Hello,

Thanks, that worked on both counts!

I had the English extension installed but I think at some point I accidentally enabled another language then reversed that, so maybe it was that. Anyhow, I disabled the English extentsion and re-installed it, and that cleared the isssue.

As for the secondary tags, dragging worked.

Thanks.

**Comment by khalby786** [comment]
Something similar happened to me, and turns out it was FoF Filter extension causing this problem. Disabling the extension solved it for me.

**Comment by CWKevo** [comment]
> Something similar happened to me, and turns out it was the FoF Filter extension causing this problem. Disabling the extension solved it for me.

Yes, that's known in #123

This issue should be resolved in Flarum `beta.14`.
