### ISSUE TITLE
Create User Modal

### ISSUE THREAD

**Issue by sudip2003** [gwillem/freeflarum.com#110]
__Packagist URL for extension:__

[//]: # "https://packagist.com/..."

https://packagist.org/packages/clarkwinkelmann/flarum-ext-create-user-modal

__Why we should install this extension?__

[//]: # "In short, tell us why we should install this extension and how it would be beneficial towards the community."

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

I need this extension since I am building small private clubs where others can be only added by the admin. The sign-up option should not be available and hence Doorman is not an option.

Will try to get upvotes, though I am not in the tech industry and am working on this solo.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

https://discuss.flarum.org/d/22608-create-user-modal

The discussion shows that the extension should be working.

**Comment by CWKevo** [comment]
You could achieve similar results with this guide: https://www.freeflarum.com/docs/how-to/basics/private-forum/
I don't feel like this is an extension that you really need. You can create accounts for your friends, which is similar to the user creation extension you requested.

**Comment by sudip2003** [comment]
Thanks for checking out my issue :) ... I guess for the solution you mentioned will need the users to be created in advance and then sign-up needs to be closed? In my use case, we might need to keep adding new users. I guess will have to reopen sign-ups, sign them up and then close sign-ups again in that case?

**Comment by CWKevo** [comment]
Yes, that's what I meant. I can check the extension, but for me it seems that it isn't something that is required to create an user. I'd suggest not adding much extensions, because sooner, something breaks. This extension doesn't seem like a huge forum-breaker though, so we could give it a try :)

**Comment by sudip2003** [comment]
Appreciate your response! I think I can try it like this for now. Will maybe update if I see any issues popping up for me, later. 

In any case, if it is possible, you could add this extension to your backlog maybe :)

**Comment by CWKevo** [comment]
I think that we could add this extension and if problems arrive, we can remove it. It seems minimalistic by only playing with the API & does not require extra setup.

Therefore, installed! You can check it out.
