### ISSUE TITLE
Todo: upgrade analytics & sitemap to fof version

### ISSUE THREAD

**Issue by gwillem** [gwillem/freeflarum.com#111]

**Comment by CWKevo** [comment]
Is this still relevant? Major extension update was already done...

**Comment by gwillem** [comment]
Yes I think so

![image](https://user-images.githubusercontent.com/1145479/93612522-e2fd0280-f9cf-11ea-81f2-0735d820c801.png)

**Comment by gwillem** [comment]
NB: upon forum creation, fof/sitemap is automatically enabled. We may need to modify the deployment code

**Comment by CWKevo** [comment]
I saw it in the commands and stuff, yes we will need to do that too.
