### ISSUE TITLE
Tags Extension Issue

### ISSUE THREAD

**Issue by SemiClickbait** [gwillem/freeflarum.com#112]
**Issue with the tags extension**
Button labels are displayed weirdly.

![image](https://user-images.githubusercontent.com/23344210/86850895-075b6b00-c080-11ea-9067-07dbe5f0f0b3.png)
---
![image](https://user-images.githubusercontent.com/23344210/86850928-17734a80-c080-11ea-8b3d-3c4c705e862a.png)
---
![image](https://user-images.githubusercontent.com/23344210/86850951-23f7a300-c080-11ea-8c91-309eba43f95c.png)

**Comment by gwillem** [comment]
Its a known issue with Flarum, you need to refresh your cache (from main
admin page) after enabling the tags extension

**Comment by CWKevo** [comment]
Please, see also #109 for more information and let us know if the steps to fix your issue there worked.

**Comment by SemiClickbait** [comment]
Refreshing the forum cache seems to have helped.
Thanks!
