### ISSUE TITLE
Tls 1.0 and 1.1 disable

### ISSUE THREAD

**Issue by sysdl132** [gwillem/freeflarum.com#113]
https://www.ssllabs.com/ssltest/analyze.html?d=www.freeflarum.com
- What was wrong:
SSL tester reports that the TLS 1.0 and 1.1 enabled website will cause TLS error. 
https://blog.qualys.com/ssllabs/2018/11/19/grade-change-for-tls-1-0-and-tls-1-1-protocols?_ga=2.145635252.1436766803.1594287367-2069693307.1594287367
- The way to fix the error
Very simple:disable 1.0 and 1.1

**Comment by gwillem** [comment]
Thank you, fixed!
