### ISSUE TITLE
Shout Private Messaging

### ISSUE THREAD

**Issue by quitd** [gwillem/freeflarum.com#114]
__Packagist URL for extension:__
https://packagist.org/packages/kyrne/shout

__Why we should install this extension?__

[//]: # "In short, tell us why we should install this extension and how it would be beneficial towards the community."

1. useful for real-time messaging on Flarum
2. easy to use UI (like FB Messenger, or other messaging app)
3. messages are encrypted

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
updated 20 hours ago

**Comment by CWKevo** [comment]
This seems like a very cool extension, however it kind of relies on the Websockets extension which is paid.

Websockets aren't necessary for the extension to function properly, but without that the messages will not appear in real time and you won't have the "Typing..." status etc... This kind of defeats the purpose of the extension in my opinion and you should consider if you'd like the Byobu extension as an alternative.

I'll leave this open, but keep in mind that FreeFlarum does not add paid extensions currently, not even if you pay for it yourself... Flarum's policy just does not allow that. You can decide whenever you still want the extension, despite the lack of real-time features.

**Comment by CWKevo** [comment]
Reopened in favour of #152
