### ISSUE TITLE
Discussion Templates (Per-tag)

### ISSUE THREAD

**Issue by quitd** [gwillem/freeflarum.com#115]
__Packagist URL for extension:__
https://packagist.org/packages/askvortsov/flarum-discussion-templates

__Why we should install this extension?__
1. makes creating discussions easier & faster

[//]: # "In short, tell us why we should install this extension and how it would be beneficial towards the community."

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
doesn't have the incompatible tag at the Flarum Discuss so...?

**Comment by ririko5834** [comment]
+1 from me. 
Please add it soon 🙏

**Comment by CWKevo** [comment]
Installed!
