### ISSUE TITLE
Welcome Widgets

### ISSUE THREAD

**Issue by quitd** [gwillem/freeflarum.com#116]
__Packagist URL for extension:__

https://packagist.org/packages/the-turk/flarum-welcome-widgets

__Why we should install this extension?__
1. Lets users know what's been changed since their last visit.
2. makes the forum looks good

[//]: # "In short, tell us why we should install this extension and how it would be beneficial towards the community."

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
posted at Flarum Discuss 18 hours ago

**Comment by ririko5834** [comment]
+1 from me. 
Please add it soon 🙏

**Comment by CWKevo** [comment]
> **Known issues:**
> 
> - Widgets won't show up when you login via an external identity provider (like GitHub, Twitter, Facebook etc.) due to a bug in flarum/core.

This might be a problem for some forums, since some use these login options. However, I think that this shouldn't be a big problem and this extension might be useful for giving forum users some insights of forum statistics without needing to go to Administration.

**Comment by CWKevo** [comment]
Installed now!
