### ISSUE TITLE
FoF Filter causes text distortion

### ISSUE THREAD

**Issue by meetdilip** [gwillem/freeflarum.com#117]
**Describe the bug:**

[//]: # "A clear and concise description of what the bug is."

When enabled, FoF Filter extension causes text distortion as seen below, even with all other extensions disabled

![fof filter](https://i.imgur.com/TbePvsk.png)

**My FreeFlarum forum URL:**

https://admintech.flarum.cloud/

[//]: # "For example, https://x.freeflarum.com where 'x' is your forum name."

**To Reproduce:**

1. Go to ' Admin Panel '
2. Click on 'enable FoF Filter extension'
3. Check text in the left sidebar
4. Check text is the front end of the website
**Expected behavior:**

[//]: # "A clear and concise description of what you expected to happen."

No distortion of the text. Should appear as is

**Screenshot(s):**

[//]: # "If applicable, add screenshot(s) to help explain your problem."

**Comment by CWKevo** [comment]
Hello,
this is a common Flarum cache bug that can be fixed by clearing the cache from your Administration panel.

If that didn't work, you can try my other possible solutions in #109 #112.

Hope that helped!

**Comment by meetdilip** [comment]
Thanks @CWKevo . I tried the following with all other extensions but " English " disabled

1. Cleared cache through the dashboard
2.  Installed FoF filter

now the text distortion occurs

3. Toggled the English pack

no result

4. Cleared cache through the dashboard

no change

5. Checked the front end

distorted text there too


Clearing cache or toggling English pack is not capable of changing the distorted text ( on both back-end and interface ).

I had to remove FoF Filter before anything really happens.

Tried using the latest Firefox and Opera.

**Comment by CWKevo** [comment]
Strange. I can confirm that this happens on my forum as well. No errors in developer console either. Using Chrome.
I'm 99% sure that this is an issue in the extension itself, but this does not mean that it is couldn't be a FreeFlarum issue.

**Comment by meetdilip** [comment]
@CWKevo Any chance we can test _FoF Filter_ on an independent Flarum installation outside of the Free Flarum setup ? Thanks.

**Comment by CWKevo** [comment]
You could try running Flarum on your own, locally by using something like [WampServer](https://www.wampserver.com/en/). However, I'd suggest to wait for @gwillem for additional assistance.

**Comment by meetdilip** [comment]
> I'd suggest to wait for @gwillem for additional assistance.

Sure :)

**Comment by gwillem** [comment]
Hi, it is highly unlikely to be a FreeFlarum issue, as we run stock-Flarum only. It may be an conflict with another extension, but I don't have the resources to debug that, sorry. You should try debugging it on your own, or ask the extension author.
