### ISSUE TITLE
Suddenly Stopped Working | FreeFlarum

### ISSUE THREAD

**Issue by NamVr** [gwillem/freeflarum.com#118]
**Describe the bug:**

[//]: # "Suddenly, my freeflarum website stopped working, however it has 3 members only yet, it was new."

**My FreeFlarum forum URL:** https://support.teamelites.gq/

[//]: # "For example, https://x.freeflarum.com where 'x' is your forum name."

**To Reproduce:**

<!-- Brief and clear steps to reproduce the behavior, for example:
Go to the URL and you will see everything.

**Expected behavior:** The normal forum page.

[//]: # "A clear and concise description of what you expected to happen."

**Screenshot(s):**

[//]: # "If applicable, add screenshot(s) to help explain your problem."

**Comment by NamVr** [comment]
ERROR INFO:
Flarum encountered a boot error (ReflectionException)
Class FoF\Drafts\Listeners\AddRelationships does not exist
thrown in /app/vendor/illuminate/container/Container.php on line 779

**Comment by benjaminwolkchen** [comment]
That's exactly what happened for my right now.
I enabled the Drafts extension.

**Comment by NamVr** [comment]
Hi There!

Thank you for contacting us. We are here to help you. We just have received a message from your side and soon we are going to take a action on it. We really appreciate your patience. We usually reply within 1-2 hours, but sometimes, it can take up to 24-48 hours.

Till then, you can check our website: https://namanvrati.cf and browse plans and services.
Please note: We are going to reply you, so no need to trouble. Just wait and do not submit multiple requests via emailing/ticket system. Spam and multiple requests are usually ignored by our email service filter.

Thank You!

Regards, 
Naman Vrati.

NamVr Freelancing: https://namanvrati.cf

**Comment by CWKevo** [comment]
What extensions have you had enabled by the time you enabled Drafts? Seems like a conflict between extensions for me (happens quite often). If that's the case, we can't help you much and you should contact the extension authors.

**Comment by NamVr** [comment]
Yeah and there is no place even we can self-troubleshoot.
We have no access to our backends.

If we had the access, I would disable it directly by removing the extension by deleting it from FTP and then my site would return.

**Comment by CWKevo** [comment]
> Yeah and there is no place even we can self-troubleshoot.
> We have no access to our backends.
> 
> If we had the access, I would disable it directly by removing the extension by deleting it from FTP and then my site would return.

Sadly, we can't allow this :/

**Comment by NamVr** [comment]
Yeah I can understand. But what about now?

**Comment by NamVr** [comment]
Actually what happened that this was all sudden. I was writing an post discussion when it all happened.
Also the draft extension was enabled a week ago, so it must say the problem a week ago right?

**Comment by NamVr** [comment]
Well I have one thing, I have two sites in freeflarum, one my friend runs and one I.
Actually both of the sites are not working.

forum.namanvrati.cf
support.teamelites.gq

**Comment by CWKevo** [comment]
> Also the draft extension was enabled a week ago, so it must say the problem a week ago right?

Then it is indeed a bug between extensions. Drafts fired an event upon creating a discussion that failed and now it bricked your forum. I'd recommend you to contact the extension authors yourself, until then @gwillem can unbrick your installation.

**Comment by NamVr** [comment]
Can we just disable the Draft extension?
I guess there is no need which is breaking my forums.
And I thought it would be useful, but there is no urgent need.

**Comment by NamVr** [comment]
Whomsoever is the author, kindly unbrick my installations:
support.teamelites.gq
forum.namanvrati.cf

Please disable/uninstall Drafts extension. I don't need it.

**Comment by CWKevo** [comment]
Yes, it is possible for FreeFlarum to unbrick your Flarum forum.

Also please note that FreeFlarum does not have the appropriate tools to debug extension incompatibilities and such issues, nor do we maintain extensions - it's up for their authors to resolve that. All we can do is just to disable the extension and possibly uninstall it to prevent more forums from being bricked. Please, be patient.

**Comment by NamVr** [comment]
Yes I can completely understand.
Sure there is no issue, I am patient and let me know when it is resolved (disabled/uninstalled)

**Comment by NamVr** [comment]
@gwillem Is he the owner? I am just asking.

**Comment by CWKevo** [comment]
> @gwillem Is he the owner? I am just asking.

Yes, he is the main man behind the amazing FreeFlarum.

I am but a wise person helping out others to my capabilities :')

**Comment by NamVr** [comment]
That's really nice and I appreciate your team. I discovered free flarum a weeks ago only and was trying to create my small community for my new company. Really Thanks for this amazing service and I wish I could have contributed I am too young and whenever I will earn a contribution will be on my way to support the development of these kind people supporting us.

**Comment by NamVr** [comment]
Well @gwillem I hope you will seek after this issue and thanks for your help here.
I would like to get a notification here if the issue is resolved?

Regards,

**Comment by gwillem** [comment]
Hi all, your reported forums are again working now. The error was caused by an upgrade of all extensions, see https://discuss.flarum.org/d/7585-free-flarum-hosting-on-an-expert-platform-by-freeflarum-com/1468

A check/cache flush is in progress for all other forums. Please add a message here if you still have issues after 1 hour.

**Comment by NamVr** [comment]
Thank You Very Very Much it is fine and back working.

Exactly I was thinking that only, this maybe because of upgrade!
