### ISSUE TITLE
Catch The Fish

### ISSUE THREAD

**Issue by quitd** [gwillem/freeflarum.com#120]
__Packagist URL for extension:__
https://packagist.org/packages/clarkwinkelmann/catch-the-fish

__Why we should install this extension?__
1. for fun, so users don't get bored ..?

[//]: # "In short, tell us why we should install this extension and how it would be beneficial towards the community."

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
There is no Incompatible tag at the Flarum Discuss post

**Comment by CWKevo** [comment]
Seems like an unique type of extension which we haven't got to see at FreeFlarum yet. Keep in mind that your request needs more upvotes, so ask your friends to hit the thumbs up button.

**Comment by ririko5834** [comment]
I like this extension. Please add it if it is possible!

**Comment by CWKevo** [comment]
If this is compatible with beta.14 after we update, I plan to add it as an April Fools joke.

**Comment by CWKevo** [comment]
Added 1 month later, because the extension became beta.16 while we were still on beta.15
