### ISSUE TITLE
Simplified Chinese Language Pack / 简体中文语言包

### ISSUE THREAD

**Issue by lynnguo666** [gwillem/freeflarum.com#122]
__Packagist URL for extension:__
https://discuss.flarum.org/d/22690-simplified-chinese-language-pack

[//]: # "https://packagist.com/..."

__Why we should install this extension?__
This plugin fixes the problem that some plugins do not work under Chinese localization

[//]: # "In short, tell us why we should install this extension and how it would be beneficial towards the community."

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://discuss.flarum.org/d/22690-simplified-chinese-language-pack

**Comment by Gideon357** [comment]
Plus one for this. Please see my issue #156 as well. It brings a great feature to Flarum.

**Comment by CWKevo** [comment]
Added!
