### ISSUE TITLE
Flarum Language Issues

### ISSUE THREAD

**Issue by CWKevo** [gwillem/freeflarum.com#123]
Hello,
as many of you have reported that their forum has broken text/language, I have decided to create this issue so that we can all discuss it here and assign it a higher priority label because many users are being affected.

**About the issue**
Now, more about the issue. The broken text is basically that normal text on your forum gets replaced by keys such as `core.login_example` instead of the actual `Log In` text.

As far as we know, it can occur by enabling particular extensions on your forum. We sadly cannot debug this kind of issue due to lack of tools that would allow us to do so. The real cause of this issue is unknown - sometimes it occurs when enabling certain extensions, but they aren't compatible when enabled together, sometimes it can occur when you disable the English language, etc...

**How languages at Flarum work?**
Flarum language packs work the way that they have defined language keys in their YAML files. Each key, such as `core.navbar.button_links` has assigned a string to it, such as the actual text you see. When something goes wrong halfway through, Flarum has no other choice but to just print out the key because an error occured and it was unable to reach the string.

**Possible causes:**
This error can (possibly) occur when:
- you have enabled "Tags" - this is a common issue in beta.13 and can be solved easily by clearing your cache (most errors are solved this way);
- you have enabled some extension(s), most likely language ones, and you didn't clear your Flarum cache (you can do so from your admin panel);
- you have enabled non-language extension, yet the extension is incompatible with other extension(s) you have enabled at (Free)Flarum and one of the victims is the language;
- you have disabled English extension. Please, do not do that - leave it enabled, as it allows for other extensions to fallback to English strings in case some extension didn't translate some keys (I'm not sure how this one really works, but one user has reported this issue and it seemed like they indeed had issues with the English language pack and re-enabling it helped).
- some extensions using duplicate keys (Flarum doesn't know to which one assign what string and it breaks);
- using FoF Filter extension, which breaks all the text in case when you use the default mail settings ([see the comments](https://github.com/gwillem/freeflarum.com/issues/123#issuecomment-672217838));
- other issues, mostly incompatibility between extensions.

We try our best to finally put this issue to rest, however it is a difficult problem. **Please, use this issue to discuss this problem further.** We want to know as much as we can about this issue so we can fix it, and report it to Flarum and extension authors (if needed).

**This issue was also discussed here**
- #99
- #109 
- #112 
- #121 
- #138 
- #154 

**Want to help us?**
You can test Flarum locally and debug the issue, if you have the appropriate tools to do so.
FreeFlarum is run entirely in @gwillem and mine's spare time. Consider making a [donation](https://freeflarum.com/donate) to show us your appreciation towards this project.

~ *Team FreeFlarum*

**Comment by ghiathkamel** [comment]
I have good news, I fixed this issue by only disable FoF Filter 0.1.0-beta (Filter out words and phrases from forum posts)

**Comment by CWKevo** [comment]
Great, some users have had problems with Filter earlier, I suggest to remove it, report the issue to their authors and wait for a fix.

**Comment by ghiathkamel** [comment]
i tried to uninstall it but no luck, it still there

**Comment by CWKevo** [comment]
That's because you cannot uninstall extensions by yourself, FreeFlarum has to do it.

**Comment by sysdl132** [comment]
asked flarum.awaiting response...

**Comment by CWKevo** [comment]
It's often more just an extension incompatibility, so it's up to the extension's authors to fix it and we have to report it to the authors. The next update will bring some API changes, so hopefully extensions will become more stable.

**Comment by sysdl132** [comment]
https://discuss.flarum.org/d/5131-friendsofflarum-filter/113

**Comment by CWKevo** [comment]
I see. I will setup a local test forum tomorrow to debug the issue further, so we can determine whenever the cause is in the extension or FreeFlarum.

**Comment by CWKevo** [comment]
So, I have installed exactly the same extensions with the same versions as FreeFlarum has and I was not able to reproduce the issue, leaving me thinking that there might be something wrong in FreeFlarum that breaks the forum text, however, I'm not sure what it is.

**Comment by CWKevo** [comment]
Upon further debugging, I have found the cause of this behavior. When your mail settings are empty/default, the language will break. As soon as you use a custom configuration, `fof/filter` will work normally.

For now, I'd encourage users that would like to use the Filter extension to use custom mail settings (currently once it's set, it cannot be undone - you can use free services such as GMail too - see [the documentation](https://www.freeflarum.com/docs/how-to/advanced-setup/configuring-mail/) for more info). Or you can just disable the Filter extension.

**Comment by CWKevo** [comment]
> Hello,
> as many of you have reported (more than 4 people, but the real number of this issue might be higher) that their forum has broken text/language, I have decided to create this issue so that we can all discuss it here and assign it a higher priority label because many users are being affected.
> 
> **About the issue**
> Now, more about the issue. The broken text is basically that normal text on your forum gets replaced by keys such as `core.login_example` instead of the actual `Log In` text.
> 
> As far as we know, it can occur by enabling particular extensions on your forum. We sadly cannot debug this kind of issue due to lack of tools that would allow us to do so. The real cause of this issue is unknown - sometimes it occurs when enabling certain extensions, but they aren't compatible when enabled together, sometimes it can occur when you disable the English language, etc...
> 
> **How languages at Flarum work?**
> Flarum language packs work the way that they have defined language keys in their YAML files. Each key, such as `core.navbar.button_links` has assigned a string to it, such as the actual text you see. When something goes wrong halfway through, Flarum has no other choice but to just print out the key because an error occured and it was unable to reach the string.
> 
> **Possible causes:**
> This error can (possibly) occur when:
> 
> * you enabled some extension(s), most likely language ones, and you didn't clear your Flarum cache (you can do so from your admin panel);
> * you have enabled non-language extension, yet the extension is incompatible with other extension(s) you have enabled at (Free)Flarum and one of the victims is the language;
> * you have disabled English extension. Please, do not do that - leave it enabled, as it allows for other extensions to fallback to English strings in case some extension didn't translate some keys (I'm not sure how this one really works, but one user has reported this issue and it seemed like they indeed had issues with the English language pack and re-enabling it helped).
> * some extensions using duplicate keys (Flarum doesn't know to which one assign what string and it breaks);
> * using FoF Filter extension, which breaks all the text in case of default mail settings (see comments);
> * other issues, mostly incompatibility between extensions.
> 
> We try our best to finally put this issue to rest, however it is a difficult problem. **Please, use this issue to discuss this problem further.** We want to know as much as we can about this issue so we can fix it, and report it to Flarum and extension authors (if needed).
> 
> **This issue was also discussed here**
> 
> * #99
> * #109
> * #112
> * #121
> * #138
> 
> **Want to help us?**
> You can test Flarum locally and debug the issue, if you have the appropriate tools to do so.
> FreeFlarum is run entirely in @gwillem and mine's spare time. Consider making a [donation](https://freeflarum.com/donate) to show us your appreciation towards this project.
> 
> ~ _Team FreeFlarum_

**Comment by CWKevo** [comment]
Closing this, as most of this stuff has been fixed now. If you experience more of this kind of error, just reply.
