### ISSUE TITLE
Extension settings popup does not appear

### ISSUE THREAD

**Issue by ghiathkamel** [gwillem/freeflarum.com#124]
i have an issue with enabling login after enabling must have popup message to enter the Client ID and Client Secret but nothing happened i cant enter/Paste Client ID and Client Secret.
this happend with Log In with Discord and GitHub login and twitter?
what can i do

**Comment by CWKevo** [comment]
You can't paste the text into the inputs? That seems like a problem on your side from me.

In case the popup doesn't appear, hover on the extension in the extension list and click on the three-dots to open the extension settings.

**Comment by ghiathkamel** [comment]
thank you for your reply, there is no box to paste the text, the popup doesn't appear, also there is no three-dot icon, google login have but those don't have :(

**Comment by ghiathkamel** [comment]
![Screenshot_2020-07-29 WRDO Forum(1)](https://user-images.githubusercontent.com/60829719/88874002-02f02100-d1ec-11ea-99fc-5c698cadfe7a.png)
![Screenshot_2020-07-29 WRDO Forum](https://user-images.githubusercontent.com/60829719/88874004-0388b780-d1ec-11ea-9660-86527f037f8d.png)
![Screenshot_2020-07-29 WRDO Forum(3)](https://user-images.githubusercontent.com/60829719/88874005-0388b780-d1ec-11ea-840b-377ae6496415.png)
![Screenshot_2020-07-29 WRDO Forum(2)](https://user-images.githubusercontent.com/60829719/88874006-0388b780-d1ec-11ea-9126-2faea085f34d.png)
please take a look on the attached photos , there is no three-dot icon :(

**Comment by CWKevo** [comment]
You must hover on them with your mouse cursor for the menu button to appear (as if you're about to click on them but you won't).
If they still don't appear, try different browser (Chrome is recommend) and also check if you don't have any browser extension installed that blocks the menu.

If nothing works, it is a Flarum bug, but I'm sure it is something on your side.

**Comment by ghiathkamel** [comment]
Hello, i tried chrome and other browsers no luck, how can i restart my server , or reset everythings 
please help

**Comment by ghiathkamel** [comment]
Hi, i tried new forum and it works , only my forum not works , maybe need restart the server 
https://wrdorg.flarum.cloud

**Comment by CWKevo** [comment]
Easiest fix might be to just re-enable the extension (disable it and then enable it again), the settings popup should appear after enabling the extension. Have you tried that?

**Comment by ghiathkamel** [comment]
yes i tried that many times , i am working on setup a new forum :(
maybe FoF filter did that to my forum

**Comment by CWKevo** [comment]
What's the invite code for your forum? Can I register an account there and see for myself?

**Comment by ghiathkamel** [comment]
how can i get the invite code 
https://wrdo.freeflarum.com/
i can give you the password if you like

**Comment by CWKevo** [comment]
Don't give your password to anyone, the invite code is from the Doorman extension I believe, so please disable it and then I can register an account.

**Comment by ghiathkamel** [comment]
admin
Ke4eYcrs
please use this , i can change later . no problem

**Comment by ghiathkamel** [comment]
i didn't find Doorman extension

**Comment by CWKevo** [comment]
Can confirm that it doesn't work for me either, so it's a bug in Flarum. All extensions don't have any settings that can be modified, please wait for @gwillem for a fix, however this is a strange issue I have never encountered. Looks like some other extension messed it up.

**Comment by ghiathkamel** [comment]
Thank you my friend , yes i think so , Looks like some other extension messed it up,
okay i will wait , thanks :)

**Comment by gwillem** [comment]
logs say:
```
[2020-07-30 00:13:15] production.ERROR: InvalidArgumentException: Missing client credentials key [identifier] from options. in /app/vendor/league/oauth1-client/src/Client/Server/Server.php:390
Stack trace:
#0 /app/vendor/league/oauth1-client/src/Client/Server/Server.php(63): League\OAuth1\Client\Server\Server->createClientCredentials(Array)
#1 /app/vendor/flarum/auth-twitter/src/TwitterAuthController.php(62): League\OAuth1\Client\Server\Server->__construct(Array)
```

**Comment by CWKevo** [comment]
I'm pretty sure that when the settings first appeared, you didn't input the Client ID and/or other arguments, you just closed it. Now it has no arguments and breaks all settings(?) Strange.

**Comment by gwillem** [comment]
Ok, it is a bug in the Arabic language pack. See here: https://github.com/ziymed/lang-arabic/issues/4

I will be removing Arabic for now.

**Comment by ghiathkamel** [comment]
awsome, thank you very much, I am very happy now 💯

**Comment by ghiathkamel** [comment]
> Ok, it is a bug in the Arabic language pack. See here: [ziymed/lang-arabic#4](https://github.com/ziymed/lang-arabic/issues/4)
> 
> I will be removing Arabic for now.
awsome, thank you very much 💯
