### ISSUE TITLE
':true}); ');

### ISSUE THREAD

**Issue by ghiathkamel** [gwillem/freeflarum.com#125]
Hello everyone, i have this message on the top of my forum, how can i remove it , thanks
https://forum.wrdo.org/
![Screenshot_2020-07-31 WRDO Forum](https://user-images.githubusercontent.com/60829719/89060567-3dafa180-d331-11ea-9e0b-80c5b473d2e8.png)

**Comment by CWKevo** [comment]
![Screenshot_20200731_194718](https://user-images.githubusercontent.com/39010496/89062425-b4b35d00-d366-11ea-998b-ac3497cbc14d.jpg)

Orange shows the text, red shows broken `<script>` tag.
Have you added custom HTML code into your forum header (or elsewhere)? If so, remove the first underlined `</script>`. If it comes from an extension, it is a bug in that extension.

**Comment by ghiathkamel** [comment]
Thank you very much , i really appreciate your time :)
i will take a look

**Comment by ghiathkamel** [comment]
issue solved, thanks :)
