### ISSUE TITLE
 WordPress Single Sign On (SSO)

### ISSUE THREAD

**Issue by niteshmanav** [gwillem/freeflarum.com#128]
__Packagist URL for extension:__

https://packagist.org/packages/maicol07/flarum-ext-sso

__Why we should install this extension?__

This is currently the only extension which enables the way to sync users from WordPress sites to Flarum community. So, please include it. 

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

Discussion link - 

https://discuss.flarum.org/d/21666-php-and-wordpress-single-sign-on-sso

It is based on an old extension called "Single Sign On" which is loved since March 2017.

**Comment by CWKevo** [comment]
Added!

**Comment by CWKevo** [comment]
Reopened (https://discuss.flarum.org/d/7585-free-flarum-hosting-on-an-expert-platform-by-freeflarum-com/2352).

Should there still be interest in this, it'll be added when it is beta.16 compatible and when we update all forums to that version.

**Comment by radiogyan** [comment]
Hey @CWKevo 
It is now beta16 compatible as per the dev (https://extiverse.com/extension/maicol07/flarum-ext-sso). Can you please add it to FreeFlarum whenever possible? 
Thanks.

**Comment by CWKevo** [comment]
It'll be added after we update to beta.16

**Comment by CWKevo** [comment]
Added!
