### ISSUE TITLE
Loading PAGE ERROR

### ISSUE THREAD

**Issue by ch-LyricEpic** [gwillem/freeflarum.com#130]
# My forum loading page has an error. How is this situation triggered?     
I confirmed that my action was to turn off the markdown syntax. After closing, the problem occurred. But now, after reopening the markdown syntax, there is still a problem

**Comment by CWKevo** [comment]
So, you disabled the Markdown extension and a problem occurred. You tried re-enabling it and there is still an error. Is that correct?

What is your FreeFlarum forum address? And what does the error message say? Could you be more specific please?

**Comment by ch-LyricEpic** [comment]
It's exactly what you described. The link to my freeflarum is https://zhonghuajia.flarum.cloud/. After entering, only "error loading forum, please force you to try again first". Unable to login or display more information. Because I can't log in, I can't enter the admin management page, so I can't provide more information. Sorry.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gwillem/freeflarum.com"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月2日(星期天) 中午1:05
收件人:&nbsp;"gwillem/freeflarum.com"<freeflarum.com@noreply.github.com&gt;;
抄送:&nbsp;"叶州 普通账户"<177264839@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gwillem/freeflarum.com] Loading PAGE ERROR (#130)





 
So, you disabled the Markdown extension and a problem occurred. You tried re-enabling it and there is still an error. Is that correct?
 
What is your FreeFlarum forum address? And what does the error message say? Could you be more specific please?

**Comment by CWKevo** [comment]
Hmm, the forum loads fine for me. Perhaps there is a problem on your side, or with your user account.
Try accessing the page from Incognito mode. If it loads fine, try to login with your account. If the error occurs, there is a bug with your user account.

**Comment by ch-LyricEpic** [comment]
HMM, still unable to login. This problem has not been solved, I temporarily deleted the forum and registered a new forum. Thank you. 177264839 邮箱：177264839@qq.com 签名由 网易邮箱大师 定制 On 08/04/2020 21:09, Kevo wrote: Hmm, the forum loads fine for me. Perhaps there is a problem on your side, or with your user account. Try accessing the page from Incognito mode. If it loads fine, try to login with your account. If the error occurs, there is a bug with your user account. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by CWKevo** [comment]
Well then, I'll close this.
