### ISSUE TITLE
Keeping post actions (reply, like, etc...) always visible

### ISSUE THREAD

**Issue by ghiathkamel** [gwillem/freeflarum.com#131]
![alwasy on](https://user-images.githubusercontent.com/60829719/89133755-adb65700-d4ec-11ea-8582-96b38e5e25ed.png)
Hello everyone, how can i keep the reply button always on, like this attached photo, in the mobile browser works great only on pc browser not works you need to move your mouse to see those, what do you think, thanks

**Comment by CWKevo** [comment]
```
<style>button[title="Reply"] { display: block !important; }</style>
```

This code should work, just paste it into your forum's header. Not tested on LC thought.

**Comment by ghiathkamel** [comment]
I put this code on the embed box but not change, 
please take a look : https://www.wrdo.org/contact
on PC works when i make small size of the browser, but the large full size of the browser you need to move your mouse to see the buttons , what do you think , thanks

**Comment by CWKevo** [comment]
Well, I grabbed the selector while I was on phone, so maybe on PC it's different... If it's urgent, I can look into it for you tomorrow, but if you want to fix it on your own, you have to get the HTML element representing the Reply button. You can do that by going into Developer Tools and Inspector, then selecting the element. Easiest way is just to right click the Reply button and select "Inspect" (or similar) from the context menu, but if it makes no sense to you, I'd suggest you to just wait.

**Comment by ghiathkamel** [comment]
Thank you very much ,  its not urgent at all , i can wait , take your time
i want to keep the reply button and the three-dot and emoji always on

**Comment by CWKevo** [comment]
It seems that all the buttons are nested under the `Post-actions` class.

Try this code in your header:
```
<style>.Post-actions { display: block !important; }</style>
```

I don't know what method Flarum uses to hide those elements, whenever it's a `visibility` or `display` or `opacity` CSS option, so the solution might vary. Try to cycle through them all,:
```
<style>.Post-actions { opacity: 1.0 !important; }</style>
```

```
<style>.Post-actions { visibility: visible !important; }</style>
```

**Comment by ghiathkamel** [comment]
Thank you  , i will try those codes in the embed box ?

**Comment by CWKevo** [comment]
Not in the embed box, just add it into your header, or your forum's CSS styles (in that case, remove `<style>` and `</style>` tags).

**Comment by ghiathkamel** [comment]
![Header](https://user-images.githubusercontent.com/60829719/89240307-c0eb2480-d5c9-11ea-9826-d3de03216fe2.png)
Hello, i did try those three codes as shown in the attached photo, but no luck yet , if there is something missing please let me know

**Comment by ghiathkamel** [comment]
Yes thanks to GOD , now it works, i did write this codes 
![Header3](https://user-images.githubusercontent.com/60829719/89244036-82f2fe00-d5d3-11ea-8ca8-0b7b13e61ac0.png)
but there is a small bug, when I click of reply the reply box not always appear, how can i fix this 
please take a look and click on reply button: https://www.wrdo.org/contact
Thanks

**Comment by CWKevo** [comment]
You can keep only 1 code, you don't need all three. Flarum uses only 1 method to hide the post actions, and I'm pretty sure they just change the `display` to `none`. So try to keep only the code with the `display` property and check if it works. If not, try the other two, one by one.

As for the reply box not being visible, it shouldn't be caused by my code. However, there is a possibility. For now, I'm getting an error when I try to login or sign up from the contact site. Anyways, obviously to find out if it's problem in my code, remove it, reload the page and then see if the issue still persists. If yes, my code breaks it up. If no, problem is elsewhere.

**Comment by ghiathkamel** [comment]
`<style>.Post-actions { opacity: 1.0 !important; }</style>`
only this code works , Thank you very much 
do i need to add any other code ?
Thanks

**Comment by CWKevo** [comment]
No, you don't need to add any other codes.

**Comment by ghiathkamel** [comment]
Issue solved, GOD bless you :)
