### ISSUE TITLE
Moving the reply box to the top of the page

### ISSUE THREAD

**Issue by ghiathkamel** [gwillem/freeflarum.com#132]
![Write a Reply](https://user-images.githubusercontent.com/60829719/89140742-8b363500-d510-11ea-86a4-9ec43a58574d.png)
Hello, can i make the box of Write a Reply not in the bottom but in the top of the page, Thanks

**Comment by CWKevo** [comment]
Probably, with another CSS & HTML editing... However, an extension would be a better idea to style your forum with, unless you want to have tons of code overwrittes in your header. Just a note, there is currently no Flarum setting to control the position of the reply box.

**Comment by ghiathkamel** [comment]
i hope if someone he has time to make this extension
i dont know how to do it with  CSS & HTML editing , i am using google site website builder .
is there a template for the Flarum forum , using CSS & HTML etc,
Thanks

**Comment by CWKevo** [comment]
If you mean templates as in Flarum's source code, then you might be looking for [Flarum's GitHub](https://github.com/flarum).
If you mean templates as in a selecting a theme, then that's possible only by using extensions.

I have always had an idea about extension that can provide the ability to cycle through different styles and CSS tweaks & templates, however I have only worked with language extensions and never really developed a serious extension like this one. I could look into it one day.

For now, you can look at [Flarum's extension documentation](https://docs.flarum.org/extend/#core-vs-extensions) and have someone setup a similar one for you. Or you can try and create it by yourself too. You can also play with CSS in headers a bit, some small tweaks shouldn't make big mess.

**Comment by quitd** [comment]
you can edit Flarum's CSS

**Comment by CWKevo** [comment]
> you can edit Flarum's CSS

Yes, but not directly, at least not at FreeFlarum. They could specify some overwrittes that would move the box to the top, however that probably wouldn't be very responsive along different devices. You could use `translateY()` or similar, such as `position: absolute` and then tweak `top` property, but this is something that is useless when all it takes could be just to program an extension that modifies Flarum template directly by changing the HTML order of the reply box, therefore it's position. You could also directly edit this setting in the source code, however that is currently not possible on FreeFlarum.

My point is that CSS pasted into headers and/or footers are great for small tweaks, but moving the reply box up would be a problem because when there are more posts on the page, you'd have to move it upwards more, whereas if there is a low amount of posts, lower values will need to be specified - and that's something that is unnecessarily tedious to do.

**Comment by CWKevo** [comment]
I just realized that it would be possible with jQuery or JavaScript to copy the HTML of the reply box and insert it before/after some element that is on the top of the page  Not sure if it's gonna work though, but I'll give it a try.

**Comment by ghiathkamel** [comment]
> you can edit Flarum's CSS

Thanks , but how :)

**Comment by ghiathkamel** [comment]
> I just realized that it could be possible with jQuery or JavaScript to copy the HTML of the reply box and insert it before/after some element that is on the top of the page Not sure if it's gonna work though, but I'll give it a try.

please can you explain how, can i do it from my side or its from freeflarum side?
Thanks my friend

**Comment by CWKevo** [comment]
It's from your side. So far, I tried this code but it doesn't work, at least not on mobiles:
```jquery
<script>
$(document).ready(function(){
 $("article.Post.ReplyPlaceholder").insertBefore($("article.CommentPost.Post.Post--by-actor"));
});
</script>
```

**Comment by ghiathkamel** [comment]
Hello , i will add  jQuery script into a custom header of my forum, what this script for , is it only for enable jQuery script in my forum.
do i need to install the script with <script ></script> or without those tags like this code : 
`src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"`

**Comment by ghiathkamel** [comment]
Do i need to install this script in the custom header of my forum or in the embed box of the google site
`<script>
$(document).ready(function(){
 $("article.Post.ReplyPlaceholder").insertBefore($("article.CommentPost.Post.Post--by-actor"));
});
</script>`

**Comment by ghiathkamel** [comment]
i did install the jQuery script into a custom header , like it shown in the photo
![Header2](https://user-images.githubusercontent.com/60829719/89241896-27724180-d5ce-11ea-9645-8d8062b8b8a4.png)

**Comment by CWKevo** [comment]
In the header. All code goes into header or footer (if not, I'd tell you to put it somewhere else).

And the CSS goes elsewhere. If you close the header, there are 2 other options: edit custom footer and edit custom CSS. Paste the CSS (last 3 lines from the header, eg. everything except the jQuery code) in there.

**Comment by CWKevo** [comment]
I haven't come to a solution. You should ask at [Flarum's Discuss](https://discuss.flarum.org), but I believe that it is currently impossible to move the reply box to the top.
