### ISSUE TITLE
About Tags

### ISSUE THREAD

**Issue by ghiathkamel** [gwillem/freeflarum.com#134]
![tags](https://user-images.githubusercontent.com/60829719/89250971-edac3580-d5e3-11ea-880b-fe20e2e7ba7d.png)
Hello everyone,
How can I create large boxes same as this General box ,i like the large size of the General box 
Thanks

**Comment by CWKevo** [comment]
Go to Admin > Extension > Tags and then on "Create new tag". I haven't documented this extension yet, but [this thread](https://discuss.flarum.org/d/22657-how-to-add-tags/2) provides a quick guide on how to use the extension.

**Comment by ghiathkamel** [comment]
Thanks, issue solved
