### ISSUE TITLE
how to put more than four tags on the home page 

### ISSUE THREAD

**Issue by ghiathkamel** [gwillem/freeflarum.com#135]
Hello, How can i remove this more... button, and show all the tags i have in the main page.
Thanks
![tags more](https://user-images.githubusercontent.com/60829719/89251387-e5082f00-d5e4-11ea-8405-570e097f979f.png)

**Comment by CWKevo** [comment]
As far as I know, this isn't currently possible.

**Comment by ghiathkamel** [comment]
issue solved 
Thanks

**Comment by gwillem** [comment]
@ghiatkamel can you stop posting general Flarum questions to this Github?
Use the forum at discuss.flarum.org for that. This github is only for
freeflarum-specific bugs and feature requests.
