### ISSUE TITLE
Confirmation mail doesn't arrive + adding language

### ISSUE THREAD

**Issue by lesteroficail228** [gwillem/freeflarum.com#136]
__Your question:__

Hello, I am sorry for possible mistakes in words. In general, let's move on to the question. User registration works fine, but email confirmation doesn't work. People just don't get a confirmation message. And yet, how can I change the language of the forum to Russian? Only Arabic and others noticed in the expansion

**Comment by CWKevo** [comment]
The E-mail should arrive soon, if it doesn't it is most likely a misconfiguration in your mail settings. On some mail providers, the mail can also arrive in the spam folder, so check that one too.

**Comment by lesteroficail228** [comment]
Thanks for the answer.

**Comment by CWKevo** [comment]
I'll close this, if same problems reappear in the future, please re-open it.
