### ISSUE TITLE
A couple of extension requests

### ISSUE THREAD

**Issue by Somyrion** [gwillem/freeflarum.com#14]
https://discuss.flarum.org/d/18796-friendsofflarum-bbcode-details
https://discuss.flarum.org/d/6207-flagrow-fonts-easily-add-fonts-to-your-forum
https://discuss.flarum.org/d/4981-fontawesome-bbcode-extension
https://discuss.flarum.org/d/7028-flagrow-mason-the-discussion-custom-fields-builder

Thanks!

**Comment by xCustomWorld** [comment]
Hello,

about the details, we already have spoilers in the [BBBBCode](https://github.com/zerosonesfun/bbbbcode) extension as spoilers, so I think we shouldn't have 2 extensions that do the same thing. But if you want the extensions just for details, it is understandable.

The font extensions is a nice idea and I think that if it's compatible with FreeFlarum it's surely very welcoming along other FreeFlarumers.

FontAwesome is a really nice idea too. We'll see.

Mason has been tested by myself on local machine and it works very well, so I think it'll surely be added to the FF as soon as possible.

**Comment by gwillem** [comment]
Mason is being installed. The others, I would like to have a few more people requesting them before I add them.

**Comment by Somyrion** [comment]
Thank you for adding Mason! 

> about the details, we already have spoilers in the [BBBBCode](https://github.com/zerosonesfun/bbbbcode) extension (from the images of the extension you have sent I guess "details" are similar to spoilers from BBBBCode) so I think we shouldn't have 2 extensions that do the same thing. But if you want the extensions just for details with nothing else, it is understandable.

I did try the BBBBCode extension out, but there are a ton of bugs with it that make it near-unusable for spoilers. Essentially, only the first spoiler in a thread actually works, while subsequent spoilers just open up the first one (rendering the content within them unreadable). BBBBCode's spoiler tags also break with multiple paragraphs or any formatting. I've just asked about these problems in the [BBBBCode extension thread](https://discuss.flarum.org/d/18958-big-beautiful-bbcodes/27), so hopefully they'll be fixed soon. 

Additionally, FreeFlarum in beta 7 _did_ have the Details extension installed, so our forum has a bunch of posts which use the `[details=][/details]` syntax already. Re-adding it would mean I wouldn't have to go through and fix all those posts 😛

**Comment by gwillem** [comment]
- fof/bbcode-details added
- zerosonesfun/bbbbcode updated
