### ISSUE TITLE
[hard-limits] Is the 250 users limit on database-side?

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [gwillem/freeflarum.com#142]
I would like to ask if the 250 users hard limit on the database-side or on server-side? If I hit that limit, should I donate some money or should I self-host Flarum elsewhere?

**Comment by CWKevo** [comment]
I'd say both server and database side. While FreeFlarum *may* handle that, more users mean more server & database stress.

While donations are very appreciated and help FF to keep the service running (thank you everyone), if you are looking towards hosting a big forum, self-hosting might be a better idea, as it gives you full control over your resources and performance options. But as for the simplicity, FreeFlarum is in my opinion the best and a great start for beginners and starting communities.

**Comment by gwillem** [comment]
There is no hard limit, but we reserve the right to ask you to migrate your
forum elsewhere, if your forum traffic affects other forums negatively.
There are many freeflarum forums with 500+ users who are no issue at all.

**Comment by AndreiJirohHaliliDev2006** [comment]
Thanks for the answers @gwillem and @CWKevo. I'll close this ticket to free up support resources for other issues.
