### ISSUE TITLE
Fof Secure HTTPS doesn't work

### ISSUE THREAD

**Issue by Puled** [gwillem/freeflarum.com#144]
When FoF Secure HTTPS enabled, pictures won't display correctly, instead, every picture will have `https://flea.flarum.cloud/api/fof/secure-https/` before the actual url.

**Comment by CWKevo** [comment]
I think that's how the extension is supposed to work. It directs traffic of images to `./fof/secure-https/x` and tells them to use HTTPS.

Side note, this GitHub is intended for FreeFlarum related issues only. Questions about the extensions should be directed to their authors, in this case, please ask about your issue [here](https://discuss.flarum.org/d/17771-friendsofflarum-secure-https). We do not maintain any extensions, therefore we sadly cannot assist you with extension-specific issues. Sorry.

**Comment by Puled** [comment]
Ok.
