### ISSUE TITLE
Follow users

### ISSUE THREAD

**Issue by thetechprofessor** [gwillem/freeflarum.com#145]
__Packagist URL for extension:__

[//]: # "https://packagist.com/... (this line is a comment, it won't be visible. Paste the URL under this, or remove this line)"

__Why should we install this extension?__

[//]: # "In short, tell us why we should install this extension and how it would be beneficial towards the community."

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

**Comment by CWKevo** [comment]
Thank you for your request, however it is invalid because it did not follow the template. I have looked Follow Users extension up, and it is even a WIP, meaning that it may be yet unstable and that we cannot install that. Sorry.
