### ISSUE TITLE
Help! I have a forum in your website!(Need help)

### ISSUE THREAD

**Issue by soundarrr** [gwillem/freeflarum.com#148]
I need help in setting up freeflarum.

I want it to be similar to discourse.
{
1.Private Messaging
2.Topics
3.Solution Button
4.Clean and Elegant UI
}

Well I know its impossible to make it look like discourse,but there may be some tricks to do it.

Please Help me!

**Comment by CWKevo** [comment]
1. Use the [FoF Byōbu](https://www.freeflarum.com/docs/how-to/extensions/fof-byobu/) extension;
2. Use the Tags extension, I'm not sure what do you quite mean by that;
3. Could you be more specific? Flarum has a "Best answer" extension, but that is unfortunately not at FreeFlarum at the moment;
4. Trust me, you won't find cleaner and more elegant UI in any of the free forum hosting over internet. You can use CSS to tweak the appearance to your liking too, but that might require some practice.

**Comment by soundarrr** [comment]
Oh I am sorry,when can I expect the Best Answer extension in FreeFlarum?

**Comment by CWKevo** [comment]
Check #98. Might be later, but might be sooner.
