### ISSUE TITLE
Error occurred while trying to load forum

### ISSUE THREAD

**Issue by dmitry106** [gwillem/freeflarum.com#149]
**Describe the bug:**
"An error occurred while trying to load this page. " when trying to load forum page. (admin panel works)

[//]: # "A clear and concise description of what the bug is."

**My FreeFlarum forum URL:**
https://thelastsovereign.flarum.cloud/

[//]: # "For example, https://x.freeflarum.com where 'x' is your forum name."

**To Reproduce:**
Access above link

**Expected behavior:**
Forum loads without error

[//]: # "A clear and concise description of what you expected to happen."

**Comment by CWKevo** [comment]
![image](https://user-images.githubusercontent.com/39010496/93014267-ffec9c80-f5af-11ea-8b3e-dedf74477202.png)
Something went wrong with the Mathren extension. I will try to reinstall it.

**Comment by CWKevo** [comment]
Your forum should be working again, but I had to remove Mather extension. It seems that some other extension caused this issue. I will try to look into it.

**Comment by CWKevo** [comment]
When I updated `illuminate/container` on my test forum, the bug is gone. I guess we will need to update some packages in order to give forums a better stability. After that, the Mathren extension should make a return.

**Comment by dmitry106** [comment]
Thank you for the information and for the fix. It was quite confusing to us since we had not changed any extensions recently when the issue occurred.

**Comment by CWKevo** [comment]
Yes, I understand that it might be confusing. Sorry for the inconvenience, I'll try to add it back... That's the cost of adding more extensions, that some others tend to break...

**Comment by CWKevo** [comment]
Somehow, Mathren is back and working now. You can try to use it, it should work.
