### ISSUE TITLE
Doorman by ReFlar - Add Request

### ISSUE THREAD

**Issue by tatata4822** [gwillem/freeflarum.com#15]
Would absolutely appreciate if [Doorman by ReFlar](https://discuss.flarum.org/d/17845-doorman-by-reflar) could be added.

**Comment by gwillem** [comment]
Being added

**Comment by gwillem** [comment]
Removed, it has a bug that breaks compatibility with certain languages.
https://github.com/FriendsOfFlarum/doorman/issues/18

**Comment by frankzhang05** [comment]
@gwillem Could [this](https://discuss.flarum.org/d/17845/30) be a potential fix?

**Comment by bixgit** [comment]
> @gwillem Could [this](https://discuss.flarum.org/d/17845/30) be a potential fix?

Was just noticing that myself; I'm not clueful enough to know, but I had the same wonder.

**Comment by mortee** [comment]
Apparently, this issue has been fixed, so maybe it can be re-added now?
https://discuss.flarum.org/d/17845-doorman-by-reflar/43

**Comment by mortee** [comment]
> Removed, it has a bug that breaks compatibility with certain languages.

maybe now?

**Comment by adamblock** [comment]
I would also appreciate this being added.

**Comment by gwillem** [comment]
Have reinstalled the latest Doorman, let us know if you encounter any difficulties.

**Comment by adamblock** [comment]
> Have reinstalled the latest Doorman, let us know if you encounter any difficulties.

Thank you!

**Comment by breakthroughsam** [comment]
I see that Doorman is in the list of installed extensions, but I'm unable to find the panel to generate invite codes anywhere in the Admin panel. Am I missing something?

**Comment by CWKevo** [comment]
> I see that Doorman is in the list of installed extensions, but I'm unable to find the panel to generate invite codes anywhere in the Admin panel. Am I missing something?

It works fine on my forum. Did you enable the extension? Try refreshing the page or clearing your browser cache and/or Flarum cache.

**Comment by breakthroughsam** [comment]
I've cleared the Flarum cache and my browser cache, and still can't seem to find it anywhere. The extension shows up as installed in the list (no checkbox to disable it though), and there isn't any kind of settings button to be found. Sorry, brand new to this and still finding my way around.

**Comment by breakthroughsam** [comment]
> > I see that Doorman is in the list of installed extensions, but I'm unable to find the panel to generate invite codes anywhere in the Admin panel. Am I missing something?
> 
> It works fine on my forum. Did you enable the extension? Try refreshing the page or clearing your browser cache and/or Flarum cache.

My apologies - this appears to be an issue with Safari. Everything works fine now that I'm in Chrome. Thanks so much!

**Comment by CWKevo** [comment]
Glad you got it solved!
