### ISSUE TITLE
Korean Language Pack

### ISSUE THREAD

**Issue by Cryental** [gwillem/freeflarum.com#151]
__Packagist URL for extension:__

https://packagist.org/packages/cryental/flarum-l10n-ext-korean

__Why should we install this extension?__

It will add Korean language support to users, which is good for korean users.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

Author: Me
URL for Forum: https://forum.cryental.dev/
Demo: https://devforum.cryental.dev/

**Comment by CWKevo** [comment]
Installed, tested, checked source, works! Thanks for the request, nice forum and extension :)
