### ISSUE TITLE
Flarum Categories bricks out the admin panel when Tags isn't enabled.

### ISSUE THREAD

**Issue by GameGlitz** [gwillem/freeflarum.com#154]
**Describe the bug:**
`
Something went wrong while trying to load the full version of this site. Try hard-refreshing this page to fix the error.
Stack strace:
TypeError: Cannot read property 'prototype' of undefined
    at https://glitzmc.flarum.cloud/assets/admin-dc1e4193.js:128:2830
    at https://glitzmc.flarum.cloud/assets/admin-dc1e4193.js:1:44842
    at Array.forEach ()
    at e.boot (https://glitzmc.flarum.cloud/assets/admin-dc1e4193.js:1:44814)
    at https://glitzmc.flarum.cloud/admin:132:33
That's all that we know... Please, report this bug on our Discuss thread or GitHub
`

**My FreeFlarum forum URL:**

https://glitzmc.flarum.cloud

**To Reproduce:**

Install Flarum Categories and the plugin below it (FORGOT THE NAME)

**Expected behavior:**

I would expect to load the administration control panel, but instead I get this error, seeming to be a corrupt forum install?

**Screenshot(s) (optional):**

[//]: # "If applicable, add screenshot(s) to help explain your problem."
![image](https://user-images.githubusercontent.com/50027352/94100236-fa4f4c00-fe24-11ea-9809-20a38195248d.png)

**Comment by CWKevo** [comment]
Yes, this issue happens a lot with Categories and also Discussion Templates. I'm thinking of removing those extensions from FF entirely, as they cause many issues on many forums. However, many forums want them, but I think that stability is the better option here.

**Comment by GameGlitz** [comment]
Oh, so are there any methods of uninstalling them? My install has a lot of CSS customization and I don't wanna have to redo my whole installation.

**Comment by CWKevo** [comment]
You don't have to reset. I can backup the codes for you if you want.

As for uninstalling, you cannot uninstall the extension, I meant removing the extensions globally, on all forums.

**Comment by GameGlitz** [comment]
> You don't have to reset. I can backup the codes for you if you want.
That would be really nice of you. Also, as of removing them globablly, I would suggest maybe enforcing rules on which extensions can be installed at once so people don't end up getting incompatibilities.

**Comment by CWKevo** [comment]
I was thinking of doing that too, but I'm afraid some people wouldn't notice the rules anyways.

I will disable Categories & Discussion Templates for you (they will appear as enabled, but won't do anything - just disable them).

**Comment by CWKevo** [comment]
Done, your forum should be okay now. Reply if some other errors occur.

**Comment by GameGlitz** [comment]
Started using Tags, and well.. uhm.
![image](https://user-images.githubusercontent.com/50027352/94101498-d7726700-fe27-11ea-8d6a-c55ebd8df82f.png)
Seems to have no language pack. This would've not bothered me if it doesn't also interfere with the main page literally destroying the UX of the page..

**Comment by CWKevo** [comment]
That's common bug with beta.13 and you have to clear your cache. See #123

**Comment by GameGlitz** [comment]
Ah! Thanks for all the support man, for a product funded with only donations I wasn't expecting an instant response that literally fixed all my issues.

**Comment by CWKevo** [comment]
🤷 thank you for the kind words. I try my best :)
Good luck with your community!
