### ISSUE TITLE
Flarum Progressive Web App

### ISSUE THREAD

**Issue by YodaDaCoda** [gwillem/freeflarum.com#155]
__Packagist URL for extension:__

https://packagist.org/packages/askvortsov/flarum-pwa

__Why should we install this extension?__

Provides push notifications, adds some offline support, generally makes flarum feel more native. This may also be a suitable replacement for #55.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

Forum discussion is current and active
https://discuss.flarum.org/d/23219-progressive-web-app-and-push-notifications

**Comment by ririko5834** [comment]
I like this extension. Please add it if it is possible!

**Comment by bluenchanter** [comment]
This should be added

**Comment by CWKevo** [comment]
I don't think that we're going to add any extensions before beta.14. But don't worry, I will keep all requests in mind and we will add them.

**Comment by CWKevo** [comment]
Unfortunately, while I was testing this extension on a test forum, a bug occurred (https://github.com/askvortsov1/flarum-pwa/issues/10 and https://discuss.flarum.org/d/23219-progressive-web-app-and-push-notifications/167).

We will need to give this one a little bit more time due to FreeFlarum's database setup. Either change databases of every FreeFlarum forum (which is crazy), or wait for a fix. I will speak to devs when I get the time, but this cannot be added now. Sorry.

**Comment by CWKevo** [comment]
I will test this again and report any bugs that I find, since this seems to be the only alternative to the "OneSignal" extension at the moment and both requests for that and this got good amount of upvotes, so I want to include this instead.

**Comment by askvortsov1** [comment]
To confirm, the current issue is that the FreeFlarum databases don't support keys longer than 767 bytes, right?

**Comment by CWKevo** [comment]
Yes, but I've heard you say elsewhere that this might be related to the MariaDB version we are using (`10.1.47`). I would like to update, although I'd need to have time to focus on that as updating databases of +3 000 forums is a tough process and something might break

**Comment by askvortsov1** [comment]
Ah, makes sense. Yeah that's a tough one...

**Comment by CWKevo** [comment]
I could technically do it today, since I have the time, but I'll see... But it would definitely help the rest of the requested extensions to join FreeFlarum sooner.

**Comment by CWKevo** [comment]
Added!
