### ISSUE TITLE
Flarum Catagories

### ISSUE THREAD

**Issue by Gideon357** [gwillem/freeflarum.com#156]
__Packagist URL for extension:__ https://packagist.org/packages/askvortsov/flarum-categories

__Why should we install this extension?__ This extension brings a feature common to most forums, such as InVision Community, phpBB, myBB, and XenForo, to Flarum. I think that a lot of people could benefit from this. I would really like this as well.

[//]: # "In short, tell us why we should install this extension and how it would be beneficial towards the community."

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__ https://discuss.flarum.org/d/23184-flarum-categories https://forum.youthneuro.org/

**Comment by CWKevo** [comment]
#104 #154

**Comment by CWKevo** [comment]
The issue I have linked above should be fixed in `beta.14`, so this extension will most likely be added after. Sorry.

**Comment by Gideon357** [comment]
Alright, thank you. When will the beta arrive?

**Comment by CWKevo** [comment]
[Probably soon](https://discuss.flarum.org/d/23667-dev-diary-beta-14/112)

Side note that this update will change Flarum API, so a lot of extensions will have to be updated too... I have no idea how long will it take the extension authors to update their extensions, but hopefully not too long. We will probably have to remove a few extensions that won't be compatible with the update too. I think that FreeFlarum could update after 2 - 3 weeks upon `beta.14` release. Can't tell, sorry.

**Comment by Gideon357** [comment]
So... Flarum will be less useful _after_ the update than before?

**Comment by CWKevo** [comment]
No, I didn't mean that. The API will obviously be enhanced with bug fixes & other features, along with a few other things :)

Flarum is in beta, so it is expected for the API and stuff to change often. It is common everywhere and we can't do much about it, but we will try to update fast.
