### ISSUE TITLE
[Question] Setting up Authy OneTouch

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [gwillem/freeflarum.com#158]
__Your question:__

I've enabled [ReFlar Two Factor](https://discuss.flarum.org/d/11006-twofactor-by-reflar) extension on my forum and I enabled Authy support. How do I setup OneTouch for my forum? I tested if it worked by sending approval/denial from my Authy Desktop app, but it does nothing? What settings should I need to place on my app's (in this case, my forum's) settings in Authy Dashboard?

![image](https://user-images.githubusercontent.com/34998342/95206883-ceb36500-0819-11eb-82c3-0963a519708a.png)

[//]: # "Replace this entire line with your question, or start writing below or above it, preferably below."

**Comment by CWKevo** [comment]
This seems more like a question to be asked at [Discuss](https://discuss.flarum.org/d/11006-twofactor-by-reflar). Keep in mind that this repository is for FreeFlarum questions only. This also unfortunately means that I have no idea how to fix the issue you're facing. Sorry.

**Comment by AndreiJirohHaliliDev2006** [comment]
Okay, my apologies.
