### ISSUE TITLE
Admin Password Email Not Coming

### ISSUE THREAD

**Issue by Nisarga-Developer** [gwillem/freeflarum.com#160]
I am working on a forum with freeflarum but when I signed up I didn't receive any e-mail containing password of admin account.

I have waited for like 11 minutes. 

Do help.

**Comment by Nisarga-Developer** [comment]
My forum link blockcodetime.flarum.cloud

**Comment by CWKevo** [comment]
https://discuss.flarum.org/d/7585-free-flarum-hosting-on-an-expert-platform-by-freeflarum-com/1609

**Comment by Nisarga-Developer** [comment]
So, I didn't found any solution there

**Comment by Nisarga-Developer** [comment]
How do I get the admin password? I have checked my spam box too

**Comment by CWKevo** [comment]
There is no solution, FreeFlarum doesn't send any mails at the moment and I'm looking for a workaround rn

**Comment by CWKevo** [comment]
The mail service should work again now, please try to re-create your forum now.

**Comment by Nisarga-Developer** [comment]
Working!
Thank you so much

**Comment by CWKevo** [comment]
No problem!

**Comment by Nisarga-Developer** [comment]
A little bit prblm here.
I added Ban IP extension
The extensions tab gone missing now.

**Comment by CWKevo** [comment]
Have you installed the "Dashboard" extension too? If yes, all extensions are listed there. If not, try accessing `yourforum.url.com/admin#/extensions`.

**Comment by Nisarga-Developer** [comment]
Okay.

**Comment by Nisarga-Developer** [comment]
How to view users list?

**Comment by CWKevo** [comment]
Use the "User Directory" extension.

Please, be aware that this is not a thread for answering Flarum questions. We are a community ran service that provides hosting for Flarum, and questions about Flarum itself should be asked at https://discuss.flarum.org.

**Comment by Nisarga-Developer** [comment]
There are problems in signing in with google
