### ISSUE TITLE
New user Sign Up not working for abc.flarum.cloud instances

### ISSUE THREAD

**Issue by meetdilip** [gwillem/freeflarum.com#161]
**Describe the bug:**

Not able to create a new user in abc.flarum.cloud forums

**admintech.flarum.cloud**

[//]: # "For example, https://x.freeflarum.com where 'x' is your forum name."

**To Reproduce:**

1. Go to 'https://admintech.flarum.cloud/'
2. Click on 'Signup'
3. Try to register by entering user name, email and password
4. When we click " Sign Up " after completing, there comes a spinner icon and everything stays as such. No signup occurs.

**Expected behavior:**

A new user is supposed to be created after the process with provided details

**Screenshot(s) (optional):**

[//]: # "If applicable, add screenshot(s) to help explain your problem."

**Comment by meetdilip** [comment]
reCAPTCHA issue. Working on it.

**Comment by CWKevo** [comment]
Alright, I thought that it was an issue on FF's side for a second because we did change some stuff earlier, which I'll explain in a moment.

**Comment by meetdilip** [comment]
I thought too because it happened on more than one instance. :(

**Comment by CWKevo** [comment]
The registration works fine on my forum, seems like an error on your side. Good luck fixing it & message me if you need help.

**Comment by meetdilip** [comment]
Thanks a lot for your guidance. I think it got fixed. I will double check and update here if there is anything wrong.
