### ISSUE TITLE
Profile page is blank for some reason? No idea why.

### ISSUE THREAD

**Issue by CvldYT** [gwillem/freeflarum.com#163]
**Profile page is 100% blank, and shows no information**

When I try and click the profile page, instead of seeing my profile, I see a blank screen.

**https://jemix.flarum.cloud/**

**To Reproduce:**

Click on your username
Click profile

**Expected behavior:**

Users SHOULD see their profile page, but instead see a blank screen.

![image](https://user-images.githubusercontent.com/64553004/96965747-835bb080-14c1-11eb-8beb-b4b1628b4a7e.png)

As you can see the screenshot shows a blank screen, instead of a users profile.
https://jemix.flarum.cloud/u/BadimoMC

**Comment by CWKevo** [comment]
In the console, I see an issue with the "Money" extension. Try to disable the extension and then try to access your profile page.

**Comment by CvldYT** [comment]
Testing now! Thanks!

**Comment by CvldYT** [comment]
Worked, thanks!

**Comment by CWKevo** [comment]
I'll look into it later to see what's the real cause, glad you got it solved!
