### ISSUE TITLE
Can I reset my extensions back to what they were when I made flarum?

### ISSUE THREAD

**Issue by CvldYT** [gwillem/freeflarum.com#164]
Same as title! Thnx

**Comment by CWKevo** [comment]
Not you, but we can. This will reset your forum settings back to default. If you want me to reset your forum settings, tell me your Flarum forum please, and some proof that you own it so we don't reset someone else.

**Comment by CvldYT** [comment]
https://jemix.flarum.cloud
![image](https://user-images.githubusercontent.com/64553004/96976670-f6205800-14d0-11eb-9106-7a640e83b49e.png)
![image](https://user-images.githubusercontent.com/64553004/96976768-14865380-14d1-11eb-9ec9-2e8c6e9688e4.png)

Just my extentions please, I screwed stuff up, and users on mobile get errors:
Error 500: Type Error Argument 1

(Try and post on my forum)

So Idk if resetting is the best option.

**Comment by CWKevo** [comment]
Your Perspective extension is the issue. Have you specified the API key?

**Comment by CvldYT** [comment]
oops no.

**Comment by CWKevo** [comment]
You have to specify the API key, then it'll work. If you don't have one or you can't obtain it, then simply disable the extension and it should work again.
