### ISSUE TITLE
FreeFlarum beta.14 Update

### ISSUE THREAD

**Issue by CWKevo** [gwillem/freeflarum.com#166]
Since beta.14 and beta.14.1 have been out for quite some time now, I have decided to make a to-do list of things that we need to do before the update:

- [x] Verify that extensions are beta.14 compatible (checked against Extiverse.com and Discuss for possible ETAs):
  - **Note:** Language extensions are all compatible, except for Dutch which broke the Linguist extension, so that's gonna be removed.
  - [x] ~~amaurycarrade/flarum-ext-syndication~~ - Seems dead, will be re-added when it updates.
  - [x] antoinefr/flarum-ext-money
  - [x] askvortsov/flarum-moderator-warnings
  - [x] ~~bertaveira/flarum-pt-pt~~ - tiu-ram0n/brazilian-portuguese is updated
  - [x] ~~cbmainz/flarum-de~~ - kakifrucht/flarum-de and kakifrucht/flarum-de-extended is updated
  - [x] clarkwinkelmann/flarum-ext-author-change
  - [x] clarkwinkelmann/flarum-ext-create-user-modal
  - [x] clarkwinkelmann/flarum-ext-emojionearea
  - [x] cryental/flarum-l10n-ext-korean - isn't beta.14, but works
  - [x] ~~csineneo/lang-simplified-chinese~~ - littlegolden/flarum-lang-simplified-chinese is updated
  - [x] ~~csineneo/lang-traditional-chinese~~ replaced by littlegolden/flarum-lang-simplified-chinese - they aren't really different, plus the one by LittleGolden is constantly being updates, so it always works and is stable
  - [x] customworld/flarum-lang-slovak           - Maintained by me, no ETA - will be updated when I have time & passion to do so. Plus, it's low priority - not many users use Slovak on FF, for now it just works
  - [x] darkfoxdeveloper/flarum-ext-spanish
  - [x] datitisev/flarum-ext-dashboard
  - [x] ~~dem13n/nickname-changer~~ - not compatible, beta.15 should bring official nickname extension.
  - [x] flarum/approval
  - [x] flarum/auth-facebook \
  - [x] flarum/auth-github      Will be replaced by flarum/oauth
  - [x] flarum/auth-twitter     /
  - [x] flarum/bbcode
  - [x] flarum/core
  - [x] flarum/embed
  - [x] flarum/emoji
  - [x] flarum/flags
  - [x] flarum/lang-english
  - [x] flarum/likes
  - [x] flarum/lock
  - [x] flarum/markdown
  - [x] flarum/mentions
  - [x] flarum/pusher
  - [x] flarum/statistics
  - [x] flarum/sticky
  - [x] flarum/subscriptions
  - [x] flarum/suspend
  - [x] flarum/tags
  - [x] fof/analytics
  - [x] fof/auth-discord                         - Will be replaced by flarum/oauth
  - [x] fof/ban-ips
  - [x] fof/bbcode-details                      - Not picked by Extiverse, but according to Discuss, it just works
  - [x] fof/best-answer
  - [x] fof/byobu
  - [x] fof/default-group
  - [x] fof/default-user-preferences - seems to just work
  - [x] fof/drafts
  - [x] fof/filter
  - [x] fof/formatting
  - [x] fof/forum-statistics-widget
  - [x] fof/gamification
  - [x] fof/linguist
  - [x] fof/links
  - [x] fof/mason
  - [x] fof/masquerade
  - [x] fof/merge-discussions
  - [x] fof/nightmode
  - [x] fof/pages
  - [x] fof/passport
  - [x] fof/polls
  - [x] fof/pretty-mail
  - [x] fof/prevent-necrobumping
  - [x] fof/profile-image-crop
  - [x] fof/reactions
  - [x] fof/recaptcha
  - [x] fof/secure-https
  - [x] fof/share-social
  - [x] fof/sitemap
  - [x] fof/socialprofile
  - [x] fof/spamblock
  - [x] fof/split
  - [x] fof/stopforumspam
  - [x] fof/terms
  - [x] fof/transliterator
  - [x] fof/user-bio
  - [x] fof/user-directory
  - [x] **jordanjay29/flarum-ext-summaries** - will be updated when it updates
  - [x] jslirola/flarum-ext-login2seeplus
  - [x] littlegolden/flarum-lang-japanese
  - [x] ~~luatdolphin/lang-vietnamese~~              - Duplicate** - luuhai48/flarum-tieng-viet is beta.14
  - [x] ~~madchatthew/themelightshadow~~ - removed - it's not updated, and so it is just ugly now
  - [x] madnest/flarum-lang-czech - I know Czech, so I could PR, but since I am busy with other stuff and not much users at FF are Czech, it's not that big priority - Isn't beta.14, but works
  - [x] manaszon/flarum-ext-hungarian - Isn't beta.14, but works
  - [x] marketplace/flarum-l10n-core-russian - Isn't beta.14, but works
  - [x] marketplace/flarum-l10n-ext-russian - Isn't beta.14, but works
  - [x] ~~matteocontrini/flarum-imgur-upload~~ ->  fof/upload, probably keep it for a while for people to be able to migrate Client ID, or just keep it, dunno
  - [x] menomenta/flarum-ext-norwegian - Isn't beta.14, but works
  - [x] michaelbelgium/flarum-discussion-views
  - [x] michaelbelgium/flarum-dutch - breaks FoF Linguist, wasn't updated in a year or so
  - [x] migratetoflarum/canonical
  - [x] nearata/lang-italian
  - [x] neercsys/flarum-ext-bosanski
  - [x] neercsys/flarum-lang-bosanski
  - [x] ~~njkhanh/lang-vietnamese~~                  - **Duplicate - luuhai48/flarum-tieng-viet is beta.14
  - [x] nomiscz/flarum-ext-auth-steam
  - [x] persianfla/flarum-ext-persian
  - [x] qiaeru/lang-french
  - [x] realodix/flarum-ext-indonesian
  - [x] **reflar/cookie-consent** - will be removed until it updates
  - [x] ~~reflar/doorman~~ - replaced by fof/doorman
  - [x] **reflar/twofactor** - will be removed until it updates
  - [x] **reflar/webhooks** - will be removed until it updates
  - [x] rikusen0335/lang-japanese-extended
  - [x] rob006/flarum-lang-polish
  - [x] **saleksin/flarum-auth-google** - Note from dev: "This may be the last release, as there is new fof/oauth extension, and there is already PR with Google support. The only problem is that in both my and fof extension Sign in button branding is wrong, and it will be hard to fix. But I hope it will eventually." - there indeed is, and so fof/oauth will be updated when the support is added - plus, for now the fof/oauth routes conflict with other auth extensions, see [this issue](/FriendsOfFlarum/oauth/issues/9)
  - [x] sycho/flarum-profile-cover
  - [x] the-turk/flarum-extended-appearance - will be absent until it updates
  - [x] the-turk/flarum-mathren - will be absent until it updates
  - [x] the-turk/flarum-welcome-widgets - will be absent until it updates
  - [x] tiu-ram0n/brazilian-portuguese - works
  - [x] tolgaaaltas/flarum-ext-turkish
  - [x] tolgaaaltas/flarum-lang-turkish
  - [x] v17development/flarum-seo - it isn't beta.14, but it just works with minimal bugs
  - [x] ~~veriael/flarum-polish~~ (?) duplicate of rob006/flarum-lang-polish
- [x] beta.14 update:
  - [x] Backups - Done automatically
  - [x] We're on beta.13
  - [x] Test things on a test forum
  - [x] If needed, update scripts (such as extension names, in case they have changed)
  - [x] **The update itself** - so far, we've only tested everything on a test forum - works well, updated the issue with info we've got from that.
- [x] Additional features:
  - [x] [fof/upload extension](https://discuss.flarum.org/d/4154-friendsofflarum-upload-the-intelligent-file-attachment-extension/1177)
- [x] If possible, use `extend.php` to add footer codes & tips
- [x] Bring back old extensions
  - [x] Categories
  - [x] Discussion Templates - PRd to fix flarum/tags missing dependency, using dev-master until it updates.
- [x]
  - [x] Add additional requested extensions that are compatible

**Notes:**
- Language extensions will probably not be updated so soon and shouldn't break anything. Translations will be missing, however.
- No need to hurry, a lot of other forums are not beta.14 yet, along with many extensions.

**Comment by gwillem** [comment]
I propose to upgrade when 2/3 of extensions are compatible. The rest, we can install later (if compat versions become available).

**Comment by ririko5834** [comment]
When Freeflarum will update forums to new version?

**Comment by CWKevo** [comment]
When 2/3 of extensions are compatible. The rest will be installed eventually later, when they become compatible.

We have no idea when will extensions update. Last extension breaking update was beta.8, and it took about 6 weeks for the majority of the extensions to update, so I'd give it about a month from now on.

**Comment by CWKevo** [comment]
The update is looking good so far, we've tested stuff on test forums and the results look promising. Some extensions didn't make it (see first post), but language extensions work (thankfully) - non-translated strings fall back to English ones. Looks like it's time to update soon, I just need to do one final test :)

**Comment by Cryental** [comment]
cryental/flarum-l10n-ext-korean updated for beta 14, please check :D

**Comment by CWKevo** [comment]
> cryental/flarum-l10n-ext-korean updated for beta 14, please check :D
> 
> https://packagist.org/packages/cryental/flarum-l10n-ext-korean
> https://github.com/Cryental/flarum-l10n-ext-korean/releases/tag/1.1
> 
> Let me know if I miss any translations!

Almost forgot about this one, I'll add it later, thanks!
