### ISSUE TITLE
Extension request - flarum-categories

### ISSUE THREAD

**Issue by ririko5834** [gwillem/freeflarum.com#167]
__Packagist URL for extension:__

https://packagist.org/packages/askvortsov/flarum-categories

__Why should we install this extension?__

Forum looks better with this. I think that a lot of people could benefit from this. I would like to have this.

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

https://discuss.flarum.org/d/23184-flarum-categories

**Comment by CWKevo** [comment]
#97, #154

This will be re-added when we update to beta.14

**Comment by ririko5834** [comment]
OK
