### ISSUE TITLE
Tag Plug-in not working

### ISSUE THREAD

**Issue by SwiftPoint334** [gwillem/freeflarum.com#168]
**Describe the bug:**

[//]: # When using the tags plugin, the titles are all messed up.

**My FreeFlarum forum URL:**

[//]: # http://scpf.flarum.cloud

**To Reproduce:**
1. Make a Forum
2. Enable the Tags plugin
3. Attempt to edit it

**Expected behavior:**

[//]: # The titles should be normal.

**Screenshot(s) (optional):**
![image](https://user-images.githubusercontent.com/26695878/99671771-e3099500-2a48-11eb-873a-530a7d8b7242.png)

**Comment by CWKevo** [comment]
#123, #138, #109, #112 

Clear your cache.
