### ISSUE TITLE
[Question] Allow topics to be closed after X days of inactivity

### ISSUE THREAD

**Issue by SirEpiclyAmazing** [gwillem/freeflarum.com#170]
Can you please make an extension to allow topics to be closed after a user settable number of days with no replys

**Comment by CWKevo** [comment]
That would require an extension, and we do not develop them. You could ask at https://discuss.flarum.org, but the [FoF Prevent Necrobumping](https://discuss.flarum.org/d/18312) extension is currently the closest to the feature you'd like to have.

**Comment by CWKevo** [comment]
I am closing this since we do not make extensions on request. Please, request it at Flarum's Discuss.
