### ISSUE TITLE
Logo suggestions

### ISSUE THREAD

**Issue by meetdilip** [gwillem/freeflarum.com#171]
I have made 2 variants. Let me know what you think about them

![Free Flarum  use this](https://user-images.githubusercontent.com/6965443/101453278-1d35ca80-3955-11eb-9aad-19745dfc292a.png)

**Comment by meetdilip** [comment]
![Free Flarum  16a](https://user-images.githubusercontent.com/6965443/101453327-2f176d80-3955-11eb-97e1-6046d456e7e1.png)

**Comment by CWKevo** [comment]
Great job! I really like them, especially the first one. Maybe center the text there and make it bigger to be easier to read.

**Comment by meetdilip** [comment]
First one is inspired by your mascot design. Credits to you :) 

>Maybe center the text there 

It is a _fit_ there. I am not sure there is space to realign them

> make it bigger to be easier to read.

I can do that :)

**Comment by meetdilip** [comment]
This one has centering ( I didn't think of vertical centering ) and bigger text. I hope you will like it

![Free Flarum  use this 2](https://user-images.githubusercontent.com/6965443/101454331-cf21c680-3956-11eb-8976-f6ba8ff447a3.png)

**Comment by CWKevo** [comment]
Yes, I certainly do like it! It looks very cool :)

**Comment by meetdilip** [comment]
Thanks :)

**Comment by meetdilip** [comment]
Source SVG

[Final Free Flarum.zip](https://github.com/gwillem/freeflarum.com/files/5657628/Final.Free.Flarum.zip)

**Comment by gwillem** [comment]
Very cool Dilip! Could you, as experiment, make one variation with a
similar font to the official Flarum logo?
[image: image.png]

**Comment by meetdilip** [comment]
Something like this ?

/



![Free Flarum Text 2x](https://user-images.githubusercontent.com/6965443/101474387-1b7a0000-3971-11eb-83a3-901db09a1dc0.png)

**Comment by meetdilip** [comment]
Perhaps this ?

![Free Flarum Text + mascot](https://user-images.githubusercontent.com/6965443/101476130-4d8c6180-3973-11eb-8c59-dd74a26bdb58.png)

**Comment by gwillem** [comment]
Ik like the latter most! Simple 2 color scheme. But perhaps a bit fatter
font?

**Comment by meetdilip** [comment]
Sure. This one ?

![fat](https://user-images.githubusercontent.com/6965443/101490175-0066ba80-3988-11eb-9f1b-38e6390b6e7e.png)

Any idea which font Flarum logo is using ?

**Comment by meetdilip** [comment]
I worked on the base font, had to redo the font. Let me what you think about this

![fat final banner](https://user-images.githubusercontent.com/6965443/101492377-d8c52180-398a-11eb-82f4-31a4c20601cf.png)

**Comment by meetdilip** [comment]
Better position of logo

![fat final banner 2](https://user-images.githubusercontent.com/6965443/101492700-14f88200-398b-11eb-87b1-63342bf40b1d.png)

**Comment by meetdilip** [comment]
I got lucky with this one. This as perfectly fat the font can become

![free flarum bold](https://user-images.githubusercontent.com/6965443/101493263-dca57380-398b-11eb-9060-7e14b815183f.png)

**Comment by gwillem** [comment]
Thanks, looks much better! Can you condense it some more in terms of
whitespace? Ideally it should look nice when you scale it to 160px:
[image: image.png]
Maybe drop the .com (everything has a.com nowadays anyway) and shrink the
icon a bit vertically?

**Comment by meetdilip** [comment]
Do you like this one ? I tried to make the mascot small. But can't make it smaller, will look bad

![72h](https://user-images.githubusercontent.com/6965443/101495188-44f55480-398e-11eb-855d-e3c0695dbc34.png)

**Comment by gwillem** [comment]
Kevo what say you?

**Comment by CWKevo** [comment]
I think that all of them look very nice, so it is hard to decide for me, but I'd go with the last one. It is simple, yet elegant. Maybe center the font or make it bigger to match with the symbol, then it'll be perfect IMO

**Comment by meetdilip** [comment]
Thanks. Making font size = mascot is in effect making the mascot small. The vertical centering is the only one we can try right now. 

Do let me know if you feel like changing anything.

![final](https://user-images.githubusercontent.com/6965443/101501921-55a9c880-3996-11eb-9f09-853a6730bbe9.png)

**Comment by CWKevo** [comment]
It looks amazing now, great job! I think that we can use the last one

**Comment by gwillem** [comment]
Agree! Great job.

**Comment by meetdilip** [comment]
Thanks. SVG attached

[final source.zip](https://github.com/gwillem/freeflarum.com/files/5660180/final.source.zip)

**Comment by CWKevo** [comment]
Also it might be worth noting that SVG fonts become default ones in the browser (eg. we'd need to import them, etc...). I'd like to use SVG because it has higher resolution, but due to this, we might just use PNG image instead of SVG, which looks like this in the browser (at least in Chrome):

![image](https://user-images.githubusercontent.com/39010496/101504396-76145b80-3973-11eb-9214-84ba78962a3a.png)

**Comment by meetdilip** [comment]
No worries. Try this one

[result.zip](https://github.com/gwillem/freeflarum.com/files/5660243/result.zip)

**Comment by CWKevo** [comment]
Perfection.

**Comment by meetdilip** [comment]
:bow

**Comment by meetdilip** [comment]
I like what we have now. But I was trying different things and made these. It resembles steps going up / growth / ascending

Just a basic concept. But if you think it is worth considering, we can try variants

![logo progress](https://user-images.githubusercontent.com/6965443/104095191-72019380-52bb-11eb-9761-84654399060a.png)

**Comment by meetdilip** [comment]
![logo progress 2](https://user-images.githubusercontent.com/6965443/104095189-70d06680-52bb-11eb-9f93-c63a2f8a9c2f.png)

**Comment by CWKevo** [comment]
Very cool, thank you very much for your efforts and hard work!

As for me, I like both, but I don't like the blocky ones that much. The gimmick of resembling steps is really nice though, seems to mean that FreeFlarum is growing? But the smooth versions just seem more modern to me

**Comment by meetdilip** [comment]
Sure. I thought something simple would be a better candidate for a logo.  Perhaps I should try the pixelated version for fun :)

**Comment by CWKevo** [comment]
Very minimal and cute :)

April Fools logo? 😅
