### ISSUE TITLE
Hope to add the following extensions

### ISSUE THREAD

**Issue by autocard** [gwillem/freeflarum.com#173]
Increase user adhesion：
1、ReFlar Level Ranks
2、Login 2 See
3、Reply 2 See

**Comment by CWKevo** [comment]
1. You didn't follow the extension request template.
2. ReFlar Level Ranks is not beta.14 yet.
3. [Login2SeePlus](https://github.com/jslirola/flarum-ext-login2seeplus) is already installed at FreeFlarum.
