### ISSUE TITLE
Shout

### ISSUE THREAD

**Issue by shawny43** [gwillem/freeflarum.com#174]
__Packagist URL for extension:__
https://packagist.org/packages/kyrne/shout

[//]: # "Replace this line with the packagist URL, such as https://packagist.com/..."

__Why should we install this extension?__
For chatting and support. That can replace private disscutions.

[//]: # "In short, tell us why we should install this extension and how it would be beneficial towards the community." An PHPBB like experience but with a touch of Flarum. You can private messaging without problem. An messenger like.

[//]: # "We honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote."

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

**Comment by CWKevo** [comment]
#114 #152
