### ISSUE TITLE
Update Vietnamese language

### ISSUE THREAD

**Issue by luatdolphin** [gwillem/freeflarum.com#175]
composer require luatdolphin/lang-vietnamese

__Packagist URL for extension:__
https://packagist.org/packages/luatdolphin/lang-vietnamese

I don't know why my Extension about Vietnamese language is removed. It made my forum is broken. I updated language package to lastest version. Can you reinstall this package again, please? Thanks!
My forum:
https://www.thiennhaimobi.ga/

!!!!!!!Broken

**Comment by CWKevo** [comment]
Fixed, not sure why it was removed. Your forum should be all good now. Sorry.
