### ISSUE TITLE
Fof draft scheduler

### ISSUE THREAD

**Issue by ItsMrReals** [gwillem/freeflarum.com#177]
__Packagist URL for extension:__

https://packagist.org/packages/fof/drafts

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

https://discuss.flarum.org/d/20957-friendsofflarum-drafts/181

_This request needs at least 7 upvotes to be accepted._

**Comment by CWKevo** [comment]
Already installed?
