### ISSUE TITLE
freeflarum not iframe compatible

### ISSUE THREAD

**Issue by rezl** [gwillem/freeflarum.com#178]
I'm looking to use Feeflarum for an [educational course](https://newamericanfarmstead.thinkific.com/) through [Thinkific](https://www.thinkific.com/). Unfortunately, the header settings on Freeflarum are not allowing it to be emdedded as an iframe. I'm not using any extensions, nor have I made any changes to the forum.

One the Thinkific side, trying to link to the site generates [this generic error](https://i.imgur.com/ngzHZ3C.png).

I checked the FreeFlarum site headers with [an iframe checker](https://www.tinywebgallery.com/blog/advanced-iframe/free-iframe-checker) and get this error:

```
Header X-Frame-Options found.
The header ist set to ALLOW-FROM *. 
This means the page most likely cannot be included into an iframe because the ALLOW-FROM header is not supported by all major browsers.
```

If I'm reading this correctly, the * is supposed to indicate it's allowing all domains, but looking at [the standard syntax options for X-Frames](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) I'm led to believe this isn't how it is supposed to be used and should instead be deleted. 

I suspect any instance of the ALLOW-FROM line is triggering the Thinkific system to think the domain cannot be put in an iframe (even if I know it can be elsewhere). I need to know definitively if this is a valid use of the ALLOW-FROM syntax so I can point the finger at Thinkific to fix, versus FreeFlarum's header settings.

Could anyone please advise?

**Comment by CWKevo** [comment]
I have put the iFrame headers, mainly for the higher rank on online site checker tools (so with a good intention). I was testing on Chrome, and since the webpages were mostly talking about the same stuff, I assumed that using iFrame `ALLOW-FROM` is supported by all modern browsers. But because this doesn't seem to be true, I will remove that (and some other unnecessary headers) today.

**Comment by rezl** [comment]
Wonderful! Thank you, looking forward to this change and using Free Flarum for our course.

**Comment by CWKevo** [comment]
I've removed the headers (thanks for reminding me 😅), could you try if it works now?

**Comment by rezl** [comment]
It works! You're amazing, thank you so much.

**Comment by CWKevo** [comment]
You're welcome, if you need more help with that, just reply
