### ISSUE TITLE
Bazaar

### ISSUE THREAD

**Issue by gwillem** [gwillem/freeflarum.com#18]
~~Flagrow/Upload is incompatible with FreeFlarum so will not be installed. It allows custom uploads which would compromise the stability of other forums on the FreeFlarum platform.~~

fof/upload is now added in beta.14.1

**Comment by xCustomWorld** [comment]
Same for Bazaar. Users could install extensions that run custom PHP code - spam, phishing, hacking and other similar activities would follow. 

Your security is FF's priority. It is always better to request an extension for a review than causing chaos along other FreeFlarum forums :)

**Comment by xCustomWorld** [comment]
**Note:** Simple ext

**Comment by xCustomWorld** [comment]
~~y misclicks tho :(~~

**Comment by luceos** [comment]
@gwillem @CWKevo fof/upload is being made compatible with beta 14 and will offer the ability to disable drivers.

ref https://github.com/FriendsOfFlarum/upload/pull/242

**Comment by gwillem** [comment]
Ref https://discuss.flarum.org/d/4154-friendsofflarum-upload-the-intelligent-file-attachment-extension/1178

**Comment by Erikuitwijdewormer** [comment]
@gwillem This upload option will allow us to use storage in a cloud environment (like for example google drive) for attachments and pictures. I would be a great asset in collaboration between our member in sharing data. Hope it will be possible to implement in next version. I would be interested to know your thoughts on this opportunity.  Regards, Erik Kramer

**Comment by CWKevo** [comment]
fof/upload made it to beta.14.1 👍
