### ISSUE TITLE
Google AdSense - willing to pay.

### ISSUE THREAD

**Issue by greatjack1** [gwillem/freeflarum.com#183]
Hi there,

I would like to have the ability to add google AdSense auto ads to a free flarum forum.

I am willing to donate / pay monthly for this ability.

It is as simple as adding a script to the header since I would want use Auto Ads.

Can we get this going?

**Comment by gwillem** [comment]
Sorry to say that we do not accept advertisements or periodical payments. We are not a commercial entity and do not want to become one. 

If you are looking to monetize your forum, perhaps it would be best to move it to your own server? You can use the FreeFlarum control panel to download all of your data.
