### ISSUE TITLE
Where is the BBBBcode

### ISSUE THREAD

**Issue by BlueWhaleYT** [gwillem/freeflarum.com#184]
I am sorry about not following the template.
I recall that there was an extension which is called BBBBcode in FreeFlarum. It provided lots of extended function. However, where is it at present?
Thanks.

**Comment by CWKevo** [comment]
Gone. It has been abandoned by its author and it is no longer maintained or compatible with the latest Flarum release (https://discuss.flarum.org/d/18958-big-beautiful-bbcodes). Should there be an alternative, do let us know and we will look at implementing it.
