### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by meetdilip** [gwillem/freeflarum.com#185]
Like it ?

![Free Flarum 800](https://user-images.githubusercontent.com/6965443/104152524-d6c90500-5405-11eb-8569-9f4f49d8c664.gif)

**Comment by meetdilip** [comment]
![My Forum 1000 a](https://user-images.githubusercontent.com/6965443/104154123-1eea2680-540a-11eb-8271-2ddd6967241c.gif)

**Comment by CWKevo** [comment]
Very simple IMO, there could be more animations. Doesn't look bad though

**Comment by meetdilip** [comment]
Yes, I kept it as simple as possible. I can add more effects if you choose one :) 

You can share sample banners if you like.

**Comment by CWKevo** [comment]
They're nice, didn't really notice the last reply (I don't have sample banners). I'd suggest more transitions and effects for the future. I'm gonna close this for now as it seems stale
