### ISSUE TITLE
Discussion Language by FriendsOfFlarum

### ISSUE THREAD

**Issue by T0MMYRR** [gwillem/freeflarum.com#186]
I think it is a very useful extension for users to know the language of each discussion, avoiding going in and out to check the language.

__Packagist URL for extension:__
https://packagist.org/packages/fof/discussion-language

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...)__: https://discuss.flarum.org/d/23702-friendsofflarum-discussion-language

**Comment by CWKevo** [comment]
I already saw it, it looks nice. When your request has some upvotes, we'll add it

**Comment by legotom** [comment]
I am not sure but this extension is the one that allows you to do what happens on this website (https://community.upc.ch/blog)? 

Changing the language of the site changes the language of the blog posts and forum discussions, this is achieved with this extension by making duplicates of the articles and discussions in each language? If so it is amazing to be able to do native translations!

**Comment by CWKevo** [comment]
To my knowledge all this does is that it lets you specify in what language a discussion is written, and lets you sort by language.

Tried to install it at the beta forum, didn't work because of an issue. I'll look into it later.

**Comment by legotom** [comment]
> To my knowledge all this does is that it lets you specify in what language a discussion is written, and lets you sort by language.
> 
> Tried to install it at the beta forum, didn't work because of an issue. I'll look into it later.

Yes, that's what I've read on the extension's page, the truth is that I'm curious how they managed to do that, maybe it's an extension that they created themselves...

**Comment by CWKevo** [comment]
Yes, likely

**Comment by CWKevo** [comment]
Added now!

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)
