### ISSUE TITLE
Flarum realtime chat

### ISSUE THREAD

**Issue by geshii** [gwillem/freeflarum.com#187]
__GitHub :__
https://github.com/Xelson/flarum-ext-chat

__Why should we add this :__
Because it's really useful to have a real time chat for our users :p

**Comment by CWKevo** [comment]
That one seems still in beta. I've saw that one and I have plans to include it when it becomes stable. Until then, this can get some upvotes.

Meanwhile, I am going to do some tests on our beta forum to see how well it works and whether we can include it sooner or not.

**Comment by CWKevo** [comment]
The beta.15 extension won't load on the beta forum, I will look into it more and report bugs to their authors.

**Comment by bluenchanter** [comment]
wow. it's a really impressive plugin. I hope their problems are resolved. Like blog and gif this is also added.

**Comment by CWKevo** [comment]
I didn't have time to debug it further, I'll do it now and hopefully include it later.

**Comment by Profi420** [comment]
ist it xmpp or what protocoll?

**Comment by CWKevo** [comment]
> ist it xmpp or what protocoll?

You should ask the devs about this?

**Comment by geshii** [comment]
> 
> 
> I didn't have time to debug it further, I'll do it now and hopefully include it later. It is available at our beta forum, it just doesn't quite work (yet).
> 
> **Edit:** I reported 1 issue, but this will not be included in the near future because it is still not stable enough.

What's the link of the beta forum?

**Comment by CWKevo** [comment]
https://beta.flarum.cloud, but I'm not sure if it's installed right now. I might wait for beta.16, then include it. I think that stable should be ready soon

**Comment by CWKevo** [comment]
I've installed it at the beta forum, doesn't seem to have any breaking issues, just some visual inconsistencies in comparsion to Flarum. The extension is still beta, I'd like to include it when it becomes stable.

You can watch the progress there: https://discuss.flarum.org/d/5133

**Comment by CWKevo** [comment]
Added! I'll make some PRs to fix some visual glitches, but it seems to work so far. Nice extension
