### ISSUE TITLE
Error booting Flarum: Return value...

### ISSUE THREAD

**Issue by xCustomWorld** [gwillem/freeflarum.com#19]
**Describe the bug**
The forum is blank and just shows me `Error booting Flarum: Return value of Flarum\Extension\Extension::getExtenderFile() must be of the type string or null, none returned` error.

**What is your FreeFlarum host name**
customworld.freeflarum.com

**To Reproduce**
1. Go to `Administration`
2. Click on `Extensions`
3. Scroll down to 'Canonical Url`
4. Enable the extension
5. The "Oops! Something went wrong. Refresh the page." error shows.
6. Refresh the page
7. The error above is shown

**Expected behavior**
The extension is enabled with no errors and works.

**Screenshots**
_null_

I know that this error was mentioned somewhere as error when installing new extension and it will resolve automatically within 30 minutes. I waited for one and half hour, the error is still herr.

**Comment by xCustomWorld** [comment]
Possible solution might be to test the extensions at some test forum before actually releasing them. Most of the bugs are literally caused by extension.

**Comment by gwillem** [comment]
It may have to do something with the canonical url extension. However, for all new forums it is automatically enabled by default, so shouldn't be a problem.

> Most of the bugs are literally caused by extension.

Yep, so that's the most work. And also the reason that I don't want to add unlimited extensions ;) 
Testing on a separate forum is quite a lot of work though...

**Comment by xCustomWorld** [comment]
Well, whenever I can, I could review extension on localhost with extensions like FreeFlarum. It is easier to browse the logs here and find the bug then. Unfortunately, I'm not able to do that at anytime, as I move around the world a bit ;)
