### ISSUE TITLE
Trust Levels (Automatic Group Assignment)

### ISSUE THREAD

**Issue by widyp** [gwillem/freeflarum.com#190]
__Packagist URL for extension:__
https://packagist.org/packages/askvortsov/flarum-trust-levels

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
updated a day ago

**Comment by CWKevo** [comment]
I've tested this extension on the beta forum and it seems to work, doesn't have any extension dependencies, so I've decided to add it.
