### ISSUE TITLE
Ghost blog integration in comments

### ISSUE THREAD

**Issue by throwawaycar** [gwillem/freeflarum.com#192]
Request integration with Ghost blogging platform. Each blog post should become a topic in the Flarum. And people should be able to post comments (embedded below the post) and also directly by navigating to Flarum. Discourse, Talkyards etc already have extension for Ghost but I don't see one for Flarum.

**Comment by CWKevo** [comment]
Please, request features here: https://discuss.flarum.org/t/features
We are a community provided service and we're not associated with Flarum. We do not develop extensions either, feature requests here are requests to add an already existing extensions, so if it exists, please follow the template and request it.
