### ISSUE TITLE
 disposable-emails

### ISSUE THREAD

**Issue by Hattie122** [gwillem/freeflarum.com#194]
---
name: 'disposable-emails'
about: 'A Flarum extension. Prevent users from signing up with disposable emails.'
title: 'Disposable Emails by FriendsOfFlarum'
labels: '🙋 Extension/feature request'

---

Packagist URL for extension: https://packagist.org/packages/fof/disposable-emails

Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...): https://discuss.flarum.org/d/20457-friendsofflarum-disposable-emails/19

**Comment by CWKevo** [comment]
Added now, it is rather just a simple & minimalistic drop-in protection, so I included it as it shouldn't break anything and hasn't much dependencies.
