### ISSUE TITLE
Flarum Mason Extension

### ISSUE THREAD

**Issue by ParlorPink** [gwillem/freeflarum.com#196]
Packagist URL for extension:
https://packagist.org/packages/fof/mason

Proof that extension works on the latest Flarum version (beta 15):
https://bookclubforgrads.com/d/15-bsm-for-millennials-by-riccardo-rattazzi

**Comment by meetdilip** [comment]
Free Flarum will upgrade to Beta 16 soon. Please check the addon compatibility with Beta 16.

**Comment by meetdilip** [comment]
Update : Not compatible with Beta 16.

**Comment by CWKevo** [comment]
Not compatible with beta.16, but added anyways (it might work, but let's try it just to be sure)

**Comment by CWKevo** [comment]
Edit: no, it didn't work. Reopening this then

**Comment by CWKevo** [comment]
Compatible with 1.0.4, so I included it

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)
