### ISSUE TITLE
Rich Text

### ISSUE THREAD

**Issue by SafEight** [gwillem/freeflarum.com#199]
__Packagist URL for extension:__
https://packagist.org/packages/askvortsov/flarum-rich-text

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://extiverse.com/extension/askvortsov/flarum-rich-text

**Comment by CWKevo** [comment]
This will be added for sure, as it is highly requested across Discuss

**Comment by CWKevo** [comment]
Added, due to high demand across Discuss
