### ISSUE TITLE
Arabic Language Pack For flarum beta 8

### ISSUE THREAD

**Issue by ziymed** [gwillem/freeflarum.com#2]
Here is the Arabic language pack 
Github : https://github.com/ziymed/lang-arabic
Packgist : https://packagist.org/packages/ziymed/lang-arabic

**Comment by gwillem** [comment]
Thank you, installed

**Comment by ziymed** [comment]
can You please try to update it,, now its beta9.
thank you

**Comment by xCustomWorld** [comment]
Be patient, we have personal life too ;)
