### ISSUE TITLE
Steam Login

### ISSUE THREAD

**Issue by xCustomWorld** [gwillem/freeflarum.com#20]
> **Please request only 1 extension per issue!**

> **Bazaar or Upload extensions are not compatible with FreeFlarum. See [#18](https://github.com/gwillem/freeflarum.com/issues/18)**

__Packagist URL for extension:__
https://packagist.org/packages/nomiscz/flarum-ext-auth-steam

__Why we should install this extension?__
- You should install it because users could login with more thrid-party services, making loggining in even easier for people.

__URL with proof that extension works on the latest Flarum version (eg.: statement by author):__
https://discuss.flarum.org/d/19750-steam-auth
> Flarum v0.1.0-beta.8 and newer

**Comment by gwillem** [comment]
ty! installed
