### ISSUE TITLE
HTML Head Items

### ISSUE THREAD

**Issue by DakotaDAllen** [gwillem/freeflarum.com#200]
__Packagist URL for extension:__
https://packagist.org/packages/ianm/html-head
 
__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://discuss.flarum.org/d/25907-html-head-items/17

**Comment by CWKevo** [comment]
Added, in order to be able to use Google meta verification tags
