### ISSUE TITLE
No Self Likes

### ISSUE THREAD

**Issue by vgrakv** [gwillem/freeflarum.com#201]
__No Self Likes URL for extension:__
https://discuss.flarum.org/d/26701-no-self-likes [...]

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__ Was created today

**Comment by meetdilip** [comment]
Should we give some shelf time for new extensions ?

**Comment by CWKevo** [comment]
> Should we give some shelf time for new extensions?

Yes, FreeFlarum isn't even beta.16 yet anyways

**Comment by CWKevo** [comment]
Added
