### ISSUE TITLE
Achievement system

### ISSUE THREAD

**Issue by masonafaw** [gwillem/freeflarum.com#202]
__Packagist URL for extension:__
https://packagist.org/packages/malago/flarum-achievements

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__ 

![image](https://user-images.githubusercontent.com/66481679/114913532-50023a80-9def-11eb-86a0-0f0cdf92dbfc.png)

**Comment by CWKevo** [comment]
`^0.2.5` is for `beta.16`, your version supports `beta.14` only, which is not latest version of Flarum.

**Comment by masonafaw** [comment]
Would^0.2.5 work?

**Comment by CWKevo** [comment]
> Would^0.2.5 work?

Yes

**Comment by masonafaw** [comment]
> > Would^0.2.5 work?
> 
> Yes

Could that one be put on?

**Comment by CWKevo** [comment]
When FreeFlarum updates to beta.16

**Comment by masonafaw** [comment]
Would that be like by end of month?

**Comment by CWKevo** [comment]
Can't tell, perhaps

**Comment by CWKevo** [comment]
Added
