### ISSUE TITLE
Flarum Categories

### ISSUE THREAD

**Issue by xTyp** [gwillem/freeflarum.com#205]
Packagist URL: https://packagist.org/packages/askvortsov/flarum-categories
Proof it works: https://discuss.flarum.org/d/23184-flarum-categories

**Comment by xTyp** [comment]
just realized it's a thing; but I do not think it's the updated version

**Comment by CWKevo** [comment]
The latest version is only for beta.16, FreeFlarum is still running beta.15. But I updated all extensions anyways just to be sure, now the forums need to be synced (as usual). I'm closing this, as when we update to beta.16, the latest versions for all extensions will be installed
