### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by Dreeam-qwq** [gwillem/freeflarum.com#206]
__Describe the bug:__

`www.freeflarum.com` is down and can't open.

__My FreeFlarum forum URL:__

**To Reproduce:*

1. Go to `www.freeflarum.com`
2. show `404 not found`

**Expected behavior:**

none

**Comment by CWKevo** [comment]
Remove the WWW and it'll work, the redirect from WWW broke, I'll look at it later today.

(so instead of https://www.freeflarum.com, you access https://freeflarum.com)
