### ISSUE TITLE
Unknown error occurs when adding custom domain.

### ISSUE THREAD

**Issue by Alexandre2006** [gwillem/freeflarum.com#208]
__Describe the bug:__

When changing the domain of my FreeFlarum to my custom domain, an unknown error occurs, and trying to access the website through my domain causes an SSL error.

__My FreeFlarum forum URL:__

https://thinkalex.flarum.cloud

**To Reproduce:**

1. Go to FreeFlarum settings
2. Add CNAME record to custom domain
3. Wait for propagation and click button to change domain

**Comment by CWKevo** [comment]
Could you tell me the URL you are trying to link please?

**Comment by Alexandre2006** [comment]
Hey! I'm trying to link forums.thinkalex.dev

**Comment by CWKevo** [comment]
I've fixed a bug in our code and your domain should now be linked too: https://forums.thinkalex.dev/
