### ISSUE TITLE
Clicking on tags will show all discussions

### ISSUE THREAD

**Issue by xCustomWorld** [gwillem/freeflarum.com#21]
**Describe the bug**
If you click on a tag from `./tags`, forum will show you all discussions. If you reload the page, it will show you the discussions under that tag (as is expected).

**What is your FreeFlarum host name**
customworld.freeflarum.com

**To Reproduce**
1. Go to forum.customworld.xyz
2. Click on any tag on the main page
3. You should see the list of all discussions
4. Reload the page - it is fixed, and discussions under this tag will show

This will work only if selecting tags from there:
![](https://i.ibb.co/yQxG7Lw/Screenshot-20190816-154024.jpg)

I have experienced this behavior only on my FreeFlarum forum, it works as it's supposed elsewhere. So it is not a bug in tags or FreeFlarum, perhaps an issue at my forum. I have tested it in Incognito mode, if there is a problem in my account or browser, but the bug is still here. 

**Expected behavior**
Tags show only discussions under that specific tag.

**Screenshot**
![Bug](https://user-images.githubusercontent.com/39010496/63171151-3ff2f000-c03b-11e9-9001-7543f079f723.jpg)

**Comment by gwillem** [comment]
It is a bug in Flarum, will be fixed in beta10: https://github.com/flarum/core/issues/1819

**Comment by gwillem** [comment]
https://discuss.flarum.org/d/21036-beta-9-bug-all-discussions-shown-when-opening-a-specific-tag
https://discuss.flarum.org/d/20960-home-page-selection-inconsistent
