### ISSUE TITLE
Flarum extension for authenticating with steam

### ISSUE THREAD

**Issue by DronXa** [gwillem/freeflarum.com#210]
__Packagist URL for extension:__
https://packagist.org/packages/nomiscz/flarum-ext-auth-steam

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
![image](https://user-images.githubusercontent.com/12373253/116994582-2f841c80-acd9-11eb-8a9a-cf969d303e42.png)
https://discuss.flarum.org/d/19750-steam-auth/47

**Comment by CWKevo** [comment]
Added

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)
