### ISSUE TITLE
Error caused by extension 

### ISSUE THREAD

**Issue by ub0nFPS** [gwillem/freeflarum.com#211]
"Flarum encountered a boot error. Details have been logged to the Flarum log file."

its the Progressive Web extension (Almost sure!)

My site:
https://jemixworlds.flarum.cloud/

**Comment by ShyzuuPlayz** [comment]
Try to disable it?

**Comment by CWKevo** [comment]
https://discuss.flarum.org/d/7585-free-flarum-hosting-on-an-expert-platform-by-freeflarum-com/2545

Fixed
