### ISSUE TITLE
Encountering a boot bug

### ISSUE THREAD

**Issue by Firebros1** [gwillem/freeflarum.com#214]
__Describe the bug:__

When I try to visit my site it gives me a boot error. 

__My FreeFlarum forum URL:__

https://robloxadhub.flarum.cloud/

**To Reproduce:**
1. Go to the website. It should give you a boot error as soon as you try to get in.
**Expected behavior:**
It loads in without a problem and I'm able to view the forum.
**Screenshot(s) of the bug (optional):**
![Untitled](https://user-images.githubusercontent.com/47542418/117865434-f5c88e00-b263-11eb-9601-7defbfe35482.png)

**Comment by CWKevo** [comment]
Fixed by clearing the cache
