### ISSUE TITLE
404 Not Found on custom domain

### ISSUE THREAD

**Issue by armst** [gwillem/freeflarum.com#215]
__Describe the bug:__

When setting up my custom domain, the DNS mostly works, but hits a snag and comes back with an nginx 404 error. I've tried various combinations with same result...
forum -> junipergrove.flarum.cloud
forum -> junipergrove.flarum.cloud.
forum -> junipergrove.freeflarum.com
forum -> junipergrove.freeflarum.com.

__My FreeFlarum forum URL:__

junipergrove.flarum.cloud

__My custom domain:__

forum.junipergrove.co
(DNS with Dreamhost)

**To Reproduce:**

1. Go to https://forum.junipergrove.co/ and notice 404 error
2. Go to https://mxtoolbox.com/SuperTool.aspx?action=a%3aforum.junipergrove.co&run=toolpage and notice error messages

**Expected behavior:**

forum.junipergrove.co correctly directs to junipergrove.flarum.cloud

**Related issues**
https://github.com/gwillem/freeflarum.com/issues/208

**Comment by CWKevo** [comment]
I've fixed it by manually running the FreeFlarum's domain link command, I am not sure why it failed or what was the error, as I haven't found it in the logs.

Did any error message appear at the settings page when you tried to change the DNS?

**Comment by armst** [comment]
@CWKevo So I'd put my custom domain in FreeFlarum settings (https://freeflarum.com/settings) before the DNS was propagated, maybe that was the issue? I needed to go re-save/refresh it there after it was set correctly?
Either way, this issue is resolved, thank you :)

**Comment by CWKevo** [comment]
Perhaps, but

> Did any error message appear at the settings page when you tried to change the DNS?
