### ISSUE TITLE
Preview Discussion

### ISSUE THREAD

**Issue by Aleperix** [gwillem/freeflarum.com#216]
Please add the Preview Discussion Extension, this extension add the preview function while creating a new discussion.
https://extiverse.com/extension/simonxeko/preview-discussion

**Comment by CWKevo** [comment]
That's cool, but have you considered rich text editor as an alternative?

AKA. why should we include this extension?

**Comment by CWKevo** [comment]
I am closing this, as this is not compatible with Flarum 1.0.4 now. Feel free to re-open this or reply to this issue when it becomes compatible
