### ISSUE TITLE
reCaptcha or hCaptcha extension for registration

### ISSUE THREAD

**Issue by rg190** [gwillem/freeflarum.com#218]
Hi is possible add in FlarumFree any extension hCaptcha or reCaptcha in registration ?
Thanks

https://extiverse.com/extension/fof/recaptcha
https://github.com/FriendsOfFlarum/recaptcha

__Packagist URL for extension:__
https://packagist.org/packages/fof/recaptcha

**Comment by CWKevo** [comment]
Re-added
