### ISSUE TITLE
Twitter and Google login not working

### ISSUE THREAD

**Issue by xCustomWorld** [gwillem/freeflarum.com#22]
**Describe the bug**
"An error occured" error is shown when logining in with Google and Twitter. I'm using correct API keys and the Twitter and Google part of Sign In passes. I think that FreeFlarum can't process the request. Or it's just same bug like before that it couldn't resolve avatars. I saw it working on other FF forums through.

**What is your FreeFlarum host name**
customworld.freeflarum.com

**To Reproduce**
1. Sign Up by using Twitter or Google.
2. When you are redirected back to forum to the `auth` path, the error is shown.

**Expected behavior**
You login with Google or Twitter normally.

**Screenshots**
_null_

**Comment by gwillem** [comment]
Thank you. I can't see what's going wrong right now, I will look deeper into it.
