### ISSUE TITLE
BB code will only show up sometimes.

### ISSUE THREAD

**Issue by rg190** [gwillem/freeflarum.com#221]
Hi,

I have been using FreeFlarum for some time and notice that the BB code does not show (default plugin).
When I write something and I want to set a bold font, nothing happens. And sometimes yes.

I also try Flarum in 1.0.1. and there everything works fine. Is it possible that this is because FreeFlarum is still in beta?

**Description of the bug:** I will write some text, set me bold or italic I'll send and the text is still in the default form without change.

Plugin: BB Code  (in FreeFlarum is now version v0.1.0-beta.16)
https://github.com/flarum/bbcode

![vid_bug](https://user-images.githubusercontent.com/83711979/120641043-73527900-c473-11eb-9bc3-77f2418e187a.gif)

**Comment by CWKevo** [comment]
Perhaps it is a bug in BBCode, but we don't have any tools to monitor these issues or even fix them, so you'll have to wait until we update to 1.0.1

**Comment by meetdilip** [comment]
It is a bug in the editor. According to the author, it will be relaxed if you untick `mdarea` in the Markdown plugin.

**Comment by rg190** [comment]
Ok, I don't see any mdarea settings in the plugin.

**Comment by CWKevo** [comment]
Administration > Extensions > Markdown > "Enable mdarea?" > Off
