### ISSUE TITLE
Checklist an Flarum Extensions for post.

### ISSUE THREAD

**Issue by shawny43** [gwillem/freeflarum.com#222]
__Packagist URL for extension:__
https://packagist.org/packages/askvortsov/flarum-checklist

__Disscusion:__ https://discuss.flarum.org/d/26457-checklists

Checklist is a extension about adding checkboxes in discussions where that can be handy for see task we have to do or explain where are on from updates. Compatible with Rich Text.

Is aleary ready for __Flarum V 1.0__

But i think can be retro-compatible at this state.

**Comment by shawny43** [comment]
I fixed some missings titles.

**Comment by CWKevo** [comment]
Added
