### ISSUE TITLE
Group List

### ISSUE THREAD

**Issue by EnythNet** [gwillem/freeflarum.com#223]
__Packagist URL for extension:__
https://packagist.org/packages/clarkwinkelmann/flarum-ext-group-list

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://discuss.flarum.org/d/25386-group-list

**Comment by CWKevo** [comment]
Not compatible with 1.0.2 yet

**Comment by CWKevo** [comment]
Added
