### ISSUE TITLE
Action Logs

### ISSUE THREAD

**Issue by EnythNet** [gwillem/freeflarum.com#224]
__Packagist URL for extension:__
https://packagist.org/packages/sycho/flarum-action-log

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://discuss.flarum.org/d/25731-action-log

**Comment by CWKevo** [comment]
Not compatible with 1.0.0, will be included when we update and this extension does too

**Comment by CWKevo** [comment]
This extension is still not compatible with 1.0.x, perhaps you might be interested in [Audit Log Free](https://discuss.flarum.org/d/24432) as a replacement?

**Comment by CWKevo** [comment]
Added (Audit Log Free)[https://discuss.flarum.org/d/24432] as an alternative
