### ISSUE TITLE
Flarum User Badges

### ISSUE THREAD

**Issue by jaspervriends** [gwillem/freeflarum.com#225]
As far as I know ([and read](https://discuss.flarum.org/d/26449-user-badges/68)) our extension isn't supported yet :)

__Packagist URL for extension:__
https://packagist.org/packages/v17development/flarum-user-badges

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__ https://discuss.flarum.org/d/26449-user-badges/53

Extension is actively maintained by @v17development

**Comment by CWKevo** [comment]
Thanks, will be added when we update to new Flarum version

**Comment by CWKevo** [comment]
Added
