### ISSUE TITLE
I can't upload profile photo

### ISSUE THREAD

**Issue by Afacanc38** [gwillem/freeflarum.com#226]
__Describe the bug:__

I can't upload profile photo.

__My FreeFlarum forum URL:__

https://ozgurlukicin.yapboz.ml/

**To Reproduce:**

1. I went to user settings.
2. I clicked on your profile picture.
3. I pressed the "Edit" button.
4. I uploaded my 500x500px photo.
![renkli-arkaplanlı](https://user-images.githubusercontent.com/66299502/123551402-3def3180-d77a-11eb-9d82-ed339b84586c.png)
5. I saw "Opps. Bir şeyler yanlış gitti. Lütfen sayfayı yenileyip tekrar deneyin." error. (I use the forum in Turkish.)

**Expected behavior:**
I speak Turkish and use the Google Translate service because I do not speak English. Please ignore any errors in my speech.

**Screenshot(s) of the bug (optional):**
![Ekran görüntüsü 2021-06-27 18-47-30](https://user-images.githubusercontent.com/66299502/123550872-27e07180-d778-11eb-8f7e-d5bb6f4ba226.png)

**Comment by Afacanc38** [comment]
**Improvement:** I tried shrinking the photo to 200x200 in GIMP and tried again, but it didn't work.

**Comment by CWKevo** [comment]
Hi,

I was able to upload the profile picture normally (https://ozgurlukicin.yapboz.ml/u/tester), which could mean that there is something wrong on your side?

I have noticed that your page shows a red padlock - this means that the connection is not secured. That could be the problem, as browsers usually do not like requests being made between unsecured protocols. I'd suggest to secure your domain with a certificate, but this is something that you should consult with your domain provider.

**Comment by Afacanc38** [comment]
Red padlock? On my side it says "Connection is secure".

![Ekran Görüntüsü - 2021-06-27 19-18-20](https://user-images.githubusercontent.com/66299502/123551915-890a4400-d77c-11eb-9c55-10ef46d1e912.png)

**Comment by CWKevo** [comment]
That's strange, it shows green for me too now. Before, it reported that the connection is insecure.

Anyways, you could try registering a new test account and upload the avatar to see if the error is related to your admin account only, or it is a browser kind of thing.

**Comment by Afacanc38** [comment]
I'm still getting the same error. I will try from different devices and different browsers.

![Uploading Ekran görüntüsü 2021-06-27 19-45-45.png…]()

**Comment by azeez010** [comment]
I am having same issues, I can't find solution, the above didnt work

**Comment by CWKevo** [comment]
> I am having same issues, I can't find solution, the above didnt work

Hi, this is not related to the issue above. I have fixed this now ([details](https://discuss.flarum.org/d/7585/4129))
