### ISSUE TITLE
Confix Theme - Extensions

### ISSUE THREAD

**Issue by shawny43** [gwillem/freeflarum.com#228]
__Packagist URL for extension:__
https://packagist.org/packages/yannisme/confixtheme

Discuss: https://discuss.flarum.org/d/27987-confix-theme

__Why should we install the extension?__
Needs themes for people who want a simplier ways without the needs of css edit.
Soo this extension will take a modern style and simplier to use. More elegant too. 

This still in beta but is looking working great. Soo why not try to get some themes?

**Comment by shawny43** [comment]
Oops! I forgot the title again. Sorry!

**Comment by CWKevo** [comment]
Added

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)
