### ISSUE TITLE
Blank Screen After Reset at Freeflarum services

### ISSUE THREAD

**Issue by shawny43** [gwillem/freeflarum.com#229]
__Describe the bug:__

I tried to do some tweaks by turn on confix theme and stuff but there error 500 everytimes i reset to factory and there no errror 500 but a blank screen in the admin panel. There a broken place.

__My FreeFlarum forum URL:__

https://shawny43.flarum.cloud/

**To Reproduce:**

1. Go to Freeflarum website (Forum Settings
2. Reset settings
3. Go to admin panel from the Forum

...etc.

**Expected behavior:**

The forum behaves normally *run very well before the arrive of some modifications*.

**Screenshot(s) of the bug (optional):**
![blankscreen](https://user-images.githubusercontent.com/53010077/124396474-c9674600-dcd7-11eb-9c95-d72c9aeaf2ec.jpg)

**Comment by CWKevo** [comment]
What does the JavaScript console say? Seems like a JS error. Is Confix still enabled?

**Comment by shawny43** [comment]
Ummm... Let's me check...

Yeah i found it some critical errors
![consoleadmin](https://user-images.githubusercontent.com/53010077/124396638-b43ee700-dcd8-11eb-9de4-62bb27d7ee9b.jpg)

**Comment by shawny43** [comment]
Okay! Admin Panel is now show the panel settings. Thx

**Comment by CWKevo** [comment]
I didn't do anything
Perhaps it was just a cache issue of some sort

**Comment by shawny43** [comment]
Hmm... Idk whats happends really. But anyways i hope that work again after all my config.
