### ISSUE TITLE
Pipetables (Tables)

### ISSUE THREAD

**Issue by xCustomWorld** [gwillem/freeflarum.com#23]
__Packagist URL for extension:__
https://packagist.org/packages/kvothe/pipetables

__Why we should install this extension?__
- We just need tables, because there is no way we can currently insert tables.

__URL with proof that extension works on the latest Flarum version (eg.: statement by author):__
> • requires
flarum/core: ^0.1.0-beta.8 (beta.8 and above)

**Comment by xCustomWorld** [comment]
I think that the Formatting extension already supports this.

**Comment by CWKevo** [comment]
Apparently it does no longer support pipetables. #106 brings this back up, so this stays closed.
