### ISSUE TITLE
Level ranks Extensions

### ISSUE THREAD

**Issue by vudoanbinhminh** [gwillem/freeflarum.com#232]
__Packagist URL for extension:__
https://packagist.org/packages/ianm/level-ranks

__Why should we install the extension?__
I just see it on flarum.pro , it's quite interesting . This extension will help users who want to be more active . It is also compatible with the existing confix theme on flarum

![image](https://user-images.githubusercontent.com/33306530/124855564-527dc600-dfd3-11eb-9fa7-438ca74329b3.png)

**Comment by shawny43** [comment]
Uuh, did you read the template? Where the link to the packagist? Sorry for distrub your idea, but how the team can find it if you don't share a Packagist link?

**Comment by CWKevo** [comment]
Thanks for the note. I understand what you mean, and yes putting Packagist link into issues is the official way, but it's not that hard to get the link from the discussion either. Most people don't follow the templates anyways, and for me it's not a big deal for as long as I know what they want

**Comment by vudoanbinhminh** [comment]
> Uuh, did you read the template? Where the link to the packagist? Sorry for distrub your idea, but how the team can find it if you don't share a Packagist link?

it's my fault, I confused Packagist URL with topic's official url of that extension (my english is not very good). fixed it

**Comment by shawny43** [comment]
That okay, the packagist url is just a shortcut for the team.

**Comment by CWKevo** [comment]
Added
