### ISSUE TITLE
request problem

### ISSUE THREAD

**Issue by StudziakYT** [gwillem/freeflarum.com#235]
Describe the bug:

Hello, I have a problem with my forum, when I enter a thread it says "The requested resource was not found.
"also shows that there are 0 discussions and 0 posts. Can you restore some posts, at least Forum Rules?

My FreeFlarum forum URL:

https://forum.freshmc.pl

To Reproduce:

Click on any topic
Expected behavior:

I didn't look at the forum for quite a long time, but when the new user wanted to view them, he appeared that there was no thread, also that the number of posts and discussions was 0 and you can see that there are threads on the right side

Screenshot(s) of the bug (optional):
https://i.imgur.com/7IWIxUy.png
https://i.imgur.com/4RNHuoO.png
https://i.imgur.com/hdA41m1.png

**Comment by CWKevo** [comment]
Duplicate of #233 - please do not open multiple issues.

The data is in the database, Flarum just fails to load it:

```
flarum.ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`flarum_freshmc`.`group_user`, CONSTRAINT `group_user_group_id_foreign` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE CASCADE) in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:112
```

It appears that your database was somehow corrupt during the time you were inactive.

I have tried to import the oldest backup from last week, however that didn't work. I might need to drop the group_user table and re-create it. Or do you have older backup copy by any chance?

**Comment by StudziakYT** [comment]
I do not have any backups, I only care to restore the thread "Regulamin Forum", as for users, they can be reset, I have no problem with that

**Comment by CWKevo** [comment]
Well, it took me some time, but I have copied our skeleton forum database and restored at least all discussions, posts, mentions and users, along with avatars. That's the best I could do, since resetting the `group_user` table did not help no matter how hard I tried. Sorry, I hope that this is enough.

You can view your forum at https://freshmc.freeflarum.com/ - you will need to update the theme and re-setup all extensions though.
