### ISSUE TITLE
Flamoji - Emoji Picker that can be self-customizable

### ISSUE THREAD

**Issue by vudoanbinhminh** [gwillem/freeflarum.com#237]
__Packagist URL for extension:__
https://packagist.org/packages/the-turk/flarum-flamoji
Topic : https://discuss.flarum.org/d/28095-flamoji

__Why should we install the extension?__
Finally, there is an emoji picker that we can customize and use it on forums (like discord). I've been waiting for it for a long time and this makes me so excited .

This ext will be suitable for forums that want to design their own emojis, more personalized and more suitable for their active topics.
![image](https://user-images.githubusercontent.com/33306530/125151406-103dbb80-e170-11eb-8a0b-7c67352340f5.png)
![image](https://user-images.githubusercontent.com/33306530/125151410-1338ac00-e170-11eb-87a9-5dab32687f8d.png)

**Comment by meetdilip** [comment]
Adding external files to FF server ? Even if they are smileys or emojis, not sure.

**Comment by CWKevo** [comment]
> Adding external files to FF server ? Even if they are smileys or emojis, not sure.

They're just images and a mere path in the database, they get only rendered client side, so I am personally not against this extension. Image like any other. What concerns you?

**Comment by meetdilip** [comment]
Ok. if you feel that way, I have no objection.

**Comment by CWKevo** [comment]
This conflicts with EmojiOne area, so I am not going to add this now. I will try to figure which one we should include later - or maybe it'll become compatible eventually

**Comment by CWKevo** [comment]
This still conflicts with EmojioneArea, so we can't include it. If it ever becomes compatible, you are free to reopen this issue.

**Comment by TB54** [comment]
Sorry, it's total newbie question, but was the "EmojiOneArea" you're talking about an extension? Because I don't see it in the freeflarum menu, so if it's not used anymore, Flamoji could be usable (I would be a very convenient extension).

**Comment by CWKevo** [comment]
@TB54 it's installed (called "Emoji Picker"). Flamoji still can't be installed alongside it.

I will look at how many forums are actually using the EmojiOneArea extension. If not many, I'll swap it with Flamoji.

**Comment by TB54** [comment]
Oh ok! Emoji Picker is the logical substitute, yes, but we are stuck with old look emoji.

**Comment by CWKevo** [comment]
This extension is now available as a replacement for EmojiOneArea

**Comment by TB54** [comment]
Awesome, thanks!
