### ISSUE TITLE
WelcomeBox from Justoverclock

### ISSUE THREAD

**Issue by shawny43** [gwillem/freeflarum.com#238]
__Packagist URL for extension:__
https://packagist.org/packages/justoverclock/flarum-ext-infocards
__Why should we install the extension?__

Discuss: https://discuss.flarum.org/d/27053-infocards-welcomebox-20

Is a extension to show up your profile and say welcome. Anyways, that can be nice for people.

**Comment by CWKevo** [comment]
Added
