### ISSUE TITLE
Terms

### ISSUE THREAD

**Issue by CWKevo** [gwillem/freeflarum.com#24]
__Packagist URL for extension:__
https://packagist.org/packages/flagrow/terms

__Why we should install this extension?__
- You should install it because it would be nice to let users know about the Terms and Privacy Policy, which each forum can make, to make users be aware of forum rules, for example.

__URL with proof that extension works on the latest Flarum version (eg.: statement by author):__
> requires
flarum/core: ^0.1.0-beta.8 (beta.8 and higher)

**Comment by DLSS604** [comment]
this would also be usefull to be able to comply with the GDPR :D

**Comment by CWKevo** [comment]
Added!
