### ISSUE TITLE
Discussion Bookmarks Extension

### ISSUE THREAD

**Issue by vudoanbinhminh** [gwillem/freeflarum.com#240]
__Packagist URL for extension:__
https://packagist.org/packages/clarkwinkelmann/flarum-ext-bookmarks

__Why should we install the extension?__
Similar feature to "save to facebook", it helps members revisit the topic they like on all devices .

This extension can also reduce the frequency of spamming users (usually, user will randomly comment on topic they like to comeback when they're ready, that will be faster than bookmarking with the browser)

**Comment by vudoanbinhminh** [comment]
so sr , i was confused between post bookmark extension with discussion bookmark

**Comment by vudoanbinhminh** [comment]
sorry , i got a little confused between "post bookmarks" and "discusstion bookmarks"

**Comment by CWKevo** [comment]
Added
