### ISSUE TITLE
Websocket for replacing Pusher

### ISSUE THREAD

**Issue by shawny43** [gwillem/freeflarum.com#241]
__Packagist URL for extension:__
https://packagist.org/packages/

Discuss: https://discuss.flarum.org/d/23473-websockets-locally-hosted-alternative-for-pusher-now-free

__Why should we install the extension?__

Websocket will replace pusher and make better to update than pusher one. And is free.

**Comment by shawny43** [comment]
This guys doesn't send packagist link. Soo im going to find it.

**Comment by CWKevo** [comment]
Added
