### ISSUE TITLE
Whisper a real-time chatting. (Work with Websocket extension.)

### ISSUE THREAD

**Issue by shawny43** [gwillem/freeflarum.com#242]
__Packagist URL for extension:__
https://packagist.org/packages/
No packagist link posted.

Discuss: https://discuss.flarum.org/d/28256-whisper-encryption-less-private-messaging

__Why should we install the extension?__

To replace neon chat, is pretty easier and more simple than a private discutions panel. And feel more like a messenger.

**Comment by CWKevo** [comment]
Added
