### ISSUE TITLE
Custom Header

### ISSUE THREAD

**Issue by Tall-Bird** [gwillem/freeflarum.com#244]
__Packagist URL for extension:__
https://packagist.org/packages/justoverclock/custom-header

__Why should we install the extension?__
I'd like to have a custom welcome screen for people who are new to the forum and not logged in, and a seperate header for those who're logged in. This seems to do so in an easy manner.

**Comment by CWKevo** [comment]
Added

**Comment by Tall-Bird** [comment]
Hi! Just wanted to add that this (unfortunately) does not interact in the way I expected, and as such I won't personally be using it. Not sure if you'd like to keep it up; but I figure that's up to you guys : )

**Comment by CWKevo** [comment]
I am keeping this extension. It is minimal and is used by other forums. Sorry that this isn't what you were looking for, but perhaps you could send some suggestions on how to improve the extension to the author

**Comment by Tall-Bird** [comment]
Not a problem! I'll see if I can reach out to the author about it. Thanks anywho!
