### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by Tall-Bird** [gwillem/freeflarum.com#245]
__Packagist URL for extension:__
https://packagist.org/packages/katosdev/signature

__Why should we install the extension?__
I'd like to give my users the ability to add in small signatures to be able to easily provide some more in-depth customisability. In previous forums I've used, signatures were a popular method for users to distinguish themselves without having to click on their profile picture and great pride was taken in them. I'd like to re-create the same feeling I had as with previous forums, where users can enjoy the energy they put into their personas.

**Comment by meetdilip** [comment]
This is a very nice feature in my opinion. I like text-only signatures though. That is also available as an option, I think.

**Comment by CWKevo** [comment]
Added

**Comment by meetdilip** [comment]
Thanks :)
