### ISSUE TITLE
Gif profile

### ISSUE THREAD

**Issue by e32b** [gwillem/freeflarum.com#247]
My bad english sorry, support for making gif profiles

**Comment by CWKevo** [comment]
This repository is intended for FreeFlarum related feature requests and extension requests. We are not affiliated with Flarum. FreeFlarum and Flarum are two separate things that operate independently - FreeFlarum acts as a hosting for Flarum, while Flarum is the forum software that our forums are running on. Right now, you are requesting a Flarum feature, which we have no control over.

- If an extension already exists that fulfils your requirements, please open a new issue and follow the template (you can search for extensions at https://extiverse.com/)
- If you have a feature request for Flarum itself, please open a new discussion at https://discuss.flarum.org/t/feedback

There currently doesn't seem to be an extension that allows uploading a GIF image as a profile picture, so I'd recommend you to request it at https://discuss.flarum.org instead. Sorry, but we can't help you with this
