### ISSUE TITLE
reFlar Webhooks

### ISSUE THREAD

**Issue by xCustomWorld** [gwillem/freeflarum.com#25]
__Packagist URL for extension:__
https://packagist.org/packages/reflar/webhooks

__Why we should install this extension?__
- You should install it because I think that many people would welcome the feature to get notified of certain discussions in a specific Discord or Slack channel. For example, I use Discord a lot and this feature would come in really handy for me.

__URL with proof that extension works on the latest Flarum version (eg.: statement by author):__
![Yes](https://user-images.githubusercontent.com/39010496/63214366-a8170400-c117-11e9-8be5-58424538731d.png)
Should work, as it says beta.8 and above. Most beta.8 extensions should work in beta.9.

**Comment by gwillem** [comment]
installed

**Comment by xCustomWorld** [comment]
Thank you! Wow, the changes are pushed literally instantly! Insane.
