### ISSUE TITLE
flarum-hideprofile

### ISSUE THREAD

**Issue by Dscord** [gwillem/freeflarum.com#251]
__Packagist URL for extension:__
https://packagist.org/packages/serakoi/flarum-hideprofile

__Why should we install the extension?__
This would allow people to hide test forum accounts

**Comment by CWKevo** [comment]
FYI this extension doesn't seem to do anything at the moment. Looking at the source shows you just a "hello world" message being printed to the console:

https://github.com/Serakoi/flarum-hideprofile/blob/main/js/src/forum/index.js#L1-L3

It seems that the author wanted to start working on it, but it was never finished (or not finished yet). There is not even a Discuss discussion for that extension. So, as I see it, including it is currently useless

**Comment by Dscord** [comment]
Oh, I'm sorry for adding this then, haha, I had no idea this had nothing on it, Sorry for wasting your time!

**Comment by CWKevo** [comment]
It's okay, you didn't waste my time. You can leave this issue open in case the author decides to finish it someday, but that's up to you
