### ISSUE TITLE
BBCode Progress Bars

### ISSUE THREAD

**Issue by vudoanbinhminh** [gwillem/freeflarum.com#256]
__Packagist URL for extension:__
https://packagist.org/packages/miniflar/bbcode-progress-bars
Topic : https://discuss.flarum.org/d/28694-bbcode-progress-bars-by-miniflar

__Why should we install the extension?__
show progress bar in post, useful for many different purposes , like progress report , composition , etc.

![image](https://user-images.githubusercontent.com/33306530/130191871-7e49641a-97ba-4d46-b2a4-a4e2e26bb1ac.png)

**Comment by CWKevo** [comment]
Added
