### ISSUE TITLE
Chinese Language Pack / 中文語言包

### ISSUE THREAD

**Issue by bili-360nemz** [gwillem/freeflarum.com#258]
__Packagist URL for extension:__
https://discuss.flarum.org/d/17954-chinese-language-pack

__Why should we install the extension?__
 For more international users!

**Comment by CWKevo** [comment]
We already have this extension installed: https://discuss.flarum.org/d/22690 - it can be found at the bottom of the extension list, its name is in Chinese

The extension that you are requesting is not compatible with Flarum ^1.0, according to the latest posts in the discussion, so we can't install this. For these reasons, I am closing this.
