### ISSUE TITLE
Primary and Secondary tags are treated same

### ISSUE THREAD

**Issue by xCustomWorld** [gwillem/freeflarum.com#26]
**Describe the bug**
I have set up primary and secondary tags. I have set primary tags from 0 to 1 and secondary from 0 - 2. However, people can assign 2 primary tags (as if they were secondary ones). When setting secondary tags to 1, people can assign 1 primary tag, but no secondary tags (if they choose 2 primary tags, they cannot assign secondary ones at all - both tag categories are treated same, as one big category)

**What is your FreeFlarum host name**
customworld.freeflarum.com

**To Reproduce**
1. Create any discussion
2. Label it with any tag
3. Even though you are supposed to label max. 1 primary tags (counting only 2 level hierarchy, as it's taken as 1 tag), you can use 2 primary tags.

**Expected behavior**
People can choose only 1 primary tag. I never had this issue before, but after I enabled some of the new extensions, I noticed that it's a little buggy. I don't know if it's a bug in FreeFlarum or extensions, but you have access to the logs so hopefully they'll show you something useful...

**Screenshots:**
![](https://user-images.githubusercontent.com/39010496/63226890-6c943c80-c1e0-11e9-90f4-4445725a375f.jpg)
![](https://user-images.githubusercontent.com/39010496/63226891-6c943c80-c1e0-11e9-8fc8-dd981c003787.jpg)

**Comment by gwillem** [comment]
This seems like a Flarum issue, can you report at their forum?

**Comment by xCustomWorld** [comment]
[Done](https://discuss.flarum.org/d/21068-both-tag-categories-are-treated-same)

**Comment by xCustomWorld** [comment]
It looks like it's not a bug but a feature  I would like the old system back though :/
