### ISSUE TITLE
Amazon Affiliation by FriendsOfFlarum

### ISSUE THREAD

**Issue by tinny77** [gwillem/freeflarum.com#265]
__Packagist URL for extension:__
https://discuss.flarum.org/d/12389-friendsofflarum-amazon-affiliation

__Why should we install the extension?__
Very useful for forum monetization

**Comment by CWKevo** [comment]
Per our [Terms](https://freeflarum.com/docs/legal/terms/), forum monetization is currently not available/forbidden at FreeFlarum (section 9).
