### ISSUE TITLE
Pallet Theme

### ISSUE THREAD

**Issue by Dscord** [gwillem/freeflarum.com#266]
__Packagist URL for extension:__
https://packagist.org/packages/the-turk/flarum-pallet-theme

__Why should we install the extension?__
Great Theme, Will be used alot!

**Comment by CWKevo** [comment]
We can't include this at the moment because it conflicts with FoF Nightmode. I am leaving this open until author makes it compatible with that extension

**Comment by Dscord** [comment]
Have you sent a request to the developer(s) of Pallet Theme to make this compatible or shall I?

**Comment by CWKevo** [comment]
No, I haven't, you can do so at https://discuss.flarum.org/d/27757.

Although the developer is busy at the moment, and has stated that this extension is under minimal maintenance, if any maintenance at all. It is unlikely to receive any updates soon, but PRs are welcome

**Comment by CWKevo** [comment]
This still conflicts with Night Mode, so we are unforunately unable to include this at the moment. I am closing the issue, but feel free to reopen it, if there is a way to install it on FreeFlarum.
