### ISSUE TITLE
FriendsOfFlarum Google Recaptcha

### ISSUE THREAD

**Issue by AndersonTheThird** [gwillem/freeflarum.com#27]
__Packagist URL for extension:__
https://packagist.org/packages/fof/recaptcha

__Why we should install this extension?__
- You should install it because a bunch of sites at the moment use google recaptcha and it helps a bunch to prevent bots from making spam accounts, its also very easy to set up. It will increase security a bunch for sites on freeflarum that have this extension.

__URL with proof that extension works on the latest Flarum version (eg.: statement by author):__
https://discuss.infosecforge.io/ (click sign up and you will see the little silent recaptcha icon)

![image](https://user-images.githubusercontent.com/46432997/63465346-e5300e80-c415-11e9-8173-171ffdc9de93.png)

**Comment by xCustomWorld** [comment]
I would also like this extension :)

**Comment by gwillem** [comment]
Added
