### ISSUE TITLE
My forum is timing out?

### ISSUE THREAD

**Issue by shydert** [gwillem/freeflarum.com#278]
__Describe the bug:__

For some reason my forum is timing out? I've tried fixing up the forum using the tool that is on the freeflarum.com website, but that doesn't do anything? It shows up the App Offline screen.

__My FreeFlarum forum URL:__

https://gab.flarum.cloud

**Comment by CWKevo** [comment]
I've fixed this by resetting your domain back to https://gab.flarum.cloud. It is accessible again, and it was likely an issue with your domain. It might've been an error with your hosting, or they might have an outage. Either way, you'll need to reconfigure it in the settings (https://freeflarum.com/settings/forum_settings)

**Comment by shydert** [comment]
Thanks! Yeah it was a problem with my domain. I accidentally switched nameservers.
