### ISSUE TITLE
Google Ads (for supporting your forum)

### ISSUE THREAD

**Issue by Equinemarkt** [gwillem/freeflarum.com#279]
Hi! 
I'm sorry if I'm doing this wrong, this is my very first time using Github. So I'm sorry if this doens't belong here. 

I was looking for a way to support my forum and came across this: https://discuss.flarum.org/d/28506-davwheat-ad-units

Now I don't know how to implement this into my freeflarum forum, so maybe someone can make this available for freeflarum also? 

And again, sorry if this isn't the way for asking. You can delete this if this is wrong! 

Otherwise, thank you so much!

**Comment by CWKevo** [comment]
Sorry, but we don't allow monetization of forums per our [ToS](https://freeflarum.com/docs/legal/terms/) (9.)
