### ISSUE TITLE
Add Persian 

### ISSUE THREAD

**Issue by alefvanoon** [gwillem/freeflarum.com#281]
Persian language is not available at freeflarum.com
Please add one of this to freeflarum: 
https://packagist.org/packages/persianfla/flarum-ext-persian (https://github.com/persianfla/flarum-ext-persian)
https://packagist.org/packages/masterking32/flarum-lang-persian (https://github.com/masterking32/flarum-lang-persian)

**Comment by CWKevo** [comment]
None of these packages are compatible with Flarum 1.0.4, therefore we can't include them. Please, contact the author(s) and ask them for update, then we can include this language

**Comment by alefvanoon** [comment]
Hmm, thanks for your reply.
Also please checkout this: https://github.com/flarum-lang/persian

**Comment by CWKevo** [comment]
Great, that's up-to-date and compatible with latest Flarum! I've added it for all forums. These are synchronizing their extensions now, so you will have to wait some time before it works
