### ISSUE TITLE
Requesting twofactor

### ISSUE THREAD

**Issue by Kaleb99jOfficial** [gwillem/freeflarum.com#285]
__Packagist URL for extension:__
https://packagist.org/packages/reflar/twofactor

__Why should we install the extension?__
This extension should be added to FreeFlarum because it will greatly improve account security as it adds TOTP based 2FA.

**Comment by CWKevo** [comment]
It seems that https://github.com/Nearata/flarum-ext-twofactor is a suitable alternative, however it doesn't seem to have a thread at Discuss yet, therefore I think that we shouldn't include it yet, as it indicates that something might not be ready yet for it to go public.

**Comment by CWKevo** [comment]
Added https://github.com/Nearata/flarum-ext-twofactor
