### ISSUE TITLE
Single Sign On

### ISSUE THREAD

**Issue by JCKodel** [gwillem/freeflarum.com#29]
__Packagist URL for extension:__
https://packagist.org/packages/wuethrich44/flarum-ext-sso

__Why we should install this extension?__
- You should install it because allows users to integrate basically any website on flarum
- I want this extension because I have an app already with sign in and wish to provide my users a ininterrupted experience between app and flarum

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://discuss.flarum.org/d/5052-single-sign-on

**Comment by xCustomWorld** [comment]
This looks really wonderful, but as I can see, this extension requires a little bit more of setup, such as copying files locally etc... FreeFlarum does no really allow users to integrate with their files at all. Sorry

If I understood it right, you want users to be able to login with your app. All that I can recommend you is to just search for extensions that aim for social sign-in. Sorry, we can't help you with that currently. You can wait for @gwillem to see his statement but I'm pretty sure that this extension is currently not supported by FF. :(

**Comment by gwillem** [comment]
FreeFlarum doesn't have a method right now to add custom records to the database, so this won't work.
