### ISSUE TITLE
Add Flarum Japanese Language Pack

### ISSUE THREAD

**Issue by Kaleb99jOfficial** [gwillem/freeflarum.com#293]
__Packagist URL for extension:__
https://packagist.org/packages/takumi9942/flarum-ext-japanese

__Why should we install the extension?__
Back in the day FreeFlarum had a Japanese Language Pack but it became outdated. This one was last updated within the last month. The Packagist and GitHub page does not supply a Discuss link but it is at https://discuss.flarum.org/d/23757-japanese-language-pack-for-flarum.

**Comment by CWKevo** [comment]
Added
