### ISSUE TITLE
Custom domain name is unsuccessful

### ISSUE THREAD

**Issue by changfeng2021** [gwillem/freeflarum.com#295]
I encountered some problems when customizing the domain name. My domain name is hosted on cloudflare. My second-level domain name is: `https://xrayse.freeflarum.com/`. This is easy to use, but I want to customize the domain name. After reading the document, I set the CNAME key @, value xrayse.freeflarum.com and CNAME key forum, value xrayse.freeflarum.com respectively, but all failed. The hint is: xrayse.com does not CNAME to xrayse.freeflarum.com

**Comment by changfeng2021** [comment]
![截屏2021-11-24 上午1 30 54](https://user-images.githubusercontent.com/88228738/143074668-f2daa3c7-0f9d-4480-8361-6994787cfc72.png)

**Comment by CWKevo** [comment]
Hi,

this is not a bug - root CNAME isn't supported, as a limitation of the DNS standard (please see https://www.freecodecamp.org/news/why-cant-a-domain-s-root-be-a-cname-8cbab38e5f5c/ for more details).

You can therefore only link your forum to a subdomain. The first CNAME is alright and should work if you put `forum.xrayse.com` in the domain field at FreeFlarum. If you'd also like to access your forum from `xrayse.com`, I recommend you to create a redirect from this domain to the `forum` subdomain in your domain registrar settings, then it should work.

**Comment by changfeng2021** [comment]
> Hi,
> 
> this is not a bug - root CNAME isn't supported, as a limitation of the DNS standard (please see https://www.freecodecamp.org/news/why-cant-a-domain-s-root-be-a-cname-8cbab38e5f5c/ for more details).
> 
> You can therefore only link your forum to a subdomain. The first CNAME is alright and should work if you put `forum.xrayse.com` in the domain field at FreeFlarum. If you'd also like to access your forum from `xrayse.com`, I recommend you to create a redirect from this domain to the `forum` subdomain in your domain registrar settings, then it should work.

thank you for reply
