### ISSUE TITLE
Christmas Time For Flarum

### ISSUE THREAD

**Issue by shydert** [gwillem/freeflarum.com#296]
__Packagist URL for extension:__
https://packagist.org/packages/justoverclock/christmas-snow-effect

__Why should we install the extension?__
Well, Christmas is coming soon so why not install this extension so Flarum forums can be Christmas themed, too?

**Comment by CWKevo** [comment]
Added

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)
