### ISSUE TITLE
flarum-ext-purify

### ISSUE THREAD

**Issue by shydert** [gwillem/freeflarum.com#297]
__Packagist URL for extension:__
https://packagist.org/packages/justoverclock/flarum-ext-purify

__Why should we install the extension?__
As FoF Filter isn't working, this may replace it, as it seems to be better than it

**Comment by shydert** [comment]
why this has not been added yet

**Comment by CWKevo** [comment]
> why this has not been added yet

Because we operate FreeFlarum in our spare time, and someone might not have that time to add new extensions right now.

**Comment by CWKevo** [comment]
Added

**Comment by shydert** [comment]
> > why this has not been added yet
> 
> Because we operate FreeFlarum in our spare time, and someone might not have that time to add new extensions right now. I'll do it later today, sorry

It's fine, no worries. :)
