### ISSUE TITLE
FoF Share Social

### ISSUE THREAD

**Issue by xCustomWorld** [gwillem/freeflarum.com#30]
__Packagist URL for extension:__
https://packagist.org/packages/fof/share-social

__Why we should install this extension?__
- You should install it because there are no buttons to share my ideas currently... 

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
It requires `^beta.8` and as long as it provides just simple share, I think it will always work...

**Comment by gwillem** [comment]
Installed
