### ISSUE TITLE
Add Minecraft Avatars

### ISSUE THREAD

**Issue by Kaleb99jOfficial** [gwillem/freeflarum.com#300]
__Packagist URL for extension:__
https://packagist.org/packages/nearata/flarum-ext-minecraft-avatars

__Why should we install the extension?__
This should be added because it allows you to upload a Minecraft skin and use the face as your forum avatar. I see this as a cool feature.

**Comment by Kaleb99jOfficial** [comment]
I promise the two extensions I am requesting right now are the last until after Christmas.

**Comment by CWKevo** [comment]
Added
