### ISSUE TITLE
Events Countdown

### ISSUE THREAD

**Issue by shydert** [gwillem/freeflarum.com#304]
__Packagist URL for extension:__
https://packagist.org/packages/justoverclock/events-countdown

__Why should we install the extension?__
A simple countdown when you make some community events or smth.

**Comment by shydert** [comment]
**:(**

**Comment by CWKevo** [comment]
Added

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)
