### ISSUE TITLE
Related Discussions

### ISSUE THREAD

**Issue by nzlgl** [gwillem/freeflarum.com#306]
__Packagist URL for extension:__
https://extiverse.com/extension/justoverclock/related-discussions
__Why should we install the extension?__
It enhances user experience

**Comment by CWKevo** [comment]
This extension is paid, so we can't include it.

**Comment by justoverclockl** [comment]
@CWKevo i wonder if we could study something to make premium extension available for freeflarum.

**Comment by CWKevo** [comment]
> @CWKevo i wonder if we could study something to make premium extension available for freeflarum.

FreeFlarum has one master forum and all forums have their extensions synced with the master one, so with the current setup, we can't just include paid extension for specific forums that have paid for it. What ideas do you have in mind?

**Comment by justoverclockl** [comment]
i wonder if exist a way to pre-install all extension to freeflarum but unlock them for those who pay. Maybe freeflarum can take a little commission on top of each payements

**Comment by CWKevo** [comment]
I assume that it would be possible with a few PHP extenders that disallow people to enable these extensions.

Despite this, I still have no idea how this would work. I am afraid that these kind of payments might render us as a commercial service in some of our users' eyes, and we simply do not want that. It is therefore very unlikely that FreeFlarum will ever allow paid extensions to be used, in my opinion. But thanks for your input.
