### ISSUE TITLE
composer require jjandxa/flarum-ext-chinese-search

### ISSUE THREAD

**Issue by essesoul** [gwillem/freeflarum.com#307]
__Packagist URL for extension:__
https://github.com/jjandxa/flarum-ext-chinese-search

__Why should we install the extension?__

The search function is not available in Chinese language forums. This plug-in can solve this problem very well. I would appreciate it if you can add it.

**Comment by CWKevo** [comment]
This seems to be cool, however:
1) The README is all in Chinese, which I do not speak.
2) It seems that this requires another service to be installed (Xunsearch). Not just with Composer's require, but a full kind of installation (http://www.xunsearch.com/doc/php/guide/start.installation)
3) It's not compatible with Flarum 1.0.1

For all the reasons above, we can't include this extension, sorry
