### ISSUE TITLE
 justoverclock/flarum-ext-dontgoaway

### ISSUE THREAD

**Issue by essesoul** [gwillem/freeflarum.com#313]
__Packagist URL for extension:__
https://extiverse.com/extension/justoverclock/flarum-ext-dontgoaway

__Why should we install the extension?__
Function available:

When user click on external link, a popup will ask for consent before leaving the website
The Exit Int popup will be showed only for guest
The modal uses sessionstorage to appear only once per session
Modal Customization through admin setting:

Enable/Disable External link popup
Modal Title
Modal Text
Modal Image
Image width
Image Height
Button fontawesome icon
Button Text

**Comment by CWKevo** [comment]
Added
