### ISSUE TITLE
justoverclock/flarum-ext-welcomebox

### ISSUE THREAD

**Issue by essesoul** [gwillem/freeflarum.com#314]
__Packagist URL for extension:__
https://extiverse.com/extension/justoverclock/flarum-ext-welcomebox

__Why should we install the extension?__
Add Welcome Box Info in sidenav.

Upload/Remove avatar directly from the Welcome Box
Show total post counter
Show Total discussion counter
Show User Groups
Show Quick links to settings, mentions, profile and discussions

**Comment by CWKevo** [comment]
Added
