### ISSUE TITLE
 justoverclock/flarum-ext-socialcards

### ISSUE THREAD

**Issue by essesoul** [gwillem/freeflarum.com#315]
__Packagist URL for extension:__
https://extiverse.com/extension/justoverclock/flarum-ext-socialcards

__Why should we install the extension?__
Add social cards on indexpage

Admin can choose the link of personal social pages, and enable/disable them one by one.

**Comment by CWKevo** [comment]
Added

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)
