### ISSUE TITLE
ffans/clipboardjs

### ISSUE THREAD

**Issue by essesoul** [gwillem/freeflarum.com#316]
__Packagist URL for extension:__
https://extiverse.com/extension/ffans/clipboardjs

__Why should we install the extension?__
to add copy code approach with code language display to your Flarum. You can choose 7 different button styles, like GitHub, SegmentFault, etc.

Supports 47 common languages by default: .properties, apacheconf, bash, bbcode, c, csharp, css, cpp, coffeescript, diff, django, docker, dockerfile, git, go, html, ini, java, javadoc, js, json, less, lua, makefile, markdown, nginx, objectivec, perl, php, powershell, properties, python, python-repl, regex, ruby, rust, sass, scss, sql, stylus, swift, typescript, vim, visual-basic, vue, xml, yaml.

**Comment by CWKevo** [comment]
Added
