### ISSUE TITLE
ChadJessen - Theme Light Shadow

### ISSUE THREAD

**Issue by AndersonTheThird** [gwillem/freeflarum.com#32]
__Packagist URL for extension:__
~~https://packagist.org/packages/madchatthew/flarum-ext-themelightshadow~~
https://packagist.org/packages/madchatthew/themelightshadow

__Why we should install this extension?__
- I want this extension because it will make my forum look so much better and much more modern.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://flarumtr.com/ - It is running on 0.9, proof of this is if you look on the left bar and look at the very bottom it says it is running 0.9 
![image](https://user-images.githubusercontent.com/46432997/63882363-d6120900-c99f-11e9-9ca8-505db7b8db49.png)

**Comment by xCustomWorld** [comment]
**Update:** This extension is most likely no longer avaliabe/abandoned. The packagist URL is not working and I haven't found any similar extension.

You can obviously open an issue at the [extension's GitHub](https://github.com/Madchatthew/themelightshadow).

Alternatively, you can message me and I'll be happy to help you with some CSS snippets that can result in similar look.

**Comment by xCustomWorld** [comment]
**Another update:** https://packagist.org/packages/madchatthew/themelightshadow
Yes.

**Comment by AndersonTheThird** [comment]
@xCustomWorld Can you open this back up since you found the new packagist?

**Comment by gwillem** [comment]
Installed
