### ISSUE TITLE
Xelson/Neon Chat. (Flarum 1.1)

### ISSUE THREAD

**Issue by shawny43** [gwillem/freeflarum.com#321]
__Packagist URL for extension:__
https://packagist.org/packages/xelson/flarum-ext-chat

__Why should we install the extension?__
Neon Chat got a update from dev builds. Is now back to work.

**Comment by CWKevo** [comment]
I included the latest release, which is for Flarum 1.1 (as stated [here](https://discuss.flarum.org/d/25361/56)). I won't include `dev-master` versions of non-language/minimalistic extensions
