### ISSUE TITLE
pattinsonfuture/lang-traditional-chinese

### ISSUE THREAD

**Issue by bili-360nemz** [gwillem/freeflarum.com#322]
__Packagist URL for extension:__
https://packagist.org/packages/pattinsonfuture/lang-traditional-chinese

__Why should we install the extension?__
For make friends with users from Hong Kong, Taiwan and Macau.

**Comment by bili-360nemz** [comment]
> **Packagist URL for extension:** https://extiverse.com/extension/pattinsonfuture/lang-traditional-chinese
> 
> **Why should we install the extension?** For make friends with users from Hong Kong, Taiwan and Macau.

**Comment by CWKevo** [comment]
Added

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3827)
