### ISSUE TITLE
jjandxa/flarum-ext-chinese-search

### ISSUE THREAD

**Issue by Talath9801** [gwillem/freeflarum.com#329]
__Packagist URL for extension:__
https://packagist.org/packages/jjandxa/flarum-ext-chinese-search

__Why should we install the extension?__
This extension supports fuzzy search. The existing search function does not work if we enter incomplete words and search. This extension also facilitates Chinese or Japanese characters searching.

**Comment by CWKevo** [comment]
This extension does not seem to support stable (non-beta) versions of Flarum.

**Comment by Talath9801** [comment]
Got that! Thanks!



---Original---
From: ***@***.***&gt;
Date: Sat, Jan 15, 2022 10:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gwillem/freeflarum.com] jjandxa/flarum-ext-chinese-search (Issue#329)




 
This extension does not seem to support stable (non-beta) versions of Flarum.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zouyonghao** [comment]
> This extension does not seem to support stable (non-beta) versions of Flarum.

I am invesgating about how to search with CJK characters, and I also searched this extension and want to modify it to use in latest Flarum version.

Question is, as mentioned here https://github.com/gwillem/freeflarum.com/issues/307, this extension requires another service, so if I can update this extension, can this extension be installed on FreeFlarum?

**Comment by CWKevo** [comment]
> if I can update this extension, can this extension be installed on FreeFlarum?

Yes, if it:
- is compatible with the latest stable Flarum version;
- does not require an external service or software;

**Comment by zouyonghao** [comment]
> > if I can update this extension, can this extension be installed on FreeFlarum?
> 
> Yes, if it:
> 
> * is compatible with the latest stable Flarum version;
> * does not require an external service or software;

So it seems this extension can not be used as it requires external service, I'll try to find other ways.
