### ISSUE TITLE
FriendsOfFlarum - Reactions

### ISSUE THREAD

**Issue by AndersonTheThird** [gwillem/freeflarum.com#33]
__Packagist URL for extension:__
https://packagist.org/packages/fof/reactions

__Why we should install this extension?__
- You should install it because it allows people to express opinions easily and it can also be used to make polls.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
"It requires beta 9" - Extension Creator 
![image](https://user-images.githubusercontent.com/46432997/63883064-4c633b00-c9a1-11e9-9ef6-b0785d46f49f.png)

**Comment by gwillem** [comment]
Installed!
