### ISSUE TITLE
Ad Units

### ISSUE THREAD

**Issue by jgrillo2020** [gwillem/freeflarum.com#330]
__Packagist URL for extension:__

https://packagist.org/packages/davwheat/flarum-ext-ads

__Why should we install the extension?__
Ability to monetize from your forum by placing ad units on your forum

**Comment by CWKevo** [comment]
We do not allow monetization of forums, as our [ToS](https://freeflarum.com/docs/legal/terms) states

**Comment by jgrillo2020** [comment]
Sorry to waist your time, I forgot about this rule.
