### ISSUE TITLE
Vietnamese full package

### ISSUE THREAD

**Issue by luatdolphin** [gwillem/freeflarum.com#34]
> **Please request only 1 extension per issue!**

> **Bazaar or Upload extensions are not compatible with FreeFlarum. See [#18](https://github.com/gwillem/freeflarum.com/issues/18)**

__Packagist URL for extension:__
https://packagist.org/packages/luatdolphin/lang-vietnamese

__Why we should install this extension?__
- You should install it because it include full translation of extension's compatibility with FreeFlarum which current Vietnamese package is not supported.
- I want this extension because It is developed by me and I use FreeFlarum, so I will support it a long time.
- I hope you will update my package as soon as possible. Thank you so much! Best regards!

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://i.imgur.com/CckcwFM.png
https://i.imgur.com/FZrzhxL.png

**Comment by xCustomWorld** [comment]
Thank you for your contribution both to Flarum and FreeFlarum, community will surely appreciate your hard work ;).

However, extension adding is not my work ~~so I just came to congratulate you~~.

**Comment by gwillem** [comment]
Installed!
