### ISSUE TITLE
Location Map

### ISSUE THREAD

**Issue by jacobgrillo** [gwillem/freeflarum.com#344]
__Packagist URL for extension:__
https://packagist.org/packages/justoverclock/users-map-location

__Why should we install the extension?__
Allows users the share their city or location on the forum using a mapbox free public token. It would be a cool feature for users.

**Comment by CWKevo** [comment]
Added

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)
