### ISSUE TITLE
flarum-silent-edit

### ISSUE THREAD

**Issue by Profi420** [gwillem/freeflarum.com#346]
__Packagist URL for extension:__
https://packagist.org/packages/datlechin/flarum-silent-edit

__Why should we install the extension?__
Allows user groups to edit posts silently.
It's simply that only have the option of a clear last edit on PostControl, for now.
This option will remove the Edited from the post header.

**Comment by CWKevo** [comment]
Added

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)
