### ISSUE TITLE
Arabic Lang Pack fixing beta9

### ISSUE THREAD

**Issue by ziymed** [gwillem/freeflarum.com#35]
I try to install Arabic Language Pack in freeflarum but its not working
so i made some release 0.1.1 and hope it will be working .

Github : https://github.com/ziymed/lang-arabic
Packgist : https://packagist.org/packages/ziymed/lang-arabic

fixing issue with beta9
thank you

**Comment by xCustomWorld** [comment]
I checked the GitHub and I have found a lot of other php codes there. Is the code necessary to run your extension? I'm not a php coder but it looks like this extension changes some page elements and css a bit.

You were probably developing this locally or on your own hosting so you started to utilizing the code to fit your forum. The thing is that it might not fit other forums. Maybe a person at other forum just wants plain Arabic language without any CSS additions.

Could you tell me, what is your extension exactly doing? Thank you!

**Comment by gwillem** [comment]
I am not sure whether the locale can change the text direction, so @ziymed may have found a proper solution. Thanks, updated!

**Comment by ziymed** [comment]
thank you @gwillem and @xCustomWorld 

I will make a lite version with : 

- local 
- change direction 

And without : 

- changing the slug to arabic
- allowing to have arabic username

thank you again.

**Comment by xCustomWorld** [comment]
We can add both versions and let people decide which one they'd like to use.

**Comment by ziymed** [comment]
thank you @xCustomWorld but still the last update not working in freeflarum and its working in my website and local, I think bec its need change the slug and allow to change the username to arabic .

**Comment by ziymed** [comment]
I have create another extension for freeflarum 

https://packagist.org/packages/ziymed/lang-ar
https://github.com/ziymed/lang-ar

Installation

Install Manualy :

composer require ziymed/lang-ar

Updating

composer update ziymed/lang-ar
php flarum cache:clear

Deleting

composer remove ziymed/lang-ar
php flarum cache:clear

This ext can do :

    Arabic translation
    RTL switch
    Discussion List Item rtl tooltip
    slug in arabic for new discussion title

**Comment by gwillem** [comment]
Removed because of: https://discuss.flarum.org/d/7585-free-flarum-hosting-on-an-expert-platform-by-freeflarum-com/923
