### ISSUE TITLE
davwheat Ad Units

### ISSUE THREAD

**Issue by Qu-projects** [gwillem/freeflarum.com#350]
__Packagist URL for extension:__
https://packagist.org/packages/davwheat/flarum-ext-ads

__Why should we install the extension?__
firstly thank you for this great initiative of providing free server but for running educational community i have to keep real teachers for interaction out of my expense which i feel my community should bear little bit on it so this extension will allow me to put ads in the community.

**Comment by CWKevo** [comment]
Sorry, FreeFlarum currently doesn't support monetization of forums. If you need ads, I'd suggest you to self-host your forum instead.

Please see #279, #191 and #183 for past requests and discussions on this topic.
