### ISSUE TITLE
Update to the latest commit of rich text

### ISSUE THREAD

**Issue by CharlieLeee** [gwillem/freeflarum.com#351]
__Packagist URL for extension:__
https://packagist.org/packages/askvortsov/flarum-rich-text#v2.1.6

__Why should we install the extension?__
The current rich text extension has a bug that cause confusing behavior when creating new post

**Comment by CWKevo** [comment]
I've updated all extensions and [all forums are currently being synced](https://discuss.flarum.org/d/7585/3402)
