### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Profi420** [gwillem/freeflarum.com#353]
Last Time we get often this message:
502 Bad Gateway
nginx

We did not change anything .. please fix

**Comment by Kaleb99jOfficial** [comment]
Also having this issue on my site.

**Comment by DeclanChidlow** [comment]
My forum has also encountered this issue.

**Comment by DeclanChidlow** [comment]
People are discussing it here:
https://discuss.flarum.org/d/7585-free-flarum-hosting-on-an-expert-platform-by-freeflarum-com/3402

**Comment by Profi420** [comment]
Are there no news? :(
what does this mean? https://freeflarum.com/status

**Comment by DeclanChidlow** [comment]
Probably nothing good

**Comment by DeclanChidlow** [comment]
Problem has been solved on my forum

**Comment by CWKevo** [comment]
Closing this, please see https://discuss.flarum.org/d/7585/3408
