### ISSUE TITLE
neerugupta/flarum-lang-arabic

### ISSUE THREAD

**Issue by medelinor-1** [gwillem/freeflarum.com#354]
__Packagist URL for extension:__

- [https://github.com/irmmr/flarum-ext-rtl](https://github.com/irmmr/flarum-ext-rtl)
- [https://github.com/neerugupta/flarum-lang-arabic](https://github.com/neerugupta/flarum-lang-arabic)

__Why should we install the extension?__
I'm trying to create a **Flarum forum in Arabic**, and since Arabic is a **right-to-left** language, to use the Arabic forum well, you need to add the extensions.

With Regards

**Comment by CWKevo** [comment]
Added

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)

**Comment by medelinor-1** [comment]
Hello
I noticed that this addition has **disappeared** from my forum, as it is no longer from right to left, but from left to right and this causes great confusion, and leads to _major problems_.
Please, is it possible to **re-add** or find an **alternative solution** for the forums in R-T-L languages.

My greetings
