### ISSUE TITLE
PipecraftNet/flarum-ext-id-slug

### ISSUE THREAD

**Issue by longlivemarxleninmaoism** [gwillem/freeflarum.com#360]
__Packagist URL for extension:__
https://packagist.org/packages/pipecraft/flarum-ext-id-slug

__Why should we install the extension?__
The Freeflarum website appears to have undergone some changes recently. Originally, when posting a topic thread in the forum, the default slug of FreeFlarum is id+title, and the Chinese characters will be removed, just like https://dipper.freeflarum.com/d/49-fireson/. But the slug of recent posts will be reflected in the post's directory in the form of Hanyu Pinyin（Alphabetized Chinese）,just like https://dipper.freeflarum.com/d/55-guan-yu-yi-ge-yong-yu-lian-luo-ge-di-di-fang-zu-zhi-he-ren-yuan-de-ping-tai-de-jian-li-de-ke-neng-xing-tao-lun/ . This makes the URL of the post too verbose. 

This plugin can better solve this problem.The author said in https://discuss.flarum.org.cn/d/2799/7/ that the plug-in will continue to be updated 

Thank you for your support.

**Comment by CWKevo** [comment]
I understand, installed.

As a side note, FreeFlarum didn't change this. Flarum and FreeFlarum are two separate, unaffiliated projects. It seems that it was changed in [this pull request for Flarum](https://github.com/flarum/framework/pull/3387), which changed the way how discussions are slugged in the recent 1.3.0 update.

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)
