### ISSUE TITLE
Remove this footer points to 404

### ISSUE THREAD

**Issue by justoverclockl** [gwillem/freeflarum.com#368]
i've noticed that the "remove this footer" points to a 404 page

https://www.freeflarum.com/docs/faq/#can-i-pay-to-remove-the-powered-by-freeflarum-footer-for-my-or-other-forum

;)

**Comment by CWKevo** [comment]
It seems that the `www` subdomain does not redirect to non-www. I've changed the link to not have WWW for the time being, so it should work properly now. Thanks for reporting this to us!
