### ISSUE TITLE
sitemap.xml 404

### ISSUE THREAD

**Issue by niccokunzmann** [gwillem/freeflarum.com#37]
**Describe the bug**

I would like to access the sitemap.

**What is your FreeFlarum host name**
https://wolfennord.flarum.cloud

**To Reproduce**
1. Go to https://wolfennord.flarum.cloud/sitemap.xml
4. See error 404

**Expected behavior**

A sitemap.

**Screenshots**

![image](https://user-images.githubusercontent.com/564768/64903187-b3c4fe80-d6b4-11e9-8689-c9ea97185cde.png)

**Possible Solution**

https://discuss.flarum.org/d/14941-flagrow-sitemap/11

**Comment by xCustomWorld** [comment]
I can confirm that I am getting the same error at my forum. Thanks for the report!

**Comment by neercsys** [comment]
I have same problem on my forum :/

**Comment by xCustomWorld** [comment]
This seems to be issue on all FreeFlarum forums, I don't know what could be the cause. If it would be bug in the extension itself, it would be probably fixed already. Perhaps reinstallation would help.

**Comment by liriarte** [comment]
I have the same problem

**Comment by gwillem** [comment]
Fixed! Thanks all for reporting.
