### ISSUE TITLE
Language Variables / Linguist

### ISSUE THREAD

**Issue by Gerryfw** [gwillem/freeflarum.com#40]
Packagist URL for extension:
https://packagist.org/packages/flagrow/linguist

__Why we should install this extension?__
There are some plugins that are not translated to German, for example. Unfortunately, Flarum offers no possibility to simply set language variables. The plugin offers you the opportunity to offer the forum in several languages on "Freeflarum".

**Comment by valterbarreira** [comment]
I also need this extension. Thanks

**Comment by gwillem** [comment]
Added fof/linguist
