### ISSUE TITLE
Discord Login

### ISSUE THREAD

**Issue by taciturasa** [gwillem/freeflarum.com#42]
__Packagist URL for extension:__
https://packagist.org/packages/fof/auth-discord

__Why we should install this extension?__
- You should install it because Discord is a highly popular chat program that is often run alongside a much longer form forum.
- I want this extension because I would like to create a forum that exists alongside a Discord community.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://i.imgur.com/pkqhaVL.png

**Comment by gwillem** [comment]
Installed!
