### ISSUE TITLE
Imgur Extension not working

### ISSUE THREAD

**Issue by stuli1989** [gwillem/freeflarum.com#43]
**Describe the bug**
I've activated the Imgur Extension so that users of my forum can upload images of their Art Work to Imgur so that they can share images with each other easily.

**What is your FreeFlarum host name**
artlounge.flarum.cloud

**To Reproduce**
1. Compose a new discussion/reply
2. Click on image upload button
3. See error

**Expected behavior**
When users click the highlighted image button they should be able to successfully upload images to imgur so that the link/preview shows up there.

**Additional Information**
I've created the Imgur Application without a Callback URL, Client ID is: <hidden by admins - do not share your Client ID>

Appreciate any help in sorting this bug out

**Comment by xCustomWorld** [comment]
[It seems to work for me](https://artlounge.flarum.cloud/d/5-works).

Maybe it's just a browser cache problem. Try refreshing page or relaunching browser...
