### ISSUE TITLE
fof/formatting (media Embed)

### ISSUE THREAD

**Issue by kimsible** [gwillem/freeflarum.com#44]
__Packagist URL for extension:__
[https://packagist.org/packages/fof/formatting](https://packagist.org/packages/fof/formatting)

__Why we should install this extension?__
- You should install it because it could bring a very better user experience
- I want this extension because my community needs to share quickly external content of social platforms like youtube, twitter, facebook...

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__ https://discuss.flarum.org/d/17770-friendsofflarum-formatting/83

**Comment by xCustomWorld** [comment]
Haha, yes it was already there :P

**Comment by CWKevo** [comment]
![It's that easy](https://i.imgur.com/5E476r7.jpg)
