### ISSUE TITLE
Reply 2 see by Kvothe

### ISSUE THREAD

**Issue by DDDASHXD** [gwillem/freeflarum.com#45]
__Packagist URL for extension:__
https://packagist.org/packages/kvothe/reply-to-see

__Why we should install this extension?__
- You should install this extension, as it make it easier to create spoilers, and to tell if a person is a leecher or not.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://discuss.flarum.org/d/18899-reply-2-see

**Comment by xCustomWorld** [comment]
Duplicate issue, if you make a mistake please reply to the issue and admins will fix it.
