### ISSUE TITLE
 Reply 2 see by Kvothe

### ISSUE THREAD

**Issue by DDDASHXD** [gwillem/freeflarum.com#46]
__Packagist URL for extension:__
https://packagist.org/packages/kvothe/reply-to-see

__Why we should install this extension?__
- You should install this extension, as it make it easier to create spoilers, and to tell if a person is a leecher or not.
- I want this because, as i said before, i need to be able to tell if a person is a leecher.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://discuss.flarum.org/d/18899-reply-2-see

**Edit by collab.:**
Old issue: #45 (for refference)

**Comment by xCustomWorld** [comment]
I was wbout to request this too, thank you. I don't need it at the moment, but leechers are all around me and when I make my forum more popular I will need this extension.

**Comment by DDDASHXD** [comment]
> I was wbout to request this too, thank you. I don't need it at the moment, but leechers are all around me and when I make my forum more popular I will need this extension.

You're welcome haha. And same, this could be really useful.

**Comment by CWKevo** [comment]
Another extension that does the exact job with more features: https://discuss.flarum.org/d/24193-login-2-see-plus

**Comment by CWKevo** [comment]
Installed Login2See, which seems better IMO.
