### ISSUE TITLE
Update Syndication extension

### ISSUE THREAD

**Issue by arthrfrts** [gwillem/freeflarum.com#47]
__Packagist URL for extension:__
https://packagist.org/packages/amaurycarrade/flarum-ext-syndication

The current Syndication version (v0.2) on FreeFlarum is generating invalid RSS feeds. v0.3.1 fixes it and adds support to newer versions of Flarum.

**Comment by gwillem** [comment]
Updated!

**Comment by jaypatelani** [comment]
RSS is back 😀 https://discuss.flarum.org/d/27687-syndication-rss-atom-feeds

Will we see that in next update ?
