### ISSUE TITLE
Perspective API

### ISSUE THREAD

**Issue by taciturasa** [gwillem/freeflarum.com#48]
__Packagist URL for extension:__
https://packagist.org/packages/tank/perspective

__Why we should install this extension?__
- You should install it because it would be a fantastic tool for helping moderate forums.
- I want this extension because I would like to have a very kind, friendly forum.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
Released within the current beta: https://discuss.flarum.org/d/21784-perspective-api

**Comment by CWKevo** [comment]
Installed!
