### ISSUE TITLE
[Request] New Extensions Please :D

### ISSUE THREAD

**Issue by RageYT** [gwillem/freeflarum.com#5]
Hello, I'd like to have the following extensions added into FreeFlarum. If you could please add these it would be much appreciated.

### Themes
https://github.com/ReFlar/nightmode

### Posting Utilities
https://github.com/MichaelBelgium/flarum-discussion-views
https://github.com/ReFlar/gamification

### Moderation Utilities
https://github.com/flagrow/users-list

**Comment by gwillem** [comment]
> flagrow/user-list
Not compatible with beta9.. there is fof/user-directory though?

> discussion-views
> gamification
> nightmode
installed!

**Comment by gwillem** [comment]
reflar/nightmode removed because it would crash the forum (at least under Firefox), see https://github.com/ReFlar/nightmode/issues/15
