### ISSUE TITLE
Emoji Picker

### ISSUE THREAD

**Issue by taciturasa** [gwillem/freeflarum.com#50]
__Packagist URL for extension:__
https://packagist.org/packages/clarkwinkelmann/flarum-ext-emojionearea

__Why we should install this extension?__
- You should install it because emojis are an important part of online discussion and it is difficult to use just typing since emojis often aren't named what they should be.
- I want this extension because I wish to let my users type emoji in a friendly way.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
Listed as current beta on flagrum: https://flagrow.io/extensions/clarkwinkelmann/flarum-ext-emojionearea

**Comment by CWKevo** [comment]
Installed!
