### ISSUE TITLE
Please create extension for ad manager

### ISSUE THREAD

**Issue by helphack333** [gwillem/freeflarum.com#51]
Please create advertisement management and banner management system extension to monetize our Forum.

Thank you for creating such beautiful forum.

**Comment by xCustomWorld** [comment]
Hello and thanks for your kind words.

However, I don't know what you exactly mean.

1. If you want to put ads on your forum and monetize it, I'm pretty sure that there are other ways to get money from your forum (perhaps sell some nice handmade baskets, that seems fine).
2. ~~yes i see you have specified the our word~~

My suggestion: Create a donation button and put it in your forum's footer. This should work :')

If you need more help, just reply.

**Comment by CWKevo** [comment]
I'm closing this issue now, as there is no further activity occurring. For those who are looking for a way how to monetize your forum, you can have a look at [Google AdSense](https://www.google.com/adsense/start/).

However, I'd prefer it if FreeFlarum forum users would consider staying with the donations alternative, as then no one is forced to pay. Obviously, you can't force anyone to pay for using your forum, forums doing this practice will be canceled.
