### ISSUE TITLE
FoF Night Mode

### ISSUE THREAD

**Issue by taciturasa** [gwillem/freeflarum.com#52]
__Packagist URL for extension:__
https://packagist.org/packages/fof/nightmode

__Why we should install this extension?__
- You should install it because it would allow users to switch between light and dark mode, instead of this being authoritated by the forum owners. This is an accessibility concern as well as a convenience one.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
Current forum users have it working: https://discuss.flarum.org/d/21492-friendsofflarum-night-mode/11

**Comment by xCustomWorld** [comment]
There was a night mode extension by reFlar but then it got deleted after updating to beta.10. I guess it was incomatible. I had that extension on my forum so I hope that this one will work as well!

**Comment by Tiixxel** [comment]
I would also like to have this Extension available because each User should choose whether they would use Light or Dark Mode.

**Comment by taciturasa** [comment]
Hey, it's been a few months. Any more word on some of these extensions?

**Comment by RanokES** [comment]
> Hey, it's been a few months. Any more word on some of these extensions?

Yeah, please check the extension out, it would be great!

**Comment by Geshii** [comment]
Please put the extension ^^

**Comment by gwillem** [comment]
Added
