### ISSUE TITLE
FoF StopForumSpam

### ISSUE THREAD

**Issue by taciturasa** [gwillem/freeflarum.com#53]
__Packagist URL for extension:__
https://packagist.org/packages/fof/stopforumspam

__Why we should install this extension?__
- You should install it because it would help forum owners mitigate spam.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://i.imgur.com/Cu08ne4.png

**Comment by owii03** [comment]
hello! I'm requesting this extensions too, thanks :)

**Comment by CWKevo** [comment]
Installed!
