### ISSUE TITLE
FoF Prevent Necrobumping

### ISSUE THREAD

**Issue by taciturasa** [gwillem/freeflarum.com#54]
__Packagist URL for extension:__
https://packagist.com/...

__Why we should install this extension?__
- I want this extension because I would like to keep users from bringing back old threads.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
Updated four days ago

**Comment by CWKevo** [comment]
Installed!

**Comment by CWKevo** [comment]
Removed. [Ref.](https://discuss.flarum.org/d/7585/3828)
