### ISSUE TITLE
OneSignal web push notifications

### ISSUE THREAD

**Issue by polyjitter** [gwillem/freeflarum.com#55]
__Packagist URL for extension:__
https://packagist.org/packages/nikovonlas/flarum-ext-web-push

__Why we should install this extension?__
- You should install it because it would be immensely helpful in notifying users.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://i.imgur.com/4YEwuUO.png

**Comment by huuduy216** [comment]
@gwillem  please add  this :)

**Comment by gwillem** [comment]
I am a bit hesitant to install this, as it has many dependencies and may impact Flarum's stability. Because of COVID-19, I don't have much time to do debugging, should it go belly-up. Sorry! But perhaps I can do it when the dust has settled.

**Comment by MistikSenpa** [comment]
> I am a bit hesitant to install this, as it has many dependencies and may impact Flarum's stability. Because of COVID-19, I don't have much time to do debugging, should it go belly-up. Sorry! But perhaps I can do it when the dust has settled.

Oh ok ;(

**Comment by CWKevo** [comment]
I'll hold on installing this one, because it requires an advanced setup (uploading/moving files, etc...). I will try to search for an alternative instead.

**Comment by CWKevo** [comment]
This isn't compatible with beta.14.1 yet. We'll consider adding it when it becomes compatible with this version. I've also considered #155 as an alternative, but that has some issues too for now.

**Comment by CWKevo** [comment]
This extension has received no attention since a year and probably won't be included at FreeFlarum ever. For now, the only alternative for push notifications seems to be the "Flarum PWA" extension. If I'll find some spare time, I will debug it once again and report bugs to its author, so we could possibly include that instead.
