### ISSUE TITLE
Ability to upload Google site verification HTML

### ISSUE THREAD

**Issue by taciturasa** [gwillem/freeflarum.com#56]
As suggested by the SEO extension, it would be helpful if it was possible to upload the HTML generated by the google site manager via the root forum settings at freeflarum.com, **or at the very least to add the tag option to the forum's head.**

This would allow freeflarum sites to have a higher ranking in google search results, and would be helpful in spreading forums further.

**Comment by taciturasa** [comment]
As a note: I led with the HTML file option since it is the most recommended one by Google. However, I am unsure if this is as easily controllable. If it is not, then it would be preferable to have an option to add the tag. A potential implementation would be to have a blank for the "content" section from the tag, regex'd to ensure it's only the content portion.

meta tag looks like this:
`<meta name="google-site-verification" content="e96uJ10oBDALYrp_KVghnGgu85PBcgqmaO_v3zSML8A" />`

content looks like this:
`e96uJ10oBDALYrp_KVghnGgu85PBcgqmaO_v3zSML8A`

html contents look like this:
inside file google7f7f1c52bdb4dd57.html:
`google-site-verification: google7f7f1c52bdb4dd57.html`


This meta information is provided by Search Console:
https://search.google.com/search-console/not-verified?original_url=/search-console/ownership&original_resource_id

**Comment by xCustomWorld** [comment]
I understand what you're trying to say, however I don't think that this would be possible.

If I understood it correctly, you want an ability to upload the HTML file needed for Google to work properly. While this can be a great addition, it is also dangerous one. People could upload other files which will break the stability and safety of FreeFlarum. This applies to individual forums...

...or you want to upload the file to all forums, eg. globally, to freeflarum.com? Then this might be possible. I don't know much about this topic, I'm just listing my own ideas.

I also believe that adding the meta tag to your forum's header will do the trick. This setting is located in Admin > Appearance and Edit Header.

Correct me if I'm wrong.

**Comment by taciturasa** [comment]
Basically, yes, I would like the ability to upload the html file, which
would get around having to edit the <head> tag. The downside to that
approach is that you have to upload an arbitrary html file; however, it may
be possible to copy the content of the html file into the settings, then
create an html file for a specific forum out of that content? It appears to
be standardized content so that could be easily regulated.

The head approach doesn't do anything too complex, but I am unsure how you
place new content inside of a Flarum <head>.

Unfortunately, the "edit header" button places html content within the
<body> at the top of the page, not inside the <head> with other meta tags.

As for root-wide; this sounded like a good fix, but then i remembered that
this unfortunately works off of sitemaps, and as such it wouldn't be
possibly without some weird meta-sitemapping on freeflarum.

**Comment by taciturasa** [comment]
Update on the meta tag variety: to add to a head, it seems you need to do some weird trickery with extend.php or with injecting it weirdly through the edit header, so unfortunately probably not possible:
https://wilcosky.com/2019/05/26/how-to-add-code-to-flarums-head/

**Comment by xCustomWorld** [comment]
Yeah, you might be right. I changed the tags, because I think that this is more like a feature request rather than a bug.

~~o, you just commented, hmmmm~~
Yes, I saw some discussions about the head tags, but unfortunately for now, Flarum (and FreeFlarum) does not have the ability to modify the <head> tag. We could maybe try to wait/search for an extension that handles that, but I can't help you any further with that at the moment, sorry.

**Comment by gwillem** [comment]
I think you should file a feature request with Flarum itself. AFAIK, Flarum right now does not allow extra data in the HTML HEAD, but that may change when enough people request it.

**Comment by zartland** [comment]
Freeflarum add url to google directory but i can't verify can you help me

**Comment by CWKevo** [comment]
> Freeflarum add url to google directory but i can't verify can you help me

Any details?

Current method is to put the verification code in <head> by using the [HTML Head Items](https://discuss.flarum.org/d/25907) extension.

**Comment by zartland** [comment]
![IMG_20211205_125237](https://user-images.githubusercontent.com/95552826/144741783-f53108fb-fbe0-46ef-a54b-7917cff34dfd.jpg)
I don't know, maybe I'm doing it wrong. This is how I do it but validation is not possible

**Comment by CWKevo** [comment]
No, this is not how you do it. You can't put an entire verification HTML file inside a widget.

You can choose an alternative method of verification. You will get a `<meta>` (or other) tag and paste it into `<head>` by using HTML Head Items extension (not via a widget).

I personally don't use Google verification, so I can't help you much, but a simple Google search showed me this: https://support.google.com/webmasters/answer/9008080?hl=en#choose_method (e. g: choose "HTML Tag" and follow the instructions to get the tag to paste into `<head>`).

**Comment by zartland** [comment]
> Hayır, bu şekilde yapmıyorsun. Doğrulama HTML dosyasının tamamını bir widget'ın içine koyamazsınız.
> 
> Alternatif bir doğrulama yöntemi seçebilirsiniz. Bir `<meta>`(veya başka) bir etiket alacak ve onu `<head>`HTML Head Items uzantısını (bir widget aracılığıyla değil) kullanarak yapıştıracaksınız .
> 
> Kişisel olarak Google doğrulamasını kullanmıyorum, bu yüzden size pek yardımcı olamam, ancak basit bir Google araması bana şunu gösterdi: [https://support.google.com/webmasters/answer/9008080?hl=tr#choose_method](https://support.google.com/webmasters/answer/9008080?hl=en#choose_method) (e .g: "HTML Etiketi"ni seçin ve etiketin yapıştırılması için talimatları izleyin `<head>`).

Thanks. I submitted it to google directory
