### ISSUE TITLE
Guardian by flagrow

### ISSUE THREAD

**Issue by MrGameMemo** [gwillem/freeflarum.com#57]
> **Please request only 1 extension per issue!**

> **Bazaar or Upload extensions are not compatible with FreeFlarum. See [#18](https://github.com/gwillem/freeflarum.com/issues/18)**

__Packagist URL for extension:__
http://packagist.com/packages/flagrow/flarum-ext-guardian

__Why we should install this extension?__
- You should install it because it helps us to manage members on the forum by listing them,
- Relate user via IP's.
- Create detailed user view.
- Provides a clear page for listing users in general.

- I want this extension because I do not see how to manage my forum members or add a member to a group.

- Any more information(?)

https://discuss.flarum.org/d/1540-flagrow-guardian-an-additional-security-layer/3

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

> It is a FoF (Friends of Flarum) extension.

**Comment by xCustomWorld** [comment]
Unfortunately, this extension seems to be abandoned and incompatible :(

I checked the GitHub but last commit here was from 2 years ago. It will most likely just not work on beta.10 at the moment. You can try searching for an alternative though. There are also extensions that handle things like user lists and IP lookups already installed in FreeFlarum, please check them out.

If a question is developed by Flagrow or FoF, ot doesn't mean that it will also work. Sorry, but I think we can't really help you with that.

**Comment by MrGameMemo** [comment]
What other extension do you have for managing users on FreeFlarum.com ?
 

Envoyé: mercredi 30 octobre 2019 à 18:00
De: "xCustomWorld" <notifications@github.com>
À: "gwillem/freeflarum.com" <freeflarum.com@noreply.github.com>
Cc: "Mr Game Pro" <mrgamepro@gmx.fr>, Author <author@noreply.github.com>
Objet: Re: [gwillem/freeflarum.com] Guardian by flagrow (#57)


Unfortunately, this extension seems to be abandoned and incompatible :(

I checked the GitHub but last commit here was from 2 years ago. It will most likely just not work on beta.10 at the moment. You can try searching for an alternative though. There are also extensions that handle things like user lists and IP lookups already installed in FreeFlarum, please check them out.

If a question is developed by Flagrow or FoF, ot doesn't mean that it will also work. Sorry, but I think we can't really help you with that.

**Comment by xCustomWorld** [comment]
I use FoF Ban IPs for efficient IP banning along with FoF User Directory to list all the members. I also use Suspend for user banning too, but I think that it's enabled by default.

My forum does not need much moderation at the moment, I have low traffic and so I accept every new discussion by using the Approval extension. Any other dangerous actions are handled by carefully choosen, per-tag permissions.

Remember that you can always create a new extension request here if you find a good, up to date extension that is compatible with FreeFlarum.
