### ISSUE TITLE
Author Change

### ISSUE THREAD

**Issue by UntrustableRus** [gwillem/freeflarum.com#58]
__Packagist URL for extension:__
https://packagist.org/packages/clarkwinkelmann/flarum-ext-author-change

__Why we should install this extension?__
- I want this extension because I have posts in each category giving an overview of each category. I had a staff member write all of these and I pinned them. The staff member no longer works for me so I want to change their posts to my account. It seems that this extension allows you to change the post author.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

> Extension created 16 days ago (as this is being written)

**Comment by CWKevo** [comment]
Installed!
