### ISSUE TITLE
[request] different theme/styles to choose from

### ISSUE THREAD

**Issue by P4prik4** [gwillem/freeflarum.com#6]
I'd like to be able to choose from premade templates/themes that  use mock/placeholder pictures & links. 
Something that I can see theHTML CSS of and tweak. 
swap out pictures text and link. 
I prefer this over starting CSS from scratch. 

I'm particularly interested in many different top banner styles to choose from.

**Comment by gwillem** [comment]
That would be cool, however Flarum does not support turn-key themes yet. So somebody has to make that first ;) Please submit a feature request at the official flarum forum

**Comment by xCustomWorld** [comment]
@P4prik4 if you are friendly enough with HTML, CSS and JS, you can also play with the codes in Administration > "Appearance". This doesn't really allow people to cycle through them, but it's a good start to alter some basic elements on the page.

If you are looking for Night Mode toggle, FreeFlarum already has reflar/night-mode installed, so be sure to check it out. Optionally, you can re-create this issue with extensions you found.
