### ISSUE TITLE
NickName Changer

### ISSUE THREAD

**Issue by frankzhang05** [gwillem/freeflarum.com#61]
> **Please request only 1 extension per issue!**

> **Bazaar or Upload extensions are not compatible with FreeFlarum. See [#18](https://github.com/gwillem/freeflarum.com/issues/18)**

__Packagist URL for extension:__
https://packagist.org/packages/dem13n/nickname-changer

__Why we should install this extension?__
- I want this extension because it comes in handy when I need a separate name for displaying in the forums.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
>Flarum post: https://discuss.flarum.org/d/21238-nickname-changer
>GitHub page: https://github.com/Dem13n/nickname-changer
>Screenshots:
>>![](https://camo.githubusercontent.com/5538138bfaa9624321aaf7c5e6b75270a423d91b/68747470733a2f2f692e696d6775722e636f6d2f4c5666356c367a2e706e67)
>>![](https://camo.githubusercontent.com/1f7f0fbdf8a3dff7966a346359b94f95ec2facb1/68747470733a2f2f692e696d6775722e636f6d2f51725743734a552e706e67)
>>![](https://camo.githubusercontent.com/c4685f4bc08b4a9db7cc139e1e2fe115e1133e73/68747470733a2f2f692e696d6775722e636f6d2f676e77475172752e706e67)
>>![](https://camo.githubusercontent.com/aa5bb150c82fb3ec09858f51ef18a10007c2e8ab/68747470733a2f2f692e696d6775722e636f6d2f4d70374672646f2e706e67)
>>![](https://camo.githubusercontent.com/5c5cb8b03c80901524c06030bd347aaffd0994ad/68747470733a2f2f692e696d6775722e636f6d2f763947467659512e706e67)
>>![](https://camo.githubusercontent.com/692b87b0190a17a16d1be79407ddab4f3675d636/68747470733a2f2f692e696d6775722e636f6d2f61624a766e46392e706e67)

**Comment by gwillem** [comment]
Added!
