### ISSUE TITLE
Language Turkish Core Pack

### ISSUE THREAD

**Issue by chenzyheartseeker** [gwillem/freeflarum.com#62]
When I activate this language, flarum give me an error.

![ss](https://user-images.githubusercontent.com/51253212/69010485-56c61d00-0971-11ea-8ac7-211d3e198b8a.PNG)

**Comment by xCustomWorld** [comment]
Yes, there were indeed errors with the Turkish language pack. Recently, FF has updated the extension for latest version, however it seems to still have issues.

Keep in mind, that we do not develop extensions and bugs related to extensions should be reported to their authors.

For more information, check [this](https://discuss.flarum.org/d/7585-free-flarum-hosting-on-an-expert-platform-by-freeflarum-com/933) post.

**Comment by LeventHAN** [comment]
I did fix this issue with deleting my forum and just creating a new one. Than activating the language pack and exten. language pack.... Maybe there is some issue with old forums that were upgraded.

**Comment by gwillem** [comment]
Forums would crash if they had the Doorman extension enabled AND the Turkish language. We have removed Doorman, see also https://github.com/FriendsOfFlarum/doorman/issues/18
