### ISSUE TITLE
Arabic Language

### ISSUE THREAD

**Issue by iModyHK** [gwillem/freeflarum.com#63]
__Packagist URL for extension:__
https://packagist.org/packages/ziymed/lang-arabic

__Why we should install this extension?__
Well, Flarum is the best, and Arabian users begin to use it, and it's important to use the same language they speak to make it easier for them.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://discuss.flarum.org/d/18231-arabic-language-pack-0-1-0-beta-8-2
https://www.youtube.com/watch?v=0fxyZ4wDd60

>

**Comment by gwillem** [comment]
See this: https://github.com/gwillem/freeflarum.com/issues/35
