### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by AntoineFr** [gwillem/freeflarum.com#65]
> **Please request only 1 extension per issue!**

> **Bazaar or Upload extensions are not compatible with FreeFlarum. See [#18](https://github.com/gwillem/freeflarum.com/issues/18)**

__Packagist URL for extension:__
https://packagist.org/packages/antoinefr/flarum-ext-money

__Why we should install this extension?__

You should install this extension because it was present on the 1st version of FreeFlarum and it's quite useful to encourage users posting messages.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

I am the author of this extension 😋

**Comment by BlueWhaleYT** [comment]
How I install this to FreeFlarum?

**Comment by xCustomWorld** [comment]
@BlueWhaleYT FreeFlarum installs every extension manually, there is no way you can upload your own extensions currently. You gotta be patient until FF reviews this request.

**Comment by huuduy216** [comment]
@gwillem  please add  this :)

**Comment by MistikSenpa** [comment]
Please do :)

**Comment by gwillem** [comment]
Installed!

**Comment by gwillem** [comment]
Removed, because the MySQL server kept crashing.

**Comment by MistikSenpa** [comment]
> Removed, because the MySQL server kept crashing.

I enabled it on my forum. How can I disable it? https://forum.senpa.io

**Comment by AntoineFr** [comment]
@gwillem 

> Removed, because the MySQL server kept crashing.

Do you have any error that was logged during the crash? Because I have this extension enabled on my local installation and it doesn't crash.

**Comment by gwillem** [comment]
@AntoineFr perhaps it is the difference between 1 database and 5000 :D 
How many tables does your extension create?

**Comment by AntoineFr** [comment]
It only adds one `float` column, to the `users` table.

I saw on the discuss thread that this crash may not be related to my extension. So yes I hope you could try this later to see if it works better :)

**Comment by gwillem** [comment]
That float doesn't sound a like a deal breaker :) Will let you know when I have some time and will try it again. First, I need to find out how to reduce start-up time for MariaDB, because with the current num of databases, it takes 10 minutes to boot, so if something fails and I need to rollback, it would cause another quite long downtime.

**Comment by quitd** [comment]
any updates here?

**Comment by gwillem** [comment]
There is currently an extension freeze, because PHP-FPM experienced random crashes.

**Comment by CWKevo** [comment]
Installed, everything seems to be doing alright currently. If it will break something, it will have to be removed.
