### ISSUE TITLE
Level Ranks

### ISSUE THREAD

**Issue by yWilliamPL** [gwillem/freeflarum.com#66]
dsadasd

**Comment by yWilliamPL** [comment]
> 
> 
> dsadasd

**Comment by xCustomWorld** [comment]
Can you please explain why are you trying to catch our attention by editing your messages and messing with the issue like this?

I see every issue opened and carefully read it - they are being sent into my mail, so I instantly get them.

When I can assist with something, I reply to the issue ASAP. I saw your request too, there is no need to mess it up. But I don't have the privileges to install/update extensions, so you just have to wait for the owner of FreeFlarum to do that for you.

I also see that your request has received nice amount of upvotes, meaning that extensions like that have a great chance of being added. It's just up to someone else. Please, be patient, we all have our own personal life and people behind FreeFlarum run this service in their spare time. We all should respect that. I'm sorry.

**Comment by yWilliamPL** [comment]
DELETE PLEASE

**Comment by xCustomWorld** [comment]
> DELETE PLEASE

I don't think that we can...

**Comment by yWilliamPL** [comment]
I can't, I have to have administrator permission, only you can
![image](https://user-images.githubusercontent.com/34868604/89740905-620f2a80-da63-11ea-92b9-9eb0385aacd6.png)

**Comment by CWKevo** [comment]
You can, by clicking the big, ol' red button on the bottom of the message box.

**Comment by CWKevo** [comment]
> You can, by clicking the big, ol' red button on the bottom of the message box.
> 
> According to the link, you at least should be able to. I don't see the button.
> 
> > You can only delete issues in a repository owned by your user account. You cannot delete issues in a repository owned by another user account, even if you are a collaborator there.
> 
– GitHub
> 
> So yes, that should be admin + you.

**Comment by yWilliamPL** [comment]
![image](https://user-images.githubusercontent.com/34868604/95658321-df046200-0aef-11eb-915b-28071844cae8.png)
