### ISSUE TITLE
Russian language pack for Flarum Extensions

### ISSUE THREAD

**Issue by ikseek** [gwillem/freeflarum.com#67]
__Packagist URL for extension:__
https://packagist.org/packages/marketplace/flarum-l10n-ext-russian

__Why we should install this extension?__
- Because otherwise Russian language pack does not cover already provided extensions. If I enable _byobu_ for example, there are ugly string id's on every page.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://discuss.flarum.org/d/1545-russian-language-pack

**Comment by gwillem** [comment]
Thanks, installing rn
