### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by liriarte** [gwillem/freeflarum.com#69]
__Packagist URL for extension:__
https://github.com/FriendsOfFlarum/analytics

__Why we should install this extension?__
- To provides Piwik's and Google's analytics features to your free forums

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://discuss.flarum.org/d/1983-flagrow-analytics-extension-tracking-user-visits

**Comment by gwillem** [comment]
installed
