### ISSUE TITLE
Forums seem to be down

### ISSUE THREAD

**Issue by liriarte** [gwillem/freeflarum.com#71]
**Describe the bug**
It returns a 502 Bad Gateway. I've tried another one that I found in the issues and it is also down.

**What is your FreeFlarum host name**
crowdlending.freeflarum.com

**To Reproduce**
1. Go to https://crowdlending.freeflarum.com/
2. See error

**Expected behavior**
To render the forum

**Comment by arfonzocoward** [comment]
Also seeing the same errors here with our forum, and when testing another forum I know of.

**Comment by gwillem** [comment]
Thank you, issue has been resolved for the short term. The root cause is a bug in php-fpm, I will be looking of a way to detect and auto resolve this in the future.
