### ISSUE TITLE
User ignoring 

### ISSUE THREAD

**Issue by cocopuff2917** [gwillem/freeflarum.com#72]
> **Please request only 1 extension per issue!**
User ignoring  

> **Bazaar or Upload extensions are not compatible with FreeFlarum. See [#18]

__Packagist URL for extension:__
https://flagrow.io/extensions?q=ignore%20user

__Why we should install this extension?__
i want users to be  able to have a good time and not worry about users being rude to others  and to make sure no issues occur 

- I want this extension because... 
- Any more information(?)

> ** We only honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote. **

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__    

https://tweetcentrel.flarum.cloud/

>

**Comment by xCustomWorld** [comment]
So, what is exactly the extension you'd like?
URL that you have provided is URL to your forum, not to the extension. Please, follow up on the extension template request.

**Comment by cocopuff2917** [comment]
i would like the  https://flagrow.io/extensions?q=ignore%20user

and i want it for my community 
https://tweetcentrel.flarum.cloud/

@xCustomWorld

**Comment by xCustomWorld** [comment]
So that's https://github.com/FriendsOfFlarum/ignore-users.

If your request gets some upvotes, FF will add it.
