### ISSUE TITLE
New Extention

### ISSUE THREAD

**Issue by 15Teds** [gwillem/freeflarum.com#75]
https://discuss.flarum.org/d/4154-friendsofflarum-upload-the-intelligent-file-attachment-extension

**Comment by xCustomWorld** [comment]
1. Your request is incomplete.
2. According to #18, any extension that allows direct file uploads to FreeFlarum servers is forbidden. Sorry. If you are looking for image uploading solution, you might want to try out the imgur image upload extension which is compatible with FreeFlarum at the moment.
