### ISSUE TITLE
Math

### ISSUE THREAD

**Issue by TimotheeMathieu** [gwillem/freeflarum.com#76]
> **Please request only 1 extension per issue!**

> **Bazaar or Upload extensions are not compatible with FreeFlarum. See [#18](https://github.com/gwillem/freeflarum.com/issues/18)**

__Packagist URL for extension:__
https://packagist.org/packages/the-turk/flarum-mathren

__Why we should install this extension?__
- You should install it because...
It allows math equation to be rendered.
- I want this extension because...
I want to do a forum in which I can type maths to communicate with scientists.
- Any more information(?)
No
> ** We only honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote. **

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
See https://discuss.flarum.org/d/22439-mathren-tex-math-rendering
>

Thank you

**Comment by gwillem** [comment]
Thanks, being installed!
