### ISSUE TITLE
Hungarian language pack

### ISSUE THREAD

**Issue by mortee** [gwillem/freeflarum.com#80]
__Packagist URL for extension:__
https://packagist.org/packages/manaszon/flarum-ext-hungarian

__Why we should install this extension?__
I would like to provide a forum for a few Hungarian people, most of them elderly, and many don't speak English well.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://discuss.flarum.org/d/8931-hungarian-language-pack

Thank you!

**Comment by gwillem** [comment]
Thanks, being installed!
