### ISSUE TITLE
Forum Statistics Widget

### ISSUE THREAD

**Issue by MistikSenpa** [gwillem/freeflarum.com#82]
__Packagist URL for extension:__
https://discuss.flarum.org/d/22380-friendsofflarum-forum-statistics-widget

__Why we should install this extension?__

- I want this extension because I want to showcase the forum stats to all the members, so they can see how much the community has grown

**Comment by MistikSenpa** [comment]
Hi, has 5 thumbs ups now!

**Comment by MistikSenpa** [comment]
@gwillem

**Comment by gwillem** [comment]
Being installed, eta 30 minutes

**Comment by MistikSenpa** [comment]
> Being installed, eta 30 minutes

Has it been added?

**Comment by MistikSenpa** [comment]
@gwillem im not seeing it

**Comment by gwillem** [comment]
Indeed, something went wrong. Retrying, eta 30 min
