### ISSUE TITLE
Filter by FriendsOfFlarum

### ISSUE THREAD

**Issue by meetdilip** [gwillem/freeflarum.com#84]
> **Please request only 1 extension per issue!**

> **Bazaar or Upload extensions are not compatible with FreeFlarum. See [#18](https://github.com/gwillem/freeflarum.com/issues/18)**

__Packagist URL for extension:__
https://packagist.org/packages/fof/filter

__Why we should install this extension?__
- You should install it because...

It will help filter bad / unacceptable words from the post. Efficient when dealing with troublemakers or planning to keep the board civil.

- Any more information(?)

A discussion on this going on at Flarum Discuss

https://discuss.flarum.org/d/23429-word-filter

> ** We only honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote. **

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

>

Discussion at Flarum Discuss about this extension

https://discuss.flarum.org/d/5131-friendsofflarum-filter

**Comment by meetdilip** [comment]
@gwillem We have 5 votes now :)

**Comment by gwillem** [comment]
Installing rn...
