### ISSUE TITLE
Infinite loading ( of doom  ) wheel at the sign up. 

### ISSUE THREAD

**Issue by LaBiscornue** [gwillem/freeflarum.com#86]
**Describe the bug**
Hey ! So, I have made numbers of modifications on the forum, all roll super great in admin mode but when a new user try to sign up, the loading wheel in the popup Signup just rolling, for ever and ever. Nothing happen. No problem to sign in with my account. 

**What is your FreeFlarum host name**
fack.freeflarum.com

**To Reproduce**
1. Go to fack.freeflarum.com
2. Click on 'Inscription' top, right.
3. Try to sign Up with valid infos. 
4. See the loading wheel keep rolling. 

**Expected behavior**
Some new users be able to sign up.

Thanks for you help.

**Comment by LaBiscornue** [comment]
Today, I try to desactivate some extension, to see if something mess up with the SignUp and Suddenly : 

> An error occurred while loading the page.

No more acces to the forum. :(

**Comment by gwillem** [comment]
```
[2020-04-21 14:04:20] production.ERROR: RuntimeException: Tag 'IMG' does not exist in /app/vendor/s9e/text-formatter/src/Configurator/Collections/TagCollection.php:34
```

I think it's a bug in Flarum. Can you report this at discuss.flarum.org ?

**Comment by LaBiscornue** [comment]
Ok ! I'll do that. 
I will come back for the infinite loading if is still not working. :) 

( The link of my report on discuss.flarum.org : [https://discuss.flarum.org/d/23506-an-error-occurred-while-loading-the-page](url) )

**Comment by LaBiscornue** [comment]
Hey @gwillem  ! 
They were pretty quick to answer and so, and need your help : 

> LaBiscornue maybe you disabled both the bbcode and markdown extensions, and another extension expects the IMG tag to exist, but I think it no longer exists if both extensions are disabled.
> We'd need to find which third-party extension is trying to access the IMG tag, but this will be complicated on FreeFlarum if you end up blocking the forum everytime 😬 usually it's possible to recover by editing the enabled_extensions setting directly from the database but FreeFlarum will have to do that for you.
> If we know which extension is responsible for the issue, we can notify the developer to get a fix developed. Most likely a check is missing somewhere for the presence of that IMG tag.

Can you do that or, even better, have you a earlier backup of my freeflarum from like, 6 to 10 days earlier ? 

If yes, I take it ( one or the other ) and we can looking for the signup problem ! ^^
Thanks for your time ! <3

**Comment by gwillem** [comment]
I have reset your extension and layout settings, can you try again?

**Comment by LaBiscornue** [comment]
All working for now ! The SignUp form too. 
Thanks ! <3 

So, im wondering if it's a problem with the traduction with linguist of some extension, so that why the signup problem step up suddenly... i'll make some " test ".

**Comment by gwillem** [comment]
Hi, closing this issue as there have been no more crashes in the logs.
