### ISSUE TITLE
Portuguese language pack pt-PT

### ISSUE THREAD

**Issue by valterbarreira** [gwillem/freeflarum.com#89]
Packagist:
https://packagist.org/packages/bertaveira/flarum-pt-pt

__Why we should install this extension?__
portuguese language wasn't available for recent versions and I want to set flarum on my natural language

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):_

Current version is - v1.2.0 (updated 23/04/2020)
This language pack was tested with the flarum 0.1.0-beta.12 but should work with most versions.
https://discuss.flarum.org/d/23517-portuguese-language-pack-pt-pt

**Comment by gwillem** [comment]
being installed
