### ISSUE TITLE
[Extension Request] Imgur File Upload 

### ISSUE THREAD

**Issue by xCustomWorld** [gwillem/freeflarum.com#9]
https://discuss.flarum.org/d/18491-imgr-upload-simple-image-upload-from-the-editor

I know you disallow direct file upload, but I understood it like users could upload php files that could run dangerous scripts. This uploads image by using Imgur API and then pastes Imgur URL in the post editor (as described in the gif). 

I think that this extension is needed for every forum, as there is no way to insert image directly through the editor. If there is any other reason why to disallow file uploads, I understand. 
Either way or not, thank you for your time you are investing into ~~my spam~~ me.

**Comment by gwillem** [comment]
Added!
