### ISSUE TITLE
Passport | Friends Of Flarum

### ISSUE THREAD

**Issue by yanquisalexander** [gwillem/freeflarum.com#90]
> **Please request only 1 extension per issue!**

> **Bazaar or Upload extensions are not compatible with FreeFlarum. See [#18](https://github.com/gwillem/freeflarum.com/issues/18)**

__Packagist URL for extension:__
https://packagist.org/packages/fof/passport

__Why we should install this extension?__
Many SMEs (like the one I founded) would like to have a focused user base, in my case AB Studios Account, we know that users would not like to have to create another account to use a module

So we want to integrate our OAuth to the forum in FreeFlarum

> ** We only honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote. **

**Comment by gwillem** [comment]
Installed!

**Comment by yanquisalexander** [comment]
Thank you!

**Comment by yanquisalexander** [comment]
This extension has been removed? 🤔

**Comment by CWKevo** [comment]
> This extension has been removed? 🤔

It was, likely because it was incompatible with latest Flarum during the 1.0.0. I have re-installed it, so it should be available again after all forums are synced

**Comment by CWKevo** [comment]
Removed (again). [Ref.](https://discuss.flarum.org/d/7585/3828)
