### ISSUE TITLE
Doorman by ReFlar

### ISSUE THREAD

**Issue by DLSS604** [gwillem/freeflarum.com#92]
I'd like to request the extention Doorman by ReFlar.
this to limit registratios to people who have a referral code.

Packagist URL for extension:
https://packagist.org/packages/ReFlar/doorman

__Why we should install this extension?__
You should install it because it gives the ability to limit the people who are able to register to the ones that have a referral code keeping your community more private and making it so only people who know eachother can join, this would be really usefull for my community.

it was written for beta 8 , and still worked perfectly on beta 11.
i'm assuming it still works on beta 12, but there hasn't been a post confirming/denying it.

- Any more information(?)
more info can be found @ https://discuss.flarum.org/d/17845-doorman-by-reflar
the github page is https://github.com/FriendsOfFlarum/doorman
the packagist : https://packagist.org/packages/ReFlar/doorman

**Comment by gwillem** [comment]
See #15
