### ISSUE TITLE
flarum-ext-norwegian

### ISSUE THREAD

**Issue by bohtho** [gwillem/freeflarum.com#94]
Norwegian language pack

__Packagist URL for extension:__
https://packagist.org/packages/menomenta/flarum-ext-norwegian

__Why we should install this extension?__
You should offer it as it is missing among all the already provided language packs.

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__
https://extiverse.com/extension/menomenta/flarum-ext-norwegian

**Comment by gwillem** [comment]
Being installed..
