### ISSUE TITLE
FoF Best Answer

### ISSUE THREAD

**Issue by Aid-12114** [gwillem/freeflarum.com#98]
__Packagist URL for extension:__
https://packagist.org/packages/fof/best-answer

__Why we should install this extension?__
We should install this extension because it can help many forums/communities which have support categories like mine.

> ** We only honor extension requests that have at least 5 upvotes on this ticket. So ask your friends to upvote. **

__Proof that extension works on the latest Flarum version (eg.: statement by author, image, URL link to the statement, forum that has the extension...):__

>
![image](https://user-images.githubusercontent.com/66113140/83342278-1718be80-a320-11ea-9a75-63a22c5ccc49.png)

![image](https://user-images.githubusercontent.com/66113140/83342280-1bdd7280-a320-11ea-8c90-1ec79a171c0a.png)

![image](https://user-images.githubusercontent.com/66113140/83342284-20a22680-a320-11ea-913d-03aaad3cdb6d.png)

**Comment by killyaskill** [comment]
It would indeed be nice if this was added in!

**Comment by Bluejeanx** [comment]
> It would indeed be nice if this was added in!

Agreed!

**Comment by CWKevo** [comment]
There was a similar/possibly the same extension already requested in #17. This one seems to be updated for latest Flarum.

Also, it has 6 upvoted now, so it has a high chance of being approved 😄

**Comment by Anonymyous678** [comment]
Good idea, can you please add it?

**Comment by niteshmanav** [comment]
One more upvote. Kindly approve this. I am asking for since a year - https://github.com/gwillem/freeflarum.com/issues/17#issuecomment-521210276 :D

**Comment by CWKevo** [comment]
Installed!
