### ISSUE TITLE
GitHub Sign In Showing Incorrect Label

### ISSUE THREAD

**Issue by IeuanGol** [gwillem/freeflarum.com#99]
**Describe the bug**

Basically instead of showing "Sign in with GitHub" it says 
![](https://i.imgur.com/MchROtd.png)

**What is your FreeFlarum host name**
https://programisland.flarum.cloud/ MAIN: https://forum.programisland.cf/

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Sign up' or 'Sign in'
2. Observe the GitHub login label

**Expected behaviour**
The label should say 'Log in with GitHub'

**Comment by IeuanGol** [comment]
![](https://i.imgur.com/mEDGQFz.png)
It managed to fix itself.

**Comment by gwillem** [comment]
How?

**Comment by CWKevo** [comment]
Might be another cache issue, imo. Not sure though. Flarum translations are weird sometimes, tbh :/
